### ISSUE TITLE
Tenant could not be identified on domain 127.0.0.1 

### ISSUE THREAD

**Issue by wawerukaranja55** [stancl/tenancy#1004]
### Bug description

am getting this error when i run PHP artisan serve in my laravel application.i have stancl/tenancy package installed in my application .i havent understood about the error.whats its cause and how can i fix it

### Steps to reproduce

on opening my application by php artisan serve i get this error

### Expected behavior

on php artisan serve i expect the web application to open normally

### Laravel version

9.0

### stancl/tenancy version

3.1.0

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks
