### ISSUE TITLE
Issue with global cache

### ISSUE THREAD

**Issue by codebyoul** [stancl/tenancy#1008]
### Bug description

I have installed redis and when i try to run the Global cache test fail and all other tests run without error, this is my code: 

        $this->assertSame(null, cache('foo'));
        GlobalCache::put(['foo' => 'bar'], 1);
        $this->assertSame('bar', GlobalCache::get('foo'));
         //dd(Redis::connection('cache')->keys('*')); ----> here i have data
        $tenant1 = Tenant::create();
        dd(Redis::connection('cache')->keys('*'));----> here empty

Any idea please ?

### Steps to reproduce

1. running the global test with redis
2. add this unit test:

        $this->assertSame(null, cache('foo'));
        GlobalCache::put(['foo' => 'bar'], 1);
        $this->assertSame('bar', GlobalCache::get('foo'));
         //dd(Redis::connection('cache')->keys('*')); ----> here i have data
        $tenant1 = Tenant::create();
        dd(Redis::connection('cache')->keys('*'));----> here empty

### Expected behavior

The Global cache should not be cleared when a new Tenant is created with Tenant::create()

### Laravel version

9.0

### stancl/tenancy version

3.6

**Comment by stancl** [comment]
This isn't a bug, this is a support question, use the right channels for that.

The issue is likely related to your configuration in some way. The issue description does not provide enough context to answer this.
