### ISSUE TITLE
Issue with the cache in multithread

### ISSUE THREAD

**Issue by codebyoul** [stancl/tenancy#1016]
### Bug description

When we run the test in parallel mode, sometimes we have this exception:

       DomainTenantResolver::resolved(): Argument #1 ($tenant) must be of type Stancl\Tenancy\Contracts\Tenant, null given, at the CachedTenantResolver.php 

In the CachedTenantResolver to avoid this exception it will be better if we have something like:

          if ($tenant = $this->cache->get($key)) {
            $this->resolved($tenant, ...$args);
            return $tenant;
         }

Because the "has" method use also the "get" method

### Steps to reproduce

Run test in parallel mode -p=100 for example

### Expected behavior

Multithreading work without issue

### Laravel version

9

### stancl/tenancy version

3

**Comment by stancl** [comment]
Is this the same thing as #1005?

Strange that this is getting reported now by multiple people after 2+ years of having that code in the package. @drfraker have you encountered this in the past or only recently?

**Comment by codebyoul** [comment]
@stancl :exact the same thing, and his code fixe the issue but with mine is better
