### ISSUE TITLE
Queued Notifications are not tenant aware and produces wrong Action links 

### ISSUE THREAD

**Issue by chibyk101** [stancl/tenancy#1018]
### Bug description

I want to notify a user after registering to follow a link in the email to get to the tenant's application. And I want to queue this notification but notifications sent in a queue by implementing the ShouldQueue interface will return a weird action link that looks so  

localhost/{central_domin}/......

Instead of the tenant's domain, Localhost is treated as the tenant domain and the central domain is like a path

In the config/tenancy.php I removed every other domain in the central domain key

```php 
'central_domains' => [
      'mydomain.test',
  ],
```
  
Nothing changed.

```php
/**
     * Tenancy bootstrappers are executed when tenancy is initialized.
     * Their responsibility is making Laravel features tenant-aware.
     *
     * To configure their behavior, see the config keys below.
     */
    'bootstrappers' => [
        Stancl\Tenancy\Bootstrappers\DatabaseTenancyBootstrapper::class,
        Stancl\Tenancy\Bootstrappers\CacheTenancyBootstrapper::class,
        Stancl\Tenancy\Bootstrappers\FilesystemTenancyBootstrapper::class,
        Stancl\Tenancy\Bootstrappers\QueueTenancyBootstrapper::class,
        // Stancl\Tenancy\Bootstrappers\RedisTenancyBootstrapper::class, // Note: phpredis is needed
    ],
```

### Steps to reproduce

- Create a tenant

- Register a user for a tenant

- notify the user

```PHP
$user->notify(new WelcomeNotification)
```

- In the notification class implement the ShouldQueue Interface

```PHP
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;

class NewStudentRegistration extends Notification implements ShouldQueue
{
  use Queueable;

  public $password;
   ...
}
```
- Listen for queues with PHP artisan queue:listen

I'll also love to mention that i use nwidart/laravel-modules just to be sure it's not the cause

### Expected behavior

Emails sent to users should include the correct Tenant URL

like:  http:\\\tenant-domain.com/login

### Laravel version

9.19

### stancl/tenancy version

3.6

**Comment by stancl** [comment]
This isn't a bug because there's no such thing as a "tenant URL". A tenant can have 10 different domains. There's no way for the package to build a tenant URL.

You need to manually set the app URL roots since the job runs in a CLI environment (which has no requests or no domains).

**Comment by chibyk101** [comment]
If anyone is facing a similar challenge, just prevent using the route() method to generate a URL inside any queued Job
