### ISSUE TITLE
share keys it not functioning in tenant 

### ISSUE THREAD

**Issue by RX025** [stancl/tenancy#1028]
### Bug description

I generate a single Passport key pair for the whole app, 
 create Passport clients for tenants using tenant database seeder. but 
unfortunately end up with an error like Unable to read key from file storage/tenant\oauth-private.key and my flow is not an tenant specific its for both tenant and central app and  it should only use storage folder to read the key but not the storage/tenant. and  there is no methods under routes in passport currently. so how does it work.
"message": "Call to undefined method Laravel\\Passport\\Passport::routes()",
Passport::routes(null, ['middleware' => [
            'universal',
            InitializeTenancyByDomain::class
        ]]);

https://www.loom.com/share/9667593814b64804b8b00d9521960a56

### Steps to reproduce

Unable to read key from file file://D:\demo\laravelDemo\pradeep demo\laravel-api\storage/tenantfoo\oauth-private.key

### Expected behavior

should read key from file storage/oauth file

### Laravel version

9.19

### stancl/tenancy version

3.6

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks

**Comment by MamdouhKhaled** [comment]
Hey!
first of all thanks for this making this package 
### this may help
add this line to `AuthServiceProvider`  `boot()` method  `Passport::loadKeysFrom(storage_path());`
```php
public function boot(): void
    {
        Passport::loadKeysFrom(storage_path());
        Route::group([
            'as' => 'passport.',
            'middleware' => [
                InitializeTenancyByDomain::class, // Use tenancy initialization middleware of your choice
                PreventAccessFromCentralDomains::class,
            ],
            'prefix' => config('passport.path', 'oauth'),
            'namespace' => 'Laravel\Passport\Http\Controllers',
        ], function () {
            $this->loadRoutesFrom(__DIR__ . "/../../vendor/laravel/passport/src/../routes/web.php");
        });
    }
```
or you are in tenancy config you can 
```
        'suffix_storage_path' => false,
````

**Comment by zeliangong** [comment]
Hi @stancl, you may add this in your documentation from @MamdouhKhaled comment. It really solves the issue.
