### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'domains.tenant_id' in 'where clause'

### ISSUE THREAD

**Issue by solomon-ochepa** [stancl/tenancy#1031]
### Bug description

namespace Stancl\Tenancy\Database\Concerns;
trait HasDomains
Line: 16

```
public function domains()
{
    return $this->hasMany(config('tenancy.domain_model'), 'tenant_id');
}
```

When using a custom Tenant model (e.g. Organization), this line will throws errors; hoping the Domain table to maintain the column name tenant_id while in the real sense it must has been modify to suit whatever name the custom tenant model name is (e.g. organization_id instead).

Removing the 'tenant_id' will solve this bug.

### Steps to reproduce

```
public function domains()
{
    return $this->hasMany(config('tenancy.domain_model'), 'tenant_id');
}
```

### Expected behavior

```
public function domains()
{
    return $this->hasMany(config('tenancy.domain_model'));
}
```

### Laravel version

v9.43.0

### stancl/tenancy version

^3.6

**Comment by stancl** [comment]
Was fixed in v4, right now you can just override the method in your Tenant model

https://github.com/archtechx/tenancy/blob/7d3298c6bb40d3977770675b008ae3f138364f26/src/Database/Concerns/HasDomains.php#L19
