### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.tenants' doesn't exist

### ISSUE THREAD

**Issue by solomon-ochepa** [stancl/tenancy#1032]
### Bug description

namespace Stancl\Tenancy\Database\Models;
class Tenant
Lines: ~31, 32

```
protected $table = 'tenants';
protected $primaryKey = 'id';
```

When using custom tenant model (e.g. Organization), the package will assumed/force the database table's name to be 'tenants', of which in a real sense the developer should be allowed to name it anything.

By default, Laravel knows the name of the database table is simply the plural of the model's name (e.g. Organization model ~ organizations table).

Secondly, I don't think it's a wise idea to define the $primaryKey property here, let alone assigning a fix value to it.
By default, Laravel knows the primary id is always 'id' column, and should in case the developer wants to modify it, it should be declare from the custom tenant model.

Thanks.

Temporary Solutions:
1. comment them out.
2. define $table property in your custom model and use the name of your new custom tenant model (e.g. organizations)

### Steps to reproduce

```
protected $table = 'tenants';
protected $primaryKey = 'id';
```

### Expected behavior

```
// protected $table = 'tenants';
// protected $primaryKey = 'id';
```

### Laravel version

v9.43.0

### stancl/tenancy version

^3.6

**Comment by stancl** [comment]
You can override the `$table` property if needed. And you don't need to use `Stancl\Tenancy\Database\Models\Tenant`, you can just implement the `Stancl\Tenancy\Contracts\Tenant` contract on your own model. The `Stancl\Tenancy\Database\Models\Tenant` class is meant to provide out-of-the-box functionality that works well for most people. You are free to customize your own `Tenant` model however you want.

**Comment by solomon-ochepa** [comment]
> You can override the `$table` property if needed. And you don't need to use `Stancl\Tenancy\Database\Models\Tenant`, you can just implement the `Stancl\Tenancy\Contracts\Tenant` contract on your own model. The `Stancl\Tenancy\Database\Models\Tenant` class is meant to provide out-of-the-box functionality that works well for most people. You are free to customize your own `Tenant` model however you want.

It'll be nice if the $table property is not even define in the first place. Laravel by default has handled that aspect already as to avoid confusions and encourage simplicity.

Once a custom tenant is define, there is no point defining the $table property; except if the dev is using a customized table's name e.g. Organization model using companies, orgs, businesses etc. as it's table's name.
