### ISSUE TITLE
tenants:migrate-refresh

### ISSUE THREAD

**Issue by solomon-ochepa** [stancl/tenancy#1034]
### Description
This command will allows you to refresh your tenants migrations

### Why this should be added
migrate:fresh is not necessary all the time as this will wipe/rollback the entire database.
migrate:refresh instead is a more polite and specific command to reset only selected migrations without affecting the whole database.

### Code
https://github.com/okiaso/TenantsMigrateRefresh.php

### Installation
Just download the file to your `app/Console/Commands` directly & you can start using this command immediately.

### Usage
`tenants:migrate-refresh`
`tenants:migrate-refresh [migration-file-1.php migration-file-2.php ...more]`
`tenants:migrate-refresh [--path=database/migrations/migration-file-1.php ...more]`

**Comment by stancl** [comment]
#1017

**Comment by solomon-ochepa** [comment]
Thanks
