### ISSUE TITLE
[Feature Suggestion] InitializeTenancyByRequestData optional $header and/or $queryParameter

### ISSUE THREAD

**Issue by sneakylenny** [stancl/tenancy#1037]
### Why this should be added

For my current project I am using Tennacy for Laravel and Laravel Lighthouse (a framework for serving GraphQL from Laravel).
This means I have 1 endpoint for GraphQL queries, which is `/graphql`.
I would like to get data from the tenant databases by using a header, which is possible by using the `InitializeTenancyByRequestData` identifier and disabling the queryParameter by setting it to `null`. 
However, when I use this identifier I lose the ability to access the central database if I leave the header empty because it will throw an exception. This exception can easily be handled by setting the `$onFail` callback. As a workaround I created a new middleware (`php artisan make:middleware InitializeTenancyByHeader`) to solve this problem. In this middleware I extended the `InitializeTenancyByRequestData` since it works as intended but is missing onFail logic for this specific case, so I add the desired config and onFail logic to it:

<details>
  <summary>InitializeTenancyByHeader.php</summary>

```php
namespace App\Http\Middleware;

use Illuminate\Http\Request;
use Stancl\Tenancy\Resolvers\RequestDataTenantResolver;
use Stancl\Tenancy\Tenancy;
use Stancl\Tenancy\Middleware\InitializeTenancyByRequestData;

class InitializeTenancyByHeader extends InitializeTenancyByRequestData
{
    public function __construct(Tenancy $tenancy, RequestDataTenantResolver $resolver)
    {
        parent::__construct($tenancy, $resolver);
        self::$onFail = fn (\Throwable $exception, Request $request, \Closure $next) => $this->onFail($exception, $request, $next);
        self::$queryParameter = null;
    }

    public function onFail(\Throwable $exception, Request $request, \Closure $next)
    {
        if($request->header(self::$header)) {
            throw $exception;
        }

        return $next($request);
    }
}
```
</details>

Using this middleware I can do the following:
- Query from the central database by omitting the `X-Tenant` header.
- Query from a tenant database by putting a valid tenant id in the `X-Tenant` header.
- If the tenant doesn't exist it will throw the exception to tell me that it, in fact, does not exist.

I thought it would be great if there was a default option to make the `header` and/or `queryParameter` optional.

### Description

I have 2 proposals:
1. The "optional by type" approach:
Setting `$header` or `$queryParameter` on `InitializeTenancyByRequestData` to `null` would keep the current behavior and setting them to `false` would make them optional.
```php
// Throw exception when header is missing
$header === null 
$queryParameter === null
// Continue request when header is missing
$header === false 
$queryParameter === false // Continue request
```
2. The "static parameter" approach.
```php
InitializeTenancyByRequestData::$optional = true; // Default: false
```

1, 2 or both?

Proposal 2 may work for other identifiers too, but for this one it makes the most sense and would be easy to implement without breaking changes.

#### Note:

This feature request is a "nice to have" and not an imminent issue that is bothering me. Just sharing thoughts on improving since I commonly use this package as a multi tenant solution in my projects :)
Also, there could be a good reason on why this is a terrible idea. Which, if so, I would like to learn more about.

**Comment by stancl** [comment]
> However, when I use this identifier I lose the ability to access the central database if I leave the header empty because it will throw an exception

Can you expand on this a bit?

**Comment by sneakylenny** [comment]
> Can you expand on this a bit?

I am hitting just 1 endpoint (`http://api.mysite.com/graphql`) for both central and tenant applications. I only want to connect to a tenant when the header is present. Now, I either connect to the tenant database or get an exception (`TenantCouldNotBeIdentifiedByRequestDataException`) when the header is not present __or__ incorrect. I want the option to only throw the exception when the header __is__ present __and__ incorrect.
I thought it would be more convenient to check if the header or query pram exists first, and then after that, check if the tenant can be identified. That way the script can continue when desired (by omitting the header). Allowing me to hit the same endpoint to connect to the central database if the header is not present.

**Comment by stancl** [comment]
There is a check for `hasHeader()`: https://github.com/archtechx/tenancy/blob/84a32877994bfd2ed303240f9e24709c74c809e6/src/Middleware/InitializeTenancyByRequestData.php#L54

And the header is not used at all when it's not provided.

If you want to make the route accessible even when the tenant is not provided *in any way at all*, you can use [universal routes](https://tenancyforlaravel.com/docs/v3/features/universal-routes) for that.

**Comment by sneakylenny** [comment]
This will be a Lighthouse only feature then.
Laravel Lighthouse registers the route itself based on set config, which is where I put the tenancy middleware. 
I have found no way in their docs to disable this and/or manually registering the route. I've tried it, but could not manage to get it stable (server wouldn't start up or connect). 
If I happen to get it working I will post it here but that chance will be small since the middleware solution works well too.

So I will close this features request and suggest anyone who is looking for a solution to just simply write their own middleware or $onFail logic.

Thanks for taking the time to think along @stancl !

**Comment by sneakylenny** [comment]
For those wondering: After a refactor I found out this issue can easily solved by extending the `InitializeTenancyByRequestData` class and overwriting the handle method:

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Config;
use Stancl\Tenancy\Contracts\TenantCouldNotBeIdentifiedException;
use Stancl\Tenancy\Middleware\InitializeTenancyByRequestData as TenancyInitializeTenancyByRequestData;

class InitializeTenancyByRequestData extends TenancyInitializeTenancyByRequestData
{
    /**
     * Disable the query param option (optional but useful in my case).
     */
    public static $queryParameter = null;

    public function handle($request, Closure $next)
    { 
        //                          Important: add a check if a payload was present.
        //                                                |
        //                                                V
        if ($request->method() !== 'OPTIONS' && $this->getPayload($request)) {
            return $this->initializeTenancy($request, $next, $this->getPayload($request));
        }

        return $next($request);
    }
}
```

By adding this check, my issue described in my initial comment is resolved. The middleware will now behave as intended for my needs:
- If I request to `/graphql` **without** the `X-Tenant` header, the tenant won't be initialized and it will query from the central database.
- If I request to `/graphql` **with** the `X-Tenant` header **with** a valid/matching tenant id, it will query from the tenant database
- If I request to `/graphql` **with** the `X-Tenant` header **without** a valid/matching tenant id, it will throw the `TenantCouldNotBeIdentifiedException`.
