### ISSUE TITLE
using Model::shouldBeStrict(); cause database error  

### ISSUE THREAD

**Issue by satis-apex** [stancl/tenancy#1041]
### Bug description

laravel with new feature on  model restrict 
adding following methods on appServiceProvider database issue occurs and also cannot create tenant through tinker
 "Model::shouldBeStrict(!$this->app->isProduction());"
issue on tinker
"The attribute [tenancy_db_connection] either does not exist or was not retrieved for model [App\Models\Tenant]."

### Steps to reproduce

add the following method on boot in AppServiceProvider.php
Model::shouldBeStrict(!$this->app->isProduction())

### Expected behavior

tenancy_db_connection issue should not occur

### Laravel version

9.35

### stancl/tenancy version

3.6

**Comment by stancl** [comment]
Using `shouldBeStrict()` is not supported on the `Tenant` model because of the data column.

**Comment by joelstein** [comment]
This is possible by disabling the strictness flags on the Tenant model.

For example:

```php
class Tenant extends BaseTenant implements TenantWithDatabase
{
    protected static $modelsShouldPreventLazyLoading = false;
    protected static $modelsShouldPreventSilentlyDiscardingAttributes = false;
    protected static $modelsShouldPreventAccessingMissingAttributes = false;
}
```

Then it's possible to use strictness on all other models:

```php
class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        Model::shouldBeStrict(TRUE);
    }
}
```

@stancl, will you consider adding this to `Stancl\Tenancy\Database\Models\Tenant` and updating the docs to mention that Tenant classes have strictness disabled by default?

**Comment by stancl** [comment]
Great suggestion, could you send a PR?

I'm thinking that only the "accessing missing attributes" property matters here. Perhaps "silently discarding attributes too"? It's not very clear what it does from the name.

**Comment by joelstein** [comment]
You're right—we only need to change the `$modelsShouldPreventAccessingMissingAttributes` property.

I'll create a PR. Thanks!

**Comment by joelstein** [comment]
Thanks!
