### ISSUE TITLE
Identify tenant from parameter in POST request  exemple : 

### ISSUE THREAD

**Issue by elmarzouguidev** [stancl/tenancy#1046]
#### Description

Identify tenant from parameter in POST request  exemple : 

I have one subdomain for the all tenants : cloud.mysaas.com
how to initialize the current tenant with POST method not query parameter ??
exemple : 
I have Login form like that :  cloud.mysaas.com/login

**Comment by stancl** [comment]
Use the issue templates properly, and for support use our [Discord](https://archte.ch/discord).
