### ISSUE TITLE
Undefined constant 'STDIN' when run 'tenants:seed' command on production mode

### ISSUE THREAD

**Issue by yazanqwaider** [stancl/tenancy#1047]
When the **SeedDatabase** Job has been called on production, the "undefined constant '**STDIN**'" has fired.

If you added the _--force_ option on this command and another commands like that are running programmatically, it will be great.

[This line of code](https://github.com/archtechx/tenancy/blob/84a32877994bfd2ed303240f9e24709c74c809e6/src/Jobs/SeedDatabase.php#L34)

**Comment by stancl** [comment]
https://github.com/archtechx/tenancy/blob/84a32877994bfd2ed303240f9e24709c74c809e6/assets/config.php#L197

**Comment by yazanqwaider** [comment]
Thank you
