### ISSUE TITLE
Initialize Tenant by subdomain or domain via helper method

### ISSUE THREAD

**Issue by JCEC007** [stancl/tenancy#1051]
Thanks a lot for this repo, has been of great help for us, 

Right now we are needing other way to initialize a tenant(other than via middleware), because we need to initialize the tenant long before the laravel boot, we are using the laravel-modules package and it's necessary to boot and register the submodules before the middleware has you know.

I was reviwing the code to try to create a helper, but as I can see all the initialization is quite complex and nested within middleware. 

If you plan this or thinks this could be a good idea, let me know and I could try some solution. of course, with your help to start 😁

**Comment by stancl** [comment]
> because we need to initialize the tenant long before the laravel boot

Impossible.

> but as I can see all the initialization is quite complex and nested within middleware.

It's not. You can initialize a tenant without any middleware or routing logic. But not before Laravel boot.

Also, for support questions I recommend using [our Discord](https://archte.ch/discord).

**Comment by JCEC007** [comment]
I'm sorry, I will try to rephrase my question,

We area using laravel-modules package, that package injects the submodules in the laravel booting, we change the logic of that package to get the enabled modules from database insted of json file, but that modules are booting before the tenant middleware, finnally is booting the modules enabled in the central DB.

The thing is: could be possible another helper passing the request()->getHost(), based in the domain or subdomain to know who tenant is trying to run?

Right now, the current helper is based in the tenant id, but it will be great if we pass the current request host and return the tenant object.
 
 PD.: Is not necesssary initialize the tenant, could be optional, or a new method called: findByDomainOrSubdomain
