### ISSUE TITLE
tenancy()->tenant returns null

### ISSUE THREAD

**Issue by amirtavakolian** [stancl/tenancy#1055]
### Bug description

hi. i have used tenancy package in my project and i have done all installation steps correctly.
but i do not know why dump(tenancy()->tenant) returns null and when i want to get data from database, it sends request to central domain database not tenant database 

### Steps to reproduce

..

### Expected behavior

get data from tenant database

### Laravel version

9

### stancl/tenancy version

3.6

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks
