### ISSUE TITLE
Tenancy commands are not listed after the the package installed in Laravel-8

### ISSUE THREAD

**Issue by vinothmallow** [stancl/tenancy#1056]
### Bug description

Am using the laravel **8.83.27** version, in this, I tried to install the packages and it was successfully installed, after the installation I use the php artisan to view the tenancy command but the commands are not listed. So I decided to create a custom command by copying the existing the command present inside the vendor folder, In this, I also faced an error during running the php artisan 

  **Illuminate\Contracts\Container\BindingResolutionException 

Target [Illuminate\Database\Migrations\MigrationRepositoryInterface] is not instantiable while building [App\Console\Commands\CustomTenantsRollback, Illuminate\Database\Migrations\Migrator].**

**The above error also fixed by the below way**

public function __construct()
    {
        $migrator = app("migrator");
        parent::__construct($migrator);

        $this->specifyTenantSignature();
    }
Previously it was
public function __construct(Migrator $migrator)
    {
        parent::__construct($migrator);

        $this->specifyTenantSignature();
    }

After the above error was fixed, I tried to create a tenant but the tenant database are not created, 'data' column present a null value. could you please help me how to fix this error in laravel-8.

FYI
This package working well in Laravel-9

### Steps to reproduce

Install laravel 8.83.27
Install the package stancl/tenancy 3.6.1
Create a tenant via tinker

### Expected behavior

Expected output

Psy Shell v0.11.11 (PHP 8.1.11 — cli) by Justin Hileman

> use App\Models\Tenant;
> $tenant = Tenant::create();
= App\Models\Tenant {#3844
    id: "0ffbc195-e9e1-4d90-99b4-cd072991518f",
    data: null,
    updated_at: "2023-02-07 02:25:58",
    tenancy_db_name: "tenant0ffbc195-e9e1-4d90-99b4-cd072991518f",
  }

But it return in laravel 8.83.27

Psy Shell v0.11.12 (PHP 8.0.24 — cli) by Justin Hileman
> 
> $tenant = App\Models\Tenant::create();
= App\Models\Tenant {#3670
    id: "bd3379bf-7bd2-4a15-9780-edeec24ffa5d",
    updated_at: "2023-02-07 02:33:24",
    created_at: "2023-02-07 02:33:24",
    data: null,
  }

### Laravel version

8.83.27

### stancl/tenancy version

3.6.1

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks
