### ISSUE TITLE
Error when trying to run Tinker to create tenant

### ISSUE THREAD

**Issue by devnart** [stancl/tenancy#1059]
### Bug description

When following the quick start documentation of stancl/tenancy from https://tenancyforlaravel.com/docs/v3/quickstart, When I reach the last step which is running tinker I get the following error : 

   Stancl\Tenancy\Exceptions\TenantDatabaseAlreadyExistsException  Tenant cannot be created. Reason: Database tenantfoo already exists.

![image](https://user-images.githubusercontent.com/47011625/217930586-ceb3a694-fa0c-45f7-bab2-85ab3d7df86c.png)

Despite this error the tenant is created in the database, is it maybe related to version of Laravel ? I'm using Laravel v9.51.0

### Steps to reproduce

-> php artisan tinker
-> tenant1 = App\Models\Tenant::create(['id' => 'foo']); 

### Expected behavior

don't know

### Laravel version

9.51.0

### stancl/tenancy version

3.6

**Comment by emibytes** [comment]
Did you manage to fix the problem?

**Comment by stancl** [comment]
There's nothing to fix, the exception says what's wrong. There already is a `tenantfoo` database. To be able to create a tenant with the ID of `foo` you should delete that database.
