### ISSUE TITLE
[Feature Suggestion] Set database host for only reading

### ISSUE THREAD

**Issue by rodrigoalexandrino** [stancl/tenancy#1063]
#### Description
I'm using Laravel with Tenancyforlaravel in my project and it's deployed on AWS, I also use RDS for database management (Postgres in my case).

In peak moments where I have thousands of users accessing the application, the system is slow and the first thing to crash is the database. I've done several query optimizations and put cache in every possible place.

I know that in Laravel it is possible to select a read-only and a write-only database host (in the config/database.php file). I would like to know if there is a way to configure this per tenant, so each one would have their own read and write host

**Comment by stancl** [comment]
Not a feature we have at this moment. If someone wants to research how it could be used it here, and write up the high level implementation, I might consider it.
