### ISSUE TITLE
Getting Tenant Object from the Tenant DB

### ISSUE THREAD

**Issue by JCEC007** [stancl/tenancy#1067]
### Bug description

Hi, first thanks for this package, has been helpfull for us.

We have this case, we have a central DB with users and tenants, our system creates a tenant and then inserts the central user in the tenant DB so that all the login process work inside the tenant, but the tenant model is in the central DB, we want to offer a form to each client to see their own Organizations(tenants) and make adjustments, but when we search the organizations from the tenant domain we see that the query is always done in the central.

Because of this we inserted the Organization(Tenant) table in the tenant DB and we seeded all the data of the Organization into the tenant table, only the Organizations of that tenant, but still continues to query to the central insted of the tenant DB.

We also made a one to many relationship between the model User and Organization and when we try to call the relation it makes the query to the central.

Maybe we are missing something of configuration or maybe this kind of functionallity needs to have more work around processes?

thanks for your time!

### Steps to reproduce

.

### Expected behavior

.

### Laravel version

8

### stancl/tenancy version

3.5.1

**Comment by stancl** [comment]
Please follow the issue template when filling out bug reports. If this is a support question, you can ask on our Discord.
