### ISSUE TITLE
Unable to register a Tenant through controller

### ISSUE THREAD

**Issue by ArsalanSiddique** [stancl/tenancy#1073]
### Bug description

```
$ php artisan tinker
>>> $tenant1 = App\Models\Tenant::create(['id' => 'foo']);
>>> $tenant1->domains()->create(['domain' => 'foo.localhost']);

```

The above commands are working fine on CLI

but when I write them in the controller and link them with a form then, domains are inserted, tenants are inserted and a new database is successfully created with the name of the tenant 

```
$subdomain = $request->subdomain;
$subdomain_link = $subdomain.".locahost";

$tenant = \App\Models\Tenant::create(['id' => $subdomain]);
$tenant->domains()->create(['domain' => $subdomain_link]);
```

the above code is my controller code and the issue is when I hit the route it returns 

`Tenant could not be identified on domain app.localhost`

### Steps to reproduce

```
$subdomain = $request->subdomain;
$subdomain_link = $subdomain.".locahost";

$tenant = \App\Models\Tenant::create(['id' => $subdomain]);
$tenant->domains()->create(['domain' => $subdomain_link]);
```

### Expected behavior

When I run my controller code this is doing all the things find, but I hit the route I am getting

`Tenant could not be identified on domain ccnm.localhost
`

### Laravel version

10.0.2

### stancl/tenancy version

3

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks
