### ISSUE TITLE
TenantConfig mail settings not working with queue:work

### ISSUE THREAD

**Issue by iolk** [stancl/tenancy#1074]
### Bug description

When using TenantConfig to set email configurations with queue:work, all the email notifications sent will use the mail configuration of the tenant associated with the first notification that was sent. 

![emails-1](https://user-images.githubusercontent.com/11891210/220388963-a3a60679-f0a2-40ea-9f2d-07125ac40b7c.png)

However, the configurations and tenant data inside the email notification will be correct.

![emails-2](https://user-images.githubusercontent.com/11891210/220390296-d68f9526-3703-459d-b1f7-339e82f866b1.png)

### Steps to reproduce

All the steps to reproduce are in README.md of the following repo: https://github.com/iolk/laravel-tenancy-bug

### Expected behavior

Emails should use the correct 'mail.from.name' and 'mail.from.address' for the given tenant.

### Laravel version

10.0.3

### stancl/tenancy version

3.7.0

**Comment by stancl** [comment]
That's not a bug with the TenantConfig feature. It's meant to set config keys and it does that.

The issue here is that there's a singleton in the service container which loads the value from the config *once* and then it always uses that.

We added a feature for tenant-specific mail credentials in v4.

**Comment by mshamaseen** [comment]
@stancl could you provide more context about that?
we are facing this issue and emails are triggered from the incorrect tenant when using queueable emails
Altho I can see in the email content that the data is for the correct tenant, it just uses the wrong SMTP key to send the email

**Comment by stancl** [comment]
Changing the config isn't enough for mail since it gets loaded into a singleton and never read again.

**Comment by mshamaseen** [comment]
@stancl any suggested workaround for that?

**Comment by mcorraodab** [comment]
@stancl it would be great if you could provide any directions for those still working with tenancy v3

Thanks a lot!

**Comment by egekibar** [comment]
same

**Comment by stancl** [comment]
https://github.com/archtechx/tenancy/blob/master/src/Bootstrappers/MailConfigBootstrapper.php
