### ISSUE TITLE
Is there any plan to support Multi Tenancy with Database Sharding

### ISSUE THREAD

**Issue by khanakia** [stancl/tenancy#1080]
#### Description
Is there any plan to have multiple databases and each database further can have hosted multiple tenants so basically it is Hybrid Database Sharding?

#### Why this should be added
To utilize resources better and save costs. Every big company followed this approach.

Some Sources:
https://www.notion.so/blog/sharding-postgres-at-notion
https://www.atlassian.com/engineering/scaling-rearchitecting-and-decomposing-confluence-cloud
https://www.lucidchart.com/techblog/2013/04/12/scaling-a-startup-with-database-sharding/
https://shopify.engineering/mysql-database-shard-balancing-terabyte-scale

![ThreeMultiTenantApproaches](https://user-images.githubusercontent.com/2174170/222928886-b329b55e-1d38-4290-a7ed-9a3b752dc0c6.png)

**Comment by stancl** [comment]
You can already do this. Just create several DB connections and then have some logic for assigning each tenant to the right connection by setting the [`tenancy_db_connection` property](https://tenancyforlaravel.com/docs/v3/customizing-databases/).

**Comment by khanakia** [comment]
Thanks. I will try this and see if i can achieve the **HYBRID** tenancy.

**Comment by khanakia** [comment]
I followed the quick start tutorial however it creates a separate database and i do not see a way to make it HYBRID Mult Tenant + Single Tenant

Secondly, do you have any docs which show how to achieve the hybrid tenancy exactly?

**Comment by stancl** [comment]
Support questions should go on our Discord.
