### ISSUE TITLE
When I run the tests, an unknown file is created in the DATABASE directory for each test

### ISSUE THREAD

**Issue by drezaei1993** [stancl/tenancy#1081]
### Bug description

When I run the tests, an unknown file is created in the DATABASE folder for each test
![2](https://user-images.githubusercontent.com/109957391/223060614-335aea89-3ef1-4b84-8f65-fccde096f768.png)

### Steps to reproduce

When I run the tests, an unknown file is created in the DATABASE folder for each test

### Expected behavior

Such a file should not be created

### Laravel version

8.83.14

### stancl/tenancy version

3.4

**Comment by stancl** [comment]
It's not an unknown file, it's a sqlite database following the DB naming pattern configured in `config/tenancy.php`. There's currently no cleanup logic out of the box, so you can just gitignore the files and delete them once in a while. Or you can customize your testing setup to handle this for you.

Keep in mind that things related to the testing setup are the responsibility of the application, not the package, so this wouldn't really be a bug either way.
