### ISSUE TITLE
Tests are very slow

### ISSUE THREAD

**Issue by drezaei1993** [stancl/tenancy#1082]
### Bug description

Hi,
Each test takes between 20 and 50 seconds
![2](https://user-images.githubusercontent.com/109957391/223125377-6e3efd68-75a1-4c62-8059-96a9f8cf3bea.png)

### Steps to reproduce

Each test takes between 20 and 50 seconds

### Expected behavior

It should be executed in less time

### Laravel version

8.83.14

### stancl/tenancy version

3.4

**Comment by i74ifa** [comment]
According to what I understand, this reason lies behind the create of a new tenant, every test process

You can adjust a database of the test in phpunit.xml will be relatively faster.

**Comment by stancl** [comment]
@drezaei1993 Please don't spam our issue tracker with false bug reports without first reading documentation, searching existing threads, and using appropriate support channels.
