### ISSUE TITLE
Event Events\TenantCreated Tenant instance missing columns.

### ISSUE THREAD

**Issue by SergkeiM** [stancl/tenancy#1086]
### Bug description

Event `Events\TenantCreated` Tenant instance missing columns.

### Steps to reproduce

Schema:

```php
Schema::create('tenants', function (Blueprint $table) {
            $table->string('id')->primary();
            $table->string('name');
            $table->bigInteger('repository_id')->nullable()->index();
            $table->string('framework')->default('vue');
            $table->json('data')->nullable();
            $table->timestamps();
        });
```

My Tenant Model:

```php
<?php

namespace App\Models;

use Stancl\Tenancy\Database\Models\Tenant as BaseTenant;
use Stancl\Tenancy\Database\Concerns\HasDomains;
use Stancl\Tenancy\Database\Concerns\MaintenanceMode;

class Tenant extends BaseTenant
{
    use HasDomains, MaintenanceMode;

    public static function getCustomColumns(): array
    {
        return [
            'id',
            'name',
            'repository_id',
            'framework',
        ];
    }
}
```

in 

```php
Events\TenantCreated::class => [
            JobPipeline::make([
                CustomJobs\CreateFilesystem::class
            ])->send(function (Events\TenantCreated $event) {
                dd($event->tenant); //
                return $event->tenant;
            })->shouldBeQueued(true),
        ],
```

`dd` outputs model but missing columns:

![image](https://user-images.githubusercontent.com/3294939/224356686-e1967050-7193-49fe-a9a9-4e70669144d5.png)

### Expected behavior

Attributes should have a `repository_id` and `framework`

### Laravel version

10.3.3

### stancl/tenancy version

3.7.0

**Comment by stancl** [comment]
If you didn't define the customs as custom columns (see docs), and didn't put any data in them, then they will not appear in `dd($tenant)` because they aren't set.

**Comment by stancl** [comment]
Ah I see the custom columns method in your code now (normally that would be the cause of this issue). Then check that you're actually setting the values, or show the code where you are setting those values.

Either way, custom columns work fine and retain data even in events/listeners (it doesn't matter where you use the model), so this isn't a bug in the package. For help with your setup you can ask on our [Discord](https://archte.ch/discord).
