### ISSUE TITLE
Following valid tenant with a period will result in  TenantCouldNotBeIdentifiedOnDomainException

### ISSUE THREAD

**Issue by bcbud** [stancl/tenancy#1088]
### Bug description

Following up a valid tenant domain with a period causes a  
TenantCouldNotBeIdentifiedOnDomainException error.

### Steps to reproduce

1) Set up valid domain.
2) Config domain tenancy @ http://tenant.test
3) Visit http://tenant.test.  <-- note trailing period.

### Expected behavior

Trailing period on a valid domain name should just default to the root domain index.
Should just load the default index page.
Should not cause an error.

(guessing it's just a tweak to the domain/tenant matching routine).

### Laravel version

9.52.4

### stancl/tenancy version

3.7.0

**Comment by stancl** [comment]
We just work with what `$request->getHost()` gives us. If people are visiting your site on `.com.`, that should probably be handled on the webserver level by redirecting them to the proper domain. Alternatively if you think this should be handled in PHP, it's something to submit to Laravel. Don't think there's really any reason for people to be visiting `.com.` domains so it's not something our package should be handling (from our POV it's essentially invalid input and it's the webserver's responsibility to normalize these things).

For reference:
- `google.com.` redirects to `google.com`, likely at webserver level
- `twitter.com.` doesn't work at all
- `facebook.com.` redirects to `facebook.com`, same as Google
- `github.com.` same as FB and Google
