### ISSUE TITLE
Saving failed queues in the tenant database

### ISSUE THREAD

**Issue by nino-giacca** [stancl/tenancy#1090]
### Bug description

Using multi-database tenancy queue errors are not saved in the tenant table but in the central table

### Steps to reproduce

Commenting out QueueTenancyBootstrapper and submitting a job to the queue, it is correctly saved in the "jobs" table of the tenant. Request run queues using `php artisan tenants:run queue:work --tenants=demo --option="queue=test"`

The job launches successfully from the queue table.
If the job fails, the error is not saved in the "failed_jobs" table of the tenant but in the central database table.

### Expected behavior

I expect errors to be saved in the "failed_jobs" table of the tenant they are run from

### Laravel version

8.83.27

### stancl/tenancy version

3.6.1

**Comment by stancl** [comment]
Not a bug. Everything queue-related remains in the central DB. There's no way a single queue worker could know which tenant DB has a new job/new failed job etc. The docs mention this.
