### ISSUE TITLE
Allow databases to be created independently of tenants

### ISSUE THREAD

**Issue by inmanturbo** [stancl/tenancy#1092]
I have a use case able to create the databases independently of the tenant.

My requirements are for the user on the landlord app to be able to create databases and assign them a name, then create tenants and select one of their **owned databases** when doing so. This allows them to create more  than one tenant on the same database when all the data needs to be the same aside from the users and some metadata which is stored in the landlord database. Users and other core and auth models are actually all stored in the landlord database, but all the data managed by the tenant app itself is stored in a tenant database. 

Note there are tens and tens of tables and it doesn't make sense to [sync](https://tenancyforlaravel.com/docs/v3/synced-resources-between-tenants) them all when everything BUT the users and some metadata needs to stay in sync.

If I am not mistaken this can't be done using the current implementation without significant customization -- removing the create database job and maintaining one's own database managers -- as it ties databases -> tenants tightly one to one. It looks like the configuration details are stored schemalessly in array or json column in on tenants, then databases are created for the tenant after the fact.

To me this seems like an architectural shortcoming in the way the package sets up the multi-database scenario: database managers are depending on the tenant when actually the tenant should have a (managed) database dependency. 

Note that migrations should be able to be run at the database level, while there may be other artisan commands and jobs which should be able to be run at the tenant level.

One way achieve this functionality is to explode all the details used by the database managers into its own model, something like `ManagedDatabase` with its own event life cycle, then allow the  `DatabaseManagers` to depend on this instead of the tenant. This would make the `Tenant` model's  relationship to the managed database fairly trivial and easy to work with, e.g:

```php
public function managedDatabase() : BelongsTo
{
    return $this->belongsTo(ManagedDatabase::class);
}
```

The inverse could easily be defined as has one, or in my case maybe overridden to has many.

**Comment by stancl** [comment]
You can create a tenant like this:

```php
Tenant::create([
    'tenancy_db_name' => 'your-precreated-database-name',
    'tenancy_create_database' => false,
]);
```

See this: https://github.com/archtechx/tenancy/blob/d4a99011e602cde65e708b67046d4c4cb13749b6/src/Jobs/CreateDatabase.php#L35

**Comment by inmanturbo** [comment]
Thanks for the quick response! And the info! This indeed solves a big part of the issue. However it still requires maintaining one's own library for managing databases, or creating some kind of "fake" tenant class to implement the `TenantWithDatabase` interface.

```php
    /**
     * Create a database.
     */
    public function createDatabase(TenantWithDatabase $tenant): bool;
```
This seems a little out of order, we couldn't truly have a tenant with a database without first creating a database. :smile:

**Comment by stancl** [comment]
You can either use the main approach we have or create databases yourself and then create the tenants. It doesn't really make sense for the package to let you call `createDatabase()` and use those with `tenancy_create_database`, since the whole point of that is that you'll be creating databases in a custom way, otherwise you would've used the standard approach.

So you should write your own code that calls `CREATE DATABASE` and sets up the database the way you want.

**Comment by inmanturbo** [comment]
I understand. Thank you for your time and comments.

**Comment by inmanturbo** [comment]
@stancl Unfortunately this doesn't seem to work. I must be missing something here?

```php
$this->tenant->getInternal('create_database') ;
```
always seems to return null. If I dd() any key in the event with `$this->tenant->getInternal($key)` I always get null.

Further inspection shows the model attributes in a flat structure. `data`  is shown as `null` but the values present in the data column in the database are accessible as first class properties on the model, i,e:

```
= App\Models\Tenant {#5133
    id: "8b7cac83-97e8-4d2c-948d-68c32039da8b",
    data: null,
    updated_at: "2023-03-20 23:45:51",
    created_at: "2023-03-20 23:45:51",
    create_database: false,
    tenancy_db_name: "tenant8b7cac83-97e8-4d2c-948d-68c32039da8b",
  }
```

so if I dump `$this->tenant->create_database;` I get `true // vendor/stancl/tenancy/src/Jobs/CreateDatabase.php:...`

**Comment by stancl** [comment]
The code I wrote works and is tested. If you need help with that I recommend asking on [our Discord](https://archte.ch/discord).

**Comment by inmanturbo** [comment]
I'm sorry, as a correction, if I dump `$this->tenant->create_database;` I get `false // vendor/stancl/tenancy/src/Jobs/CreateDatabase.php:...`

not true.

What is strange is the flattening of the data structure in the model. `$this->tenant->create_database` works fine. putting this here for future reference. I'm sure I'll figure it out.

**Comment by stancl** [comment]
The code I linked works with `getInternal('create_database')`, **not** `->create_database`.

**Comment by inmanturbo** [comment]
> The code I linked works with `getInternal('create_database')`, **not** `->create_database`.

Yes I see that. But when I dump the tenant the values are shown as a flat structure, and `data` is shown as `null`, the values are there, but are accessible directly, but not through `getInternal()`. It's as though the internals are being cast somehow as if they were real columns.

**Comment by inmanturbo** [comment]
I have figured out what I was doing wrong. I was using the following test:

```php
it('will know not to create a database', function () {
    $tenant = Tenant::create(['create_database' => false]);

    $this->assertSame(false, $tenant->getInternal('create_database'));
});
```

I missed the `tenancy` prefix

it shows the code in the package working correctly with 

```diff
it('will know not to create a database', function () {
-   $tenant = Tenant::create(['create_database' => false]);
+   $tenant = Tenant::create(['tenancy_create_database' => false]);
    $this->assertSame(false, $tenant->getInternal('create_database'));
});
```
Thanks for the help. Apologies for the noise.

**Comment by stancl** [comment]
Yeah, `getInternal()` (our own method) uses keys with the `tenancy_` prefix. To get a normal attribute it's `getAttribute()` (Laravel method).
