### ISSUE TITLE
Call to a member function where() on string

### ISSUE THREAD

**Issue by ajaythakkar** [stancl/tenancy#1097]
### Bug description

Call to a member function where() on string {"exception":"[object] (Error(code: 0): Call to a member function where() on string at /var/www/html/vendor/stancl/tenancy/src/Resolvers/DomainTenantResolver.php:60)

### Steps to reproduce

tenant not accessible Call to a member function where() on string

### Expected behavior

Call to a member function where() on string {"exception":"[object] (Error(code: 0): Call to a member function where() on string at /var/www/html/vendor/stancl/tenancy/src/Resolvers/DomainTenantResolver.php:60)

### Laravel version

9.19

### stancl/tenancy version

3.7

**Comment by ajaythakkar** [comment]
Need to update  : DomainTenantResolver.php
 
 protected function setCurrentDomain(Tenant $tenant, string $domain): void
    {
       //static::$currentDomain = $tenant->domains->where('domain', $domain)->first();
        static::$currentDomain = $tenant->domains()->where('domain', $domain)->first(); // domains()
    }

**Comment by stancl** [comment]
Not a bug in the package.

`domains` will never return a string if the model is structured as the package expects. If you're using a string `domains` property, you need to update the rest of the logic as well.

> `$tenant->domains()`

This would break the cached resolution logic. We're using `$tenant->domains` intentionally.

**Comment by ajaythakkar** [comment]
<?php

namespace App\Models;

use Stancl\Tenancy\Database\Models\Tenant as BaseTenant;
use Stancl\Tenancy\Contracts\TenantWithDatabase;
use Stancl\Tenancy\Database\Concerns\HasDatabase;
use Stancl\Tenancy\Database\Concerns\HasDomains;

class Tenant extends BaseTenant implements TenantWithDatabase
{
    use HasDatabase, HasDomains;

   
}

here it is the model

**Comment by ajaythakkar** [comment]
<?php

namespace App\Models;

use Stancl\Tenancy\Database\Models\Tenant as BaseTenant;
use Stancl\Tenancy\Contracts\TenantWithDatabase;
use Stancl\Tenancy\Database\Concerns\HasDatabase;
use Stancl\Tenancy\Database\Concerns\HasDomains;

class Tenant extends BaseTenant implements TenantWithDatabase
{
    use HasDatabase, HasDomains;

    public function domain()
    {
        return $this->hasOne(Domain::class,'tenant_id','id');
    }
}

**Comment by ajaythakkar** [comment]
`<?php

namespace App\Models;

use Stancl\Tenancy\Database\Models\Tenant as BaseTenant;
use Stancl\Tenancy\Contracts\TenantWithDatabase;
use Stancl\Tenancy\Database\Concerns\HasDatabase;
use Stancl\Tenancy\Database\Concerns\HasDomains;

class Tenant extends BaseTenant implements TenantWithDatabase
{
    use HasDatabase, HasDomains;

    
}
`

**Comment by ajaythakkar** [comment]
This is my model structure, Please look into it and help me  :

<?php

namespace App\Models;

use Stancl\Tenancy\Database\Models\Tenant as BaseTenant;
use Stancl\Tenancy\Contracts\TenantWithDatabase;
use Stancl\Tenancy\Database\Concerns\HasDatabase;
use Stancl\Tenancy\Database\Concerns\HasDomains;

class Tenant extends BaseTenant implements TenantWithDatabase
{
    use HasDatabase, HasDomains;


}
