### ISSUE TITLE
How to deal with unregistered subdomains

### ISSUE THREAD

**Issue by kcoet** [stancl/tenancy#1099]
First of all, thanks for the awesome package.

Is there a way to deal with non-existent subdomains? I've scoured the documentation but can't find it.

Here is an error message when I access a non-existent subdomain:

![image](https://user-images.githubusercontent.com/110478020/230787795-eaf62eef-bc65-4734-9c5c-58eb3a2d797d.png)

**Comment by stancl** [comment]
Hey, for support questions please use [our Discord](https://archte.ch/discord).
