### ISSUE TITLE
domain query every requst

### ISSUE THREAD

**Issue by hai-shift** [stancl/tenancy#1104]
### Bug description

hi
 
when i enter to my site domain 
every request i see in the query that:
```

select * from "tenants" where exists (select * from "domains" where "tenants"."id" = "domains"."tenant_id" and "domain" = 'myshop.shop.test') limit 1
47.56ms
/vendor/stancl/tenancy/src/Resolvers/DomainTenantResolver.php:40
appointment
select * from "domains" where "domains"."tenant_id" in (1)
```

and its take a lot of time
how i can performance that?

and if i put a  liviewire tag inside my page like this:
 <livewire:product.product-selector :variations="$product->variations"  />
               
when i see the qurey its call again to the domain query 
how i can to not load the domain query ?

### Steps to reproduce

top

### Expected behavior

top

### Laravel version

10

### stancl/tenancy version

3

**Comment by stancl** [comment]
https://tenancyforlaravel.com/docs/v3/cached-lookup/

Also please don't open bug tickets for things that aren't bugs (= things that don't behave as described).
