### ISSUE TITLE
Call to undefined method Stancl\Tenancy\Database\Models\Tenant::domains()

### ISSUE THREAD

**Issue by lotfimostafa** [stancl/tenancy#1113]
### Bug description

when i moved the InitializeTenancyByDomain middleware to the kernel file and at the end of the $middleware array, my app throws the following error:

![image](https://github.com/archtechx/tenancy/assets/12979443/ac053209-2ea6-4afb-998c-05da3d5847d2)

kernel file:
```
namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;
use Stancl\Tenancy\Middleware\InitializeTenancyByDomain;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array<int, class-string|string>
     */
    protected $middleware = [
        \App\Http\Middleware\EncryptCookies::class,
        \Illuminate\Session\Middleware\StartSession::class,
        // \App\Http\Middleware\TrustHosts::class,
        \App\Http\Middleware\TrustProxies::class,
        \Illuminate\Http\Middleware\HandleCors::class,
        \App\Http\Middleware\PreventRequestsDuringMaintenance::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        InitializeTenancyByDomain::class,

    ];
```

the Tenant model:

```
namespace App\Models\Tenant;

use Stancl\Tenancy\Database\Models\Tenant as BaseTenant;
use Stancl\Tenancy\Contracts\TenantWithDatabase;
use Stancl\Tenancy\Database\Concerns\HasDatabase;
use Stancl\Tenancy\Database\Concerns\HasDomains;
use Illuminate\Database\Eloquent\Factories\HasFactory;


class Tenant extends BaseTenant implements TenantWithDatabase
{
    use HasDatabase, HasDomains;
    use HasFactory;
...
```

tenancy config:

```
<?php

declare(strict_types=1);

use App\Models\Tenant\Tenant;
use Stancl\Tenancy\Database\Models\Domain;

return [
    'tenant_model' => Tenant::class,
...
```

### Steps to reproduce

put the InitializeTenancyByDomain middleware on the kernel file below the middleware list.

### Expected behavior

I'm treating the central domain as a tenant itself. my app has no central domain. I'm handling my central app through my first tenant (with the id of 1). 
i need to initial tenancy first thing in the app and for all my requests.

### Laravel version

10

### stancl/tenancy version

3.7.0

**Comment by lotfimostafa** [comment]
I've found another config file in the package which apparently overrides my tenancy config in the main project.

vendor\stancl\tenancy\assets\config.php

**Comment by stancl** [comment]
It doesn't override it. Those are the default values.

Issue is likely that you have cached your config and didn't clear the cache (`php artisan config:clear`), assuming:
1. Your model uses `HasDomains` (and properly imports that trait)
2. Your config specifies the tenant model as the one in your codebase

Also, for support questions please use our Discord, not the issue tracker.
