### ISSUE TITLE
Can i connect muti server DB ?

### ISSUE THREAD

**Issue by duongsieu** [stancl/tenancy#1122]
### Bug description

I can not connect database other host.
I plan to build the system on multiple host databases. For example central database would be one host, and 5 tenant databases to one host, but I only see configuring multiple databases in one host based on tenancy_db_name. Let me know how to do this.

### Steps to reproduce

nothing, I read a document on https://tenancyforlaravel.com/docs/v3/customizing-databases

### Expected behavior

I want to be able to configure the host property

### Laravel version

9.0

### stancl/tenancy version

3.4

**Comment by stancl** [comment]
Please don't submit support questions as bug reports. For support questions, use [our Discord](https://archte.ch/discord).
