### ISSUE TITLE
CORS issue with cached domains in a multi-tenant Laravel application

### ISSUE THREAD

**Issue by lucabecchetti** [stancl/tenancy#1124]
### Bug description

I'm using the Tenancy for Laravel package in my multi-tenant Laravel application, and I have encountered a CORS (Cross-Origin Resource Sharing) issue related to cached domains. My application has multiple domains, such as bar.tenant.test and foo.tenant.test. The problem arises when I log in to the foo domain after visiting the bar domain. Since the view is cached, the assets' URLs are still pointing to the bar domain, leading to CORS errors for the foo domain.

### Steps to reproduce

1. Visit the bar domain and log in.
2. Without logging out, visit the foo domain.

### Expected behavior

The assets' URLs should reflect the correct domain (foo) after visiting the foo domain, and there should be no CORS issues.

Actual behavior:
The assets' URLs in the cached view still point to the previous domain (bar), causing CORS errors when accessing the foo domain.

Additional information:
To generate asset paths in my application, I have overridden the assetPath method in the Laravel framework with the following code:

```
protected function assetPath($path, $secure = null)
{
    return global_asset($path, $secure);
}
```

### Laravel version

9.19

### stancl/tenancy version

3.7

**Comment by stancl** [comment]
Would need some more info on how to reproduce this.

That said, I don't really see how CORS would be related to the package since it doesn't interact with that. It's mostly a matter of webserver configuration.
