### ISSUE TITLE
How can I make the registration of a CustomeServiceProvider conditional on the tenant?

### ISSUE THREAD

**Issue by webactor724** [stancl/tenancy#1125]
How can I make the registration of a CustomeServiceProvider conditional on the tenant?

I want to have 2 packages, the second package will be booted if the tenant allows it to boot

But after all the efforts, I couldn't execute conditions like tenancy()->tenant in AppServiceProvider

The method below doesn't answer as if event
 TenancyBootstrapped is run before it is necessary to register a service provider

        Event::listen(TenancyBootstrapped::class, function (TenancyBootstrapped $event) {
             $this->app->register(shopServiceProvider::class);
        });

**Comment by stancl** [comment]
> TenancyBootstrapped is run before it is necessary to register a service provider

More likely that it's the other way around

**Comment by webactor724** [comment]
Yes . It run after it .
In fact, how to execute serviceProvider with event? Is it possible at all?

**Comment by stancl** [comment]
Depends on what the service provider does. What does `shopServiceProvider` do in your case?

**Comment by webactor724** [comment]
`shopServiceProvider` It is the second package .I want the ShopServiceProvider to be executed when the tenant has the shop attribute

**Comment by stancl** [comment]
Please answer what exactly the provider _does_.
