### ISSUE TITLE
url() method in notification class points to central app

### ISSUE THREAD

**Issue by marcuschristiansen** [stancl/tenancy#1127]
### Bug description

When a new user is created they will receive an email with their login details. Inside the `action()` method, as the 2nd parameter I use the `url('login')` method.

For eg. if the user is created on the tenant1.example.com domain the login button inside the email will redirect the user to the central domain at example.com/login instead of tenant1.example.com/login. 

### Steps to reproduce

Setup a Notification class and include the action() method, which will include the a button inside the email and use the url() helper inside it as the second parameter.  

### Expected behavior

If a user is created in the tenant1.example.com domain and the new user email is sent out, the action button should redirect the user to tenant1.example.com/login 

### Laravel version

8.83.27 

### stancl/tenancy version

3.6.1

**Comment by stancl** [comment]
You can use the `tenant_route()` method to generate tenant-specific URLs.

If you queue actions that send emails, the queue itself doesn't run on a tenant domain, it just uses APP_URL.
