### ISSUE TITLE
Synced resources (both central and tenant), on creation, contain identical primary keys, even when incrementing ids is enabled. (Diagnosis included)

### ISSUE THREAD

**Issue by ali-raza-saleem** [stancl/tenancy#1129]
### Bug description

I am using Resource syncing functionality. Resources (Models) have their incrementing ids enabled. Whenever I create CentralUser and attach tenants to it, all the newly created tenant Users share the same primary key. 

I did some exploration and found the issue to be inside \Stancl\Tenancy\Listeners\UpdateSyncedResource.php class

![Screenshot 2023-07-01 053519](https://github.com/archtechx/tenancy/assets/88083032/29f4e56f-0370-4569-ba3f-a8f70aaeba76)

`$localModel = $localModelClass::create($eventModel->getAttributes());`

`$eventModel->getAttributes() ` seems to be the cause here. $eventModel->getAttributes() returns all attributes including the primary key of $eventModel which in this case happens to be CentralResource.

Converse is also true; Creating Tenant creates CentralUser with same primary key as Tenant User

![Screenshot 2023-07-01 053207](https://github.com/archtechx/tenancy/assets/88083032/62a3b2c4-34fa-4d86-ba37-69c217d69898)

I think the author had uuids in mind when writing this functionality, but forgot to update it for incrementing primary keys. :-)

Its a very well written package with best design practices. Kudos to the author. 

### Steps to reproduce

1. Enable Resource Syncing between tenants (use example from the docs to setup)
https://tenancyforlaravel.com/docs/v3/synced-resources-between-tenants/

2. Create CentralUser

3. Users in tenants gets created but they share identical primary key as CentralUser.

### Expected behavior

Tenant Users should have autoincrement keys independent of CentralUser

### Laravel version

9.52.8

### stancl/tenancy version

3.7.0

**Comment by stancl** [comment]
This has been fixed in v4 but won't be changed in v3 since this has been the behavior for a long time — so we don't want to introduce breaking changes here even if they're technically bug fixes. The change affects resource syncing in a fundamental way, so it's better to hold that off until v4.

For now this is available in v4 early access.

**Comment by KenzoKai** [comment]
> For now this is available in v4 early access.

Where is v4 Early Access?

**Comment by stancl** [comment]
In the [`#announcements`](https://discord.com/channels/976506366502006874/976506996201230416/1047644771587469312) channel of our Discord (you need to [join](https://archte.ch/discord) first).
