### ISSUE TITLE
duplicate routes with Laravel 10 using breeze and sub domain not posting register to correct db

### ISSUE THREAD

**Issue by MattWiseParking** [stancl/tenancy#1130]
### Bug description

I am getting duplicate route names when using Auth breeze package.  all the routes from the sub domain seems to be posting to the landlord database and not the new tenant db which was created when creating a new tenant.

### Steps to reproduce

- install new laravel version 10 on local
- install breeze and run migrations etc...
- install this package and follow install instructions for multi tenancy using separate databases etc...
- setup tenancy as per docs for new tenancy and domain

### Expected behavior

I would expect when navigating to /register or /login url from any of the sub domains, any of the post/get should default to the new tenant database and not the landlord database

### Laravel version

10.14.1

### stancl/tenancy version

3.7

**Comment by MattWiseParking** [comment]
i would also expect not to see duplicate routes with duplicate route names.  for example, password.update is referenced twice for tenant.test/password and /password - same for all the auth routes. /register and tenant.test/register

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in the package, it seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks
