### ISSUE TITLE
Sql Server SyncedResource create with id

### ISSUE THREAD

**Issue by henry11996** [stancl/tenancy#1133]
### Bug description

Sql server not allow write id in database when `IDENTITY_INSERT` is off

https://github.com/archtechx/tenancy/blob/d9b7107900f938dc404810c59c092a1b8325366b/src/Listeners/UpdateSyncedResource.php#L63

### Steps to reproduce

1. Create SqlSrvDatabaseManager and add in `conifg('tenancy.database.managers.sqlsrv')`
2. Setup tenancy 
3. Setup [Synced resources between tenants](https://tenancyforlaravel.com/docs/v3/synced-resources-between-tenants)
4. Create a user from central user model

### Expected behavior

Create tenant user without error.

### Laravel version

10

### stancl/tenancy version

3.7.0

**Comment by KenzoKai** [comment]
In similar boat as well. I can't get SyncedResource to work either. Can create from Central, but updates do not propagate. Can not create or update from tenant. Following guide to the letter...

**Comment by stancl** [comment]
There are a few known bugs with resource syncing in v3 that we cannot fix in that version as it'd come with significant breaking changes. All that we know about have been fixed in v4.

@henry11996 is this specific to "Sql server when IDENTITY_INSERT is off" or does it happen with other database engines as well?

**Comment by henry11996** [comment]
No, as i known `IDENTITY_INSERT` setting only exist in Sql server.
All `IDENTITY` in sql server have this protection.
Maybe it can disable when saving ? see [url](https://learn.microsoft.com/en-us/sql/t-sql/statements/set-identity-insert-transact-sql?view=sql-server-ver16#remarks)
