### ISSUE TITLE
Tenant Model - undefined database() method

### ISSUE THREAD

**Issue by code-reflex** [stancl/tenancy#1134]
### Bug description

Tenant Model - undefined database() method.

Project created with laravel sail using laravel 10 & pgsql. Have followed the steps in Quick Start guide to add stancl/tenancy package & associated updates.  Tenant.php is copied from the documentation.

When trying to create a tenant with tinker, this error message pops up.
```
   BadMethodCallException  Call to undefined method Stancl\Tenancy\Database\Models\Tenant::database().
```

Have tried it with schema mode as well as in separate database modes - same message pops up.

### Steps to reproduce

```
sail@d481d47111fb:/var/www/html$ php artisan tinker
Psy Shell v0.11.19 (PHP 8.2.8 — cli) by Justin Hileman
> $tenant1 = App\Models\Tenant::create(['id' => 'foo']);

   BadMethodCallException  Call to undefined method Stancl\Tenancy\Database\Models\Tenant::database().
```

### Expected behavior

Error message mentioned above should not appear and the tenant database should get created

### Laravel version

v10.15.0

### stancl/tenancy version

3.7

**Comment by stancl** [comment]
![CleanShot 2023-07-22 at 6 59 38@2x](https://github.com/archtechx/tenancy/assets/33033094/39661b3e-a815-4448-946c-9073342b1b0a)

**Comment by stancl** [comment]
Also make sure your config isn't cached (`php artisan config:clear`) so that the package will use the model you provided in the config.
