### ISSUE TITLE
Ecosystem like Google

### ISSUE THREAD

**Issue by yashiroiori** [stancl/tenancy#1135]
How do to make en ecosystem like Google?? I mean, have multiple sites like sell hosting like digitalocean, an ERP, an CRM, system of payments like Stripe/MercadoPago/etc and have unique login

The goal it's:
mydomain.com
hosting.mydomain.com
erp.mydomain.com
crm.mydomain.com
payment.mydomain.com

How do the user login in anyone app and the login persist in all other systems?? I use cookie domain and works, sync user resources but it's to hard register the user in each system and the problem it's migrations, ok user are register un hosting app for example but how do to run all migrations on other all apps like erp/crm/payment on register??

It's correct make User login from central app with out register user in each app??
I think to resolve migrations in central app into folder tenant put all migrations to run all on register and each app connect to same user tenant, can be correct??

How it's the correct way to solve this problem??

Sorry for my bad english, regards!!

**Comment by stancl** [comment]
For support questions please use [our Discord](https://archte.ch/discord).
