### ISSUE TITLE
MFA for tenancy based users.

### ISSUE THREAD

**Issue by arvindjkhr** [stancl/tenancy#1136]
#### Description
I wanted to use some features of [Laravel Fortify](https://laravel.com/docs/10.x/fortify). But When I am using this package this is being used only for Main Site not for tenant sites. How can we use it for tenant users for MFA purposes.

#### Why this should be added
For security purposes of a user who is logging into tenant application.

**Comment by stancl** [comment]
Fortify is not supported in v3, it will be supported in v4.
