### ISSUE TITLE
Tenants uses Central DB

### ISSUE THREAD

**Issue by mohamedary** [stancl/tenancy#1137]
### Bug description

I just installed the package on a fresh Laravel application. But, when I try to dump the users in the tenant routes file. I get an error.

<img width="810" alt="image" src="https://github.com/archtechx/tenancy/assets/17085444/014e3b89-91ff-47d9-b449-d116da13e23a">

P.S: I am using Laravel Herd to setup the domain to the development environment.

Also, I am wondering why I run into the same error on the central domain. Shouldn't it be scoped to tenants subdomains?

### Steps to reproduce

Freshly install the package on a brand new Laravel project and follow the documentation steps on https://tenancyforlaravel.com/docs/v3/quickstart 

### Expected behavior

It should dump the users for each tenant.

### Laravel version

10.16.1

### stancl/tenancy version

3.7.0

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks
