### ISSUE TITLE
Livewire v3 image upload error

### ISSUE THREAD

**Issue by yaser2490** [stancl/tenancy#1138]
### Bug description

**Hi,**
I got an error when using filament panel and uploading a photo.

**Log:**
[2023-08-05 14:25:05] local.ERROR: Illegal offset type in isset or empty {"exception":"[object] (TypeError(code: 0): Illegal offset type in isset or empty at C:\\Work\\projects\\laravel\\Filament\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php:1435)

When I remove the **'universal', InitializeTenancyByDomain::class** middleware, the program works correctly

**UniversalRoutes::class feature is active too.**

**Livewire config:**
![Screenshot 2023-08-05 143142](https://github.com/archtechx/tenancy/assets/70744366/38907312-fb76-4ddb-801c-99d547338d6d)

### Steps to reproduce

1- Start new laravel project
2- Install Filament v3
3- Use FileUpload field for uploading photo (with livewire v3)

### Expected behavior

Upload File.

### Laravel version

10.17

### stancl/tenancy version

3.7

**Comment by stancl** [comment]
Please use the appropriate channels for support questions and don't open bug reports for 3rd party integrations.

**Comment by aeq-dev** [comment]
Hi @yaser2490 
Did you find a solution for that ?
