### ISSUE TITLE
Weird bug using array action in route definition

### ISSUE THREAD

**Issue by undjike** [stancl/tenancy#1139]
### Bug description

I'm facing a weird bug when using array action in route definition.

Trying to access this route always redirects me back.

```php
Route::get('/user/profile', [UserProfileController::class, 'show'])->name('profile.show');
```

I can't understand why. But when I use this... It works as expected.

```php
Route::view('/user/profile', 'page.profile')->name('profile.show');
```

I'm using Jetstream and Livewire. Both are working well, but as I cannot update vendor routes within Jetstream, I tried to reference the same view the 2nd way and I figured out the problem is coming from the route definition method.

Any idea?

### Steps to reproduce

- Install a fresh Laravel application using Jetstream and Livewire.

```batch
laravel new <project_name> --jet
```

- Then install and configure Tenancy package (multiple databases with subdomain identification),
- Create a tenant and the related domain using Tinker,
- Access the new tenant's domain,
- Create a user and login,
- From the `dashboard` page, try to access `user profile` page (both shipped with Jetstream).

You will be redirected back to `dashboard`.

### Expected behavior

Both route definition method are supposed to work.

### Laravel version

10.10

### stancl/tenancy version

3.7

**Comment by stancl** [comment]
Jetstream isn't supported in version 3. It is supported in version 4 (which is currently in early access, see `#announcements` [on our Discord](https://archte.ch/discord)).

Also, please only open bug reports for actual issues with the package itself (not integrations with third party packages besides the ones that are explicitly listed as supported in our docs).

Support questions should be asked on our Discord.

**Comment by undjike** [comment]
I'm doubting whether this bug is caused by Jetstream. As I said, it works well when not using array action in route definition.

I'm going to try with a fresh Laravel project to ensure.

**Comment by stancl** [comment]
It's not a bug in either package, it's specifically that Tenancy v3 cannot be integrated with Jetstream.
