### ISSUE TITLE
Authentication with jetstream

### ISSUE THREAD

**Issue by salacsoft** [stancl/tenancy#1140]
### Bug description

I have multiple database and integrate laravel jetstream.
I have issue on login because it only checks the user from the main database or central database, instead from the tenant database. my url is like tenant.mydmain.com/login when I used user from main database it can successfully login. however when i used user from tenant users table. it cant get through. 

### Steps to reproduce

Login to app with the tenant domain,
used the users from tenants users table
it will return invalid credentials
but when you used users from central database, it will pass through

### Expected behavior

login should identify the tenants database

### Laravel version

10

### stancl/tenancy version

3

**Comment by stancl** [comment]
As mentioned in many other issues, Jetstream is not supported in v3. It is supported in v4 which is now in early access. You can join our Discord for details and updates about v4.
