### ISSUE TITLE
Laravel-Multitenancy installation error

### ISSUE THREAD

**Issue by LEDUC21** [stancl/tenancy#1142]
### Bug description

Installing the library causes an error 
<img width="582" alt="Screenshot_4" src="https://github.com/archtechx/tenancy/assets/39991088/8e149a31-ca90-4404-84d9-37d60fbad73d">

### Steps to reproduce

<img width="582" alt="Screenshot_4" src="https://github.com/archtechx/tenancy/assets/39991088/7763dfa9-143d-4156-ae78-df0d450eab90">

### Expected behavior

<img width="582" alt="Screenshot_4" src="https://github.com/archtechx/tenancy/assets/39991088/e2bfea0a-9a28-4fa2-b826-d64fff738d59">

### Laravel version

10

### stancl/tenancy version

3.6

**Comment by stancl** [comment]
Just read the first line of the output.
<img width="1173" alt="CleanShot 2023-08-26 at 5 42 45@2x" src="https://github.com/archtechx/tenancy/assets/33033094/d25ad291-2d35-46fc-b03e-6a5be8d5d855">

**Comment by LEDUC21** [comment]
I'm on laravel 10 and php 8 is supported, locally php 8 is installed too! How to solve this problem please?
<img width="519" alt="Screenshot_5" src="https://github.com/archtechx/tenancy/assets/39991088/39b42913-8318-459b-97f2-a55addd88ba2">
<img width="582" alt="Screenshot_4" src="https://github.com/archtechx/tenancy/assets/39991088/c9552ef4-4046-4b6e-bffd-d0f49611e3f4">
