### ISSUE TITLE
Tenant Domain Redirect to Central domain for Unauthenticated users

### ISSUE THREAD

**Issue by MujeebAnwar** [stancl/tenancy#1144]
### Bug description

Tenant Domain always redirects to Central Domain for Unauthenticated Users.  When I hit my tenant 
`http://testing.k12asset.test` it needs to redirect me to `http://testing.k12asset.test/login` but it redirects me to my central domain `http://k12asset.test/login` 
I used custom Authenticate middleware for `auth`. This middleware extends from Laravel default authenticate middleware(`Illuminate\Auth\Middleware\Authenticate`). I just override redirectTo method 
<img width="750" alt="Screenshot 2023-09-08 at 3 13 36 PM" src="https://github.com/archtechx/tenancy/assets/60395570/2ec67bb5-8356-4d59-ad33-e0575713ae9c">

### Steps to reproduce

1. Go to the central domain `http://testing.k12asset.test`

### Expected behavior

 it's need to redirect me to `http://testing.k12asset.test/login` instead of `http://k12asset.test/login`

### Laravel version

8.46

### stancl/tenancy version

3.6

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't look like a bug in package, it seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks

**Comment by Delvin-MCS** [comment]
I fix the issue with edit the bootstrap/app.php
i am using laravel 12

![Image](https://github.com/user-attachments/assets/a3e8f9e9-ca2b-4545-91ba-c735c85d5c35)
