### ISSUE TITLE
MySql new Column not getting updated while creating tenant and only json data getting updated.

### ISSUE THREAD

**Issue by akhiljaiswar-tg** [stancl/tenancy#1145]
### Bug description

  When I am trying to create tenant and have user_id as column and its already there in migration as well as fillable in model still the user_id value is not getting updated in mysql column and its only getting updated in data column(json datatype).

### Steps to reproduce

First way tried after migration od user_id as additional row.
`     $tenant = Tenant::create([
            'id' => 'tenant6474',
            'user_id' => 3,
        ]);
`
Second Way tried to update
        `$tenant->user_id = 3;
        $tenant->save();
        `
Third way tried to update
$tenant->update(['user_id' => 3]);
Still same

Only the way it worked
Tenant::updateOrInsert([
            'id' => 'akhil',
        ],
            [
                'user_id' => 2,
            ]);
        

### Expected behavior

While using above methods for create and update the data(user_id) should get updated in mysql column name(user_id) other than in data (json) column

### Laravel version

10.21

### stancl/tenancy version

3.7.2

**Comment by stancl** [comment]
https://tenancyforlaravel.com/docs/v3/tenants/#custom-columns
