### ISSUE TITLE
No arguments expected for "tenants:run" command, got "send:reminder

### ISSUE THREAD

**Issue by dekts** [stancl/tenancy#1146]
### Bug description

I tried below command to run my custom command for all tenants but it throw me error.

`php artisan tenants:run send:reminder`

**No arguments expected for "tenants:run" command, got "send:reminder**

My Command File Sample:

```
namespace App\Console\Commands;

use Illuminate\Console\Command;

class SendReminderEmail extends Command
{
    /**
     * The name of the console command.
     *
     * @var string
     */
    protected $name = 'send_reminder';

    /**
     * The signature of the console command.
     *
     * @var string
     */
    protected $signature = 'tenants:run send:reminder';
    
    ......
    ......
    ......
}
```

### Steps to reproduce

`php artisan tenants:run send:reminder`

Execute above command in the terminal in your multi tenant project directory.

### Expected behavior

```
dekts@dekts my-project % php artisan tenants:run send:reminder
Tenant: tenant1
Tenant: tenant2
Tenant: tenant3
```

### Laravel version

10

### stancl/tenancy version

3.6

I appreciate the wonderful package; I need help with this. Everything else functions flawlessly.

**Comment by tmbenhura** [comment]
"tenants:run" should not be part of the signature.

it should be just:
` protected $signature = 'send:reminder';`

**Comment by dekts** [comment]
@tmbenhura still same response

<img width="770" alt="Screenshot 2023-09-18 at 4 50 18 PM" src="https://github.com/archtechx/tenancy/assets/31060232/4e9d7d9e-0a2f-4800-9173-cf1e820d9770">

<img width="702" alt="Screenshot 2023-09-18 at 4 47 24 PM" src="https://github.com/archtechx/tenancy/assets/31060232/c29bab6b-f1b1-468e-8edf-b6eea647b551">

**Comment by stancl** [comment]
Please use the right channels for support questions, such as [our Discord](https://archte.ch/discord).

**Comment by dekts** [comment]
@tmbenhura @stancl I corrected that by adding the names of the tasks and eliminating the tenants:run from the signature of all of my custom commands. The problem is that all custom commands should have an identical signature, even those that do not use tenants:run (the tenants aware command).

Thanks for your support @tmbenhura 👍
