### ISSUE TITLE
Domain tenant routes not scoped from console

### ISSUE THREAD

**Issue by tmbenhura** [stancl/tenancy#1147]
### Bug description

When using tenant-aware commands, routes generated are invalid as they are missing the domain component.

As a consequence of this, any generated notifications will also have invalid URLs and links.

A possible cause is that the tenant routes are loaded before identifying a tenant. The following iteration through TenantAwareCommand::getTenants() does not reload the routes and applies the domainless tenants across all tenants.

### Steps to reproduce

`
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Stancl\Tenancy\Concerns\HasATenantsOption;
use Stancl\Tenancy\Concerns\TenantAwareCommand;

class TestTenantCommand extends Command
{
    use TenantAwareCommand;
    use HasATenantsOption;

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'test-tenant-command';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Test tenant command';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
		dd(route('insert-tenant-route-here'));

        return 0;
    }
}
`

Run the command:
`php artisan test-tenant-command`

### Expected behavior

The expected output is:
`https://tenant.central-domain.com`

Instead, the output will be:
`https://central-domain.com`

### Laravel version

10.23.1

### stancl/tenancy version

3.7.2

**Comment by stancl** [comment]
This isn't something the package can solve directly. Tenants can have multiple domains, therefore the package cannot make assumptions about what the "correct" URL is.

That said, in v4 we have fixed this with a custom bootstrapper that lets you specify how the root URL should be configured.

**Comment by tmbenhura** [comment]
> This isn't something the package can solve directly. Tenants can have multiple domains, therefore the package cannot make assumptions about what the "correct" URL is.
> 
> That said, in v4 we have fixed this with a custom bootstrapper that lets you specify how the root URL should be configured.

Can't the tenant->initiatlise->run call reload the routes when run from the console?

**Comment by stancl** [comment]
> Tenants can have multiple domains, therefore the package cannot make assumptions about what the "correct" URL is.

**Comment by tmbenhura** [comment]
> > Tenants can have multiple domains, therefore the package cannot make assumptions about what the "correct" URL is.

I understand, but if a tenant has 1 domain isn't it better to use that, than to render invalid routes?

**Comment by stancl** [comment]
We do aim to have good defaults, but rather than having magical behavior that stops working once you add another domain to a tenant (can easily be a production-only thing), we want to make this something deliberately configured.
