### ISSUE TITLE
Single Sign On for SAML, OpenID or OAuth2 

### ISSUE THREAD

**Issue by arvindjkhr** [stancl/tenancy#1149]
#### Description
Hello Team,

First of all, Thanks for creating such a beautiful and clean plugin for tenancy where I can convert my application to a multi-tenant SaaS in less than 12 hours of efforts.
Do we have any plans to add support for SAML, OpenID or OAuth2 authentication support for tenants?

#### Why this should be added

- Flexibility to adopt a SaaS application faster.
- Faster user provisioning to a SaaS application.
- Better user management for an organization. 
- Easy Access control
- And many more in terms of security.

**Comment by 27pchrisl** [comment]
@arvindjkhr Does https://socialiteproviders.com/Saml2/ work for your use case? (I'm the maintainer of this provider, and I've used it with stancl/tenancy as well)

**Comment by arvindjkhr** [comment]
@27pchrisl Yes it can. do we have any related documentation how we can integrate for tenant websites?

**Comment by 27pchrisl** [comment]
I don't think there is any specific documentation, buf if you're using domain-based tenancy, and you intercept and change the `services.saml2` config space early in the request you can fill it with config specific to the tenant (like the IdP).

**Comment by arvindjkhr** [comment]
Ok Let me try and will keep you posted for the documentation if I could do it at my own.

**Comment by stancl** [comment]
No plans for auth integrations outside of Laravel's native auth system. But if there are any Laravel packages that integrate well I'm happy to accept integration guides for the docs.
