### ISSUE TITLE
Cannot access CSS and JS from another plugins

### ISSUE THREAD

**Issue by rpringadi** [stancl/tenancy#1152]
### Bug description

I'm using `tenancy for laravel` and `laravel-livewire-tables`.

In one of my pages, the system tries to load these files and ended up with 404 - NOT FOUND.

```
http://test_domain_one.localhost/rappasoft/laravel-livewire-tables/core.min.css
http://test_domain_one.localhost/rappasoft/laravel-livewire-tables/core.min.js
etc.
```

While if I copy the link and manually alter the URL by removing the tenant prefix, I can access the files just fine. Example:

```
http://localhost/rappasoft/laravel-livewire-tables/core.min.css
```

My guess is this is not a specific issue with `laravel-livewire-tables`, meaning it can happen with other plugins as well.

What should I do in this case to force my assets to use localhost ones?

### Steps to reproduce

* Install tenancy for laravel
* Install laravel-livewire-tables
* Create a tenant 
* Create a page with the simplest laravel-livewire-tables  example
* Open browser debug mode F12.
* Note that upon page load some assests such as CSS or JS are inaccessible (HTTP 404)

### Expected behavior

* Either provide an automatic to redirect.
* Or a way to override assets (CSS, JS) base url.

### Laravel version

10.25.2

### stancl/tenancy version

dev-master

**Comment by stancl** [comment]
1. Disable asset helper tenancy https://tenancyforlaravel.com/docs/v3/tenancy-bootstrappers/#assets
2. `dev-master` is not meant to be used

**Comment by rpringadi** [comment]
This bug was produced with asset_helper_tenancy  disabled.

```
// config/tenancy.php
'filesystem' => [
    'asset_helper_tenancy' => false,
],
 ```

<img width="1076" alt="Screenshot 2023-10-03 at 3 40 45 PM" src="https://github.com/archtechx/tenancy/assets/2053877/d54e15a4-fa27-4d77-bffb-7d860ce85e11">
