### ISSUE TITLE
Away to just have the tenant as the base url when doing assets.

### ISSUE THREAD

**Issue by Arametheus** [stancl/tenancy#1154]
So in v3 I'm running into a CORS issue.
in tenancy config I have  'asset_helper_tenancy' => false,

If I set the tenant_asset() => returns https://{tenant domain}/tenancy/assets/vendor/fontawesome-free/css/all.min.css
if I set it to asset() => then I get https://{Landlord domain}/vendor/fontawesome-free/css/all.min.css

but what I really want is https://{tenant domain}/vendor/fontawesome-free/css/all.min.css

This way i don't have to copy stuff to the tenant assets folder and I don't have to deal with CORS.

unless I'm totally missing something and you can point me in the right direction.  I think this would be a great feature for v4.

Thanks again for your awesome package.

**Comment by stancl** [comment]
You can just use a relative path: `/vendor/fontawesome-free/css/all.min.css`. No need to call `asset()`

**Comment by Arametheus** [comment]
Stancl do you know how to load vite build files from the tenant url?

I tried 
`<style>
        {!! Vite::content('resources/sass/app.scss') !!}
    </style>
    <script type="module">
        {!! Vite::content('resources/js/app.js') !!}
    </script>`

That gives me this url
https://{tenant domain}/@popperjs-f997b8e3.js

when I want this url
https://{tenant domain}/build/assets/@popperjs-f997b8e3.js

I'm sure I'm just missing something.

and thanks I was over thinking the other urls.

**Comment by stancl** [comment]
https://github.com/archtechx/tenancy/blob/85c7465aca2fb017545a5304dea0ee0006bee5f0/assets/config.php#L171
