### ISSUE TITLE
Make model:show work with tenant connection

### ISSUE THREAD

**Issue by hapidjus** [stancl/tenancy#1155]
#### Description
Currently `php artisan model:show` does not fully work with models using the tenant connection. I believe that since Laravel cant find the right table it cant infer the attributes from the table. 

I tried using `php artisan model:show Model --database tenant` but I assume that since the command is not tenant aware the DatabaseTenancyBootstrapper is not applied, since I get the Database connection [tenant] not configured.

**Comment by stancl** [comment]
Impossible to support this since there's no way to know which tenant to initialize tenancy for. We could make a custom command but I don't see much point in having a custom command for this.

**Comment by hapidjus** [comment]
I realize that out use case might not apply to everyone but since the tables are the same (in our app at least) it doesn't really matter what tenant we initialize. 

But I understand your hesitation to add a custom command, so we will probably just make out own command for that. Thanks.

**Comment by stancl** [comment]
Wrote that a bit imprecisely — it's less so about *which* tenant to use (in a custom command our approach would be to accept a tenant argument and default to `Tenant::first()`), but rather that it doesn't know what the `tenant` connection refers to. No tenancy initialization takes place in console commands until something triggers it. Calling a vendor command doesn't trigger it. Laravel has no way of knowing that tenancy should be initialized there.

You'd need a custom command that uses the traits mentioned in our docs, or similar to our commands that extend Laravel's commands.

**Comment by hapidjus** [comment]
Thanks for clarifying.
