### ISSUE TITLE
php artisan route:list not showing central application routes.

### ISSUE THREAD

**Issue by bipinks** [stancl/tenancy#1156]
### Bug description

When i run `php artisan route:list` it is expected to be shown the list of routes defined in the central application. But it is now throwing errors. I use nWidart Laravel modules architecture. So it is now trying to fetch all the routes from all the modules and follows with exception.

### Steps to reproduce

Try use modular approach and run `php artisan route:list` in console

### Expected behavior

It is expected to list all the routes defined for central application.

### Laravel version

10.28.0

### stancl/tenancy version

3.7.2

**Comment by stancl** [comment]
`route:list` works just fine in normal applications with Tenancy, so this is not a bug. If you're using multiple packages, it's up to you to integrate them properly. For support questions I recommend using our Discord, and if you're getting an exception, provide the actual exception + stack trace.
