### ISSUE TITLE
@routes directive not working

### ISSUE THREAD

**Issue by bishwajitcadhikary** [stancl/tenancy#1157]
### Bug description

@routes directive not working on the tenant but for the landlord, it's working fine.

### Steps to reproduce

@routes directive not working on the tenant but for the landlord, it's working fine.

### Expected behavior

@routes directive not working on the tenant but for the landlord, it's working fine.

### Laravel version

8.83.27

### stancl/tenancy version

3.4

**Comment by stancl** [comment]
`@routes` is not a Laravel feature.
