### ISSUE TITLE
Unable to Identify Tenant in TenantAssetsController 

### ISSUE THREAD

**Issue by browynlouis** [stancl/tenancy#1162]
### Bug description

I'm making use of the request data tenant initialization middleware **InitializeTenancyByRequestData** and it works when I use it in my API routes.

However, I notice a strange and unusual behavior that has kept me in one place for hours.
The **InitializeTenancyByRequestData** middleware doesn't seem to work in the **TenantAssetsController**, I have tried changing it on both the controller and the Service provider but it still doesn't work.
My API routes uses it as earlier stated and it works just fine.

### Steps to reproduce

- Issue noticed when using Single DB multi tenancy
- The current tenant is resolved successfully using the **InitializeTenancyByRequestData** middleware on the API routes. NB: Utilizes the "X-Tenant" header
- Files are uploaded in the context of the current tenant and it stores as stated in the docs (e.g tenant42/app/public...)
- Attempt to access the tenant's uploaded file using the `asset()` helper (still within the context of the tenant) throws an error saying tenant could not be resolved by request data payload, whereas the route just had the tenant initialized with the same middleware
- The `$tenantMiddleware` static property was also properly configured in the **TenancyServiceProvider**

### Expected behavior

The middleware on the **TenantAssetsController** is supposed to initialize the tenant and return the expected file.

### Laravel version

10.0.0

### stancl/tenancy version

3.7

**Comment by stancl** [comment]
Did you change static property?

https://github.com/archtechx/tenancy/blob/85c7465aca2fb017545a5304dea0ee0006bee5f0/src/Controllers/TenantAssetsController.php#L13

**Comment by browynlouis** [comment]
Thanks for the response @stancl 
Yes I did.. I changed it in the TenancyServiceProvider and also in the file itself... still doesn't work

**Comment by stancl** [comment]
Provide repro steps **without** any external dependencies i.e. spatie/media-library and explain what exactly doesn't work as expected.

**Comment by browynlouis** [comment]
Just made an update to repro section on the issue, please confirm @stancl

**Comment by browynlouis** [comment]
> Did you change static property?
> 
> 
The property changes successfully and I can confirm that because of the error thrown, which is specific to initializing the tenant based on request data.

**Comment by browynlouis** [comment]
I also just tried creating a new middleware to use for manual initialization.

The same behavior is observed..
- Routes are tenant authorized
- But the middleware fails to authorize in the **TenantAssetsController**

**Comment by stancl** [comment]
> Attempt to access the tenant's uploaded file using the asset() helper (still within the context of the tenant) throws an error saying tenant could not be resolved by request data payload

The package cannot add a header to frontend requests.

**Comment by stancl** [comment]
In v4 we'll have a solution for e.g. the query string approach, and some docs for overriding `fetch()` to include `X-Tenant`, but for inline `asset()` calls this cannot be done automatically especially on resources like images.

**Comment by browynlouis** [comment]
The header is being sent along with the frontend request

It works on the routes, but for some reason it doesn't work in the TenantAssetsController 

The `asset()` function is called in my CustomUrlPathGenerator for `spatie/medialibrary` just as it is in the docs.
