### ISSUE TITLE
Integration with Spatie/Laravel-Permission > v5.x don´t work

### ISSUE THREAD

**Issue by j3-solutions** [stancl/tenancy#1163]
### Bug description

Spatie/Laravel-Permission > v5.x don´t work

_Access to undeclared static property Spatie\Permission\PermissionRegistrar::$cacheKey_

The reason is te change of type in public property **$cacheKey** in _Spatie\Permission\PermissionRegistrar_ to no static

### Steps to reproduce

Install composer require laravel-permission

### Expected behavior

Fix method to integrate new versions of Laravel Permission

### Laravel version

8,9,10

### stancl/tenancy version

3.x

**Comment by stancl** [comment]
Possible solution: get the class instance using the service container and set the property, instead of setting a static property:
```php
// TenancyBootstrapped listener
$permissionRegistrar = app(\Spatie\Permission\PermissionRegistrar::class);
$permissionRegistrar->cacheKey = 'spatie.permission.cache.tenant.' . $event->tenancy->tenant->getTenantKey();
```
Or as a bootstrapper:
```php
class SpatiePermissionsBootstrapper implements TenancyBootstrapper
{
    public function __construct(
        protected PermissionRegistrar $registrar,
    ) {}

    public function bootstrap(Tenant $tenant): void
    {
        $this->registrar->cacheKey = 'spatie.permission.cache.tenant.' . $tenant->getTenantKey();
    }

    public function revert(): void
    {
        $this->registrar->cacheKey = 'spatie.permission.cache';
    }
}
```

**Comment by poseso** [comment]
It would be nice to add this to the docs, had the same problem following the docs and this fixed the problem, thanks

**Comment by stancl** [comment]
Posted it here first to get some feedback. If there are no issues with the approach above, I'll add it to the docs 👍🏻

**Comment by stancl** [comment]
https://github.com/stancl/tenancy-docs/commit/49941b625d0dc06fb37426f7c0a931b8e349b487
