### ISSUE TITLE
Filament PHP Admin Panel - Asset Path Challenge in Tenancy Applications

### ISSUE THREAD

**Issue by mbs047** [stancl/tenancy#1165]
**Dear All, community,**

I hope this message finds you well. I wanted to bring to your attention a challenge that I've encountered when using Filament PHP as an admin panel in both tenant and central applications. This issue pertains to the handling of assets, particularly Alpine.js and CSS, within the Filament package.

**The Issue:**
The primary obstacle arises from the dynamic nature of asset paths in tenancy applications. Specifically, when dealing with a tenancy application, the asset path can vary between being a subdomain and an external domain linked to the application. Currently, there are limited references addressing this challenge, prompting me to share my observations and seek community input for potential solutions.

**Objectives:**
**1. Identification of Dynamic Asset Path:**
   Determine whether the asset path is a subdomain or an external domain linked to the application.

**2. Exploration of Solutions:**
    Seek input and suggestions from the community on how to dynamically handle asset paths in tenancy applications.

**3. Documentation and Improvement:**
    Collaborate on documenting the challenge and potential solutions, with a focus on enhancing the Filament PHP experience for tenancy use cases.

**How You Can Contribute:**
Share your experiences or insights related to handling dynamic asset paths in tenancy applications using Filament PHP.
Provide suggestions or solutions that could enhance the handling of assets within Filament in diverse application environments.

**Next Steps:**
I invite all community members to engage in a collaborative discussion on this matter. Your contributions are invaluable in addressing this challenge and improving the overall Filament PHP experience for tenancy applications.

Thank you for your attention, and I look forward to our collective efforts in finding a robust solution.

Best regards,
Mohammed B.

**Comment by mbs047** [comment]
## Filament PHP Admin Panel - Asset Path Challenge in Tenancy Applications

Dear Developers, community,

I hope this message finds you well. Following our discussion on the challenges associated with asset paths in tenancy applications when utilizing Filament PHP as an admin panel, I'm pleased to present a comprehensive solution that I've implemented.

### The Issue:
The primary obstacle arises from the dynamic nature of asset paths in tenancy applications. Specifically, when dealing with a tenancy application, the asset path can vary between being a subdomain and an external domain linked to the application. Currently, there are limited references addressing this challenge, prompting me to share my observations and seek community input for potential solutions.

### The Solution:

In the `AppServiceProvider.php`, within the `boot` method, I've incorporated the following code to dynamically handle asset paths:

```php
 // Retrieve the domain and subdomain from the cache if available
list($subdomain, $domain) = Cache::remember('current_subdomain_domain', now()->addDay(), function () {
    // Parse the URL to extract the host (domain)
    $parsedUrl = parse_url(URL::current());

    // Get the host (domain) from the parsed URL
    $host = $parsedUrl['host'];

    // Split the host into subdomain and domain
    $segments = explode('.', $host, 2);
    $subdomain = isset($segments[0]) ? $segments[0] : null;
    $domain = isset($segments[1]) ? $segments[1] : null;

    return [$subdomain, $domain];
});
        
// Cache domain-specific assets path
$assetsPath = Cache::remember("assets_path_$subdomain.$domain", now()->addDay(), function () use ($subdomain, $domain) {
    return "https://$subdomain.$domain";
});

config(['filament.assets_path' => $assetsPath]);
\Log::info("Current Subdomain: $subdomain, Current Domain: $domain");

// Check if the current URL is not the same as app.central_domain
if ("$subdomain.$domain" !== config('app.central_url')) {
    \Log::info("Condition matched. Adding middleware.");

    // Only run the code if the current URL is not the same as central_domain and is a subdomain
    Livewire::setUpdateRoute(function ($handle) use ($subdomain, $domain) {
        return Route::post('/livewire/update', $handle)
            ->middleware([
                'web',
                InitializeTenancyByDomainOrSubdomain::class
            ]);
    });

    Artisan::call('route:clear');
}
```

Feel free to adapt and improve this solution based on your specific application requirements. I encourage the community to provide feedback, suggestions, or enhancements to further refine this approach.

Best regards,
Mohammed B,

**Comment by sheenazien8** [comment]
Hey @devhereco, I'm looking for how to implement filament using this tenancy, but I found nothing,

I've got the weird error that the table from the tenant database is not found because the database is still using the central database


I already implemented the `InitializeTenancyByDomain::class` in `Livewire::setUpdateRoute` method, and then I already initialized the tenant using the subdomain, but I still get that error

```PHP
        $panel = $panel
            ->id('tenant')
            ->colors([
                'primary' => Color::Amber,
            ])
            ->path('/member')
            ->login()
            ->discoverResources(in: app_path('Filament/Tenant/Resources'), for: 'App\\Filament\\Tenant\\Resources')
            ->discoverPages(in: app_path('Filament/Tenant/Pages'), for: 'App\\Filament\\Tenant\\Pages')
            ->pages([
                Pages\Dashboard::class,
            ])
            ->discoverWidgets(in: app_path('Filament/Tenant/Widgets'), for: 'App\\Filament\\Tenant\\Widgets')
            ->widgets([
                Widgets\AccountWidget::class,
                Widgets\FilamentInfoWidget::class,
            ])
            ->middleware([
                EncryptCookies::class,
                AddQueuedCookiesToResponse::class,
                StartSession::class,
                AuthenticateSession::class,
                ShareErrorsFromSession::class,
                VerifyCsrfToken::class,
                SubstituteBindings::class,
                DisableBladeIconComponents::class,
                DispatchServingFilamentEvent::class,
            ])
            ->authMiddleware([
                Authenticate::class,
            ]);

        $url = request()->getHost();
        $domain = explode('.', $url);
        if (count($domain) > 2) {
            tenancy()->initialize($domain[0]);
            $tenant = tenancy()->tenant;
            $subdomain = $tenant?->domains?->first()?->domain;
            $panel
                ->domain($subdomain);
        }

        return $panel;

```

I'm pleased if you can help solve my issue Thanks;

**Comment by plompd** [comment]
@sheenazien8 Did you managed to get Tenancy for Laravel working with Filament?

**Comment by sheenazien8** [comment]
> @sheenazien8  Did you managed to get Tenancy for Laravel working with Filament?

@plompd Ya, I did that, you can check it out on my [project](https://github.com/lakasir/lakasir/blob/master/app/Providers/Filament/TenantPanelProvider.php)

**Comment by mrmmg** [comment]
> > [@sheenazien8](https://github.com/sheenazien8)  Did you managed to get Tenancy for Laravel working with Filament?
> 
> [@plompd](https://github.com/plompd) Ya, I did that, you can check it out on my [project](https://github.com/lakasir/lakasir/blob/master/app/Providers/Filament/TenantPanelProvider.php)

This approach worked for me.
Laravel 11, Filament 3, Tenancy Package 3 tested

A special thanks to @sheenazien8 ❤
