### ISSUE TITLE
Issue related synced resources between tenants via TenantPivot and attach method

### ISSUE THREAD

**Issue by illambo** [stancl/tenancy#1167]
### Bug description

Hi, 
it seems synced resources between tenants (via TenantPivot) works only if you attach model to user but not from tenant.

```php
// this work
$user->tenants()->attach($tenant);

// this not work
$tenant->users()->attach($user);
```

I think is related to `$pivot->pivotParent`, when assume Tenant case 
https://github.com/archtechx/tenancy/blob/85c7465aca2fb017545a5304dea0ee0006bee5f0/src/Database/Models/TenantPivot.php#L17

I'm going to customize pivot model in order to fix this behavior.

### Steps to reproduce

See [docs](https://tenancyforlaravel.com/docs/v3/synced-resources-between-tenants) and try reverse relationship management 

### Expected behavior

I expect the synchronization to work even when handling the reverse relationship.

### Laravel version

10.31.0

### stancl/tenancy version

3.7.2

**Comment by stancl** [comment]
Yeah, this is a known bug. It's solvable in some cases but not others due to Laravel's limitations. We're working on an overhaul of resource syncing in v4 right now.

**Comment by illambo** [comment]
Ok, but why close the issue ? I think it's better to be there for the community.
Do you have any idea where I can find the list of know bugs?
Thanks

**Comment by stancl** [comment]
Closed because it's tracked in the v4 task list. It's still searchable including this convo.

Main broken things in v3 that can't be fixed without breaking changes are:
- some things with resource syncing
- creating tenant DBs on remote servers
