### ISSUE TITLE
Syncable - SyncedResourceSaved event is triggered even if there are no changes compared synced attributes

### ISSUE THREAD

**Issue by illambo** [stancl/tenancy#1168]
### Bug description

https://github.com/archtechx/tenancy/blob/85c7465aca2fb017545a5304dea0ee0006bee5f0/src/Database/Concerns/ResourceSyncing.php#L17

It seems to me that it doesn't check what changes (respect fields in sync), I would suggest a solution like this:

```php
static::saved(function (Syncable $model) {
    /** @var \Stancl\Tenancy\Database\Concerns\ResourceSyncing&Model $model */
    if ($model->wasRecentlyCreated || $model->wasChanged($model->getSyncedAttributeNames())) {
        $model->triggerSyncEvent();
    }
});
```

I can't understand if there is any other reason why it currently works this way, if so I ask you if you can give me some info on this.

Thanks

### Steps to reproduce

See [docs](https://tenancyforlaravel.com/docs/v3/synced-resources-between-tenants) and play with example.

### Expected behavior

I expect the synchronization is triggered only if related to the modification of syncable data (or new creation cases).

### Laravel version

10.31.0

### stancl/tenancy version

3.7.2

**Comment by stancl** [comment]
Could you expand on this issue a bit? We're aware of some bugs in resource syncing and are addressing them in v4 now.

**Comment by illambo** [comment]
Yes. IMO at the moment I see one main issues: performance (consumption of resources / execution time, any jobs to be queued, ..). Perhaps a "sync updates"  event (only triggered in case of modification of the synced attributes) to listen for might be more profitable.
What do you think?

**Comment by emre-ayhan** [comment]
I have the same isso even when navigating between pages triggers the sync evet. Using with laravel 10 inertia

**Comment by stancl** [comment]
We have a fix for this in v4 now. Might backport the fix to v3, though we don't want to make many changes to resource syncing in v3. v4 has a major rewrite of the logic since there are some bugs in v3 that are hard to fix in a backwards-compatible way.

**Comment by stancl** [comment]
I'll close this now since as mentioned, we don't really want to change how resource syncing works in v3. With this issue being fixed in v4, and v4 having a general resource syncing rewrite to address some of the other bugs discovered in v3 resource syncing.
