### ISSUE TITLE
Misplacement of Laravel Livewire Tenancy File Uploads into Central Storage Instead of Tenant-Specific Storage

### ISSUE THREAD

**Issue by jehoshaphatbc** [stancl/tenancy#1170]
### Bug description

During the file upload process in directory folder livewire-tmp, files intended for temporary or tenant-specific storage seem to be directed incorrectly towards the central storage or primary storage. This results in an issue where files, despite being uploaded for temporary storage, are not correctly placed within the designated tenant's storage. Consequently, when accessed, these files appear empty or inaccessible, possibly due to residing in the Livewire tmp storage for the wrong or unspecified tenant.

![Screenshot 2023-12-06 135434](https://github.com/archtechx/tenancy/assets/47764778/da34ace6-0221-404c-87dc-888f75253bf3)

### Steps to reproduce

- Initiate file upload process within Livewire TPM.
- Observe the direction of file storage during temporary storage phases.
- Attempt to access the temporarily stored files from the tenant's perspective.

### Expected behavior

- Files uploaded for temporary storage should be directed and accessible within the livewire-tmp storage specific to the corresponding tenant.- Files uploaded for temporary storage should be directed and accessible within the Livewire tmp storage specific to the corresponding tenant.
- Retrieval of files from temporary storage should yield the expected content without being empty or inaccessible.- Retrieval of files from temporary storage should yield the expected content without being empty or inaccessible.

![Screenshot 2023-12-06 135650](https://github.com/archtechx/tenancy/assets/47764778/ae3ef9b9-68c3-49ca-a284-e9e0591fde83)

### Laravel version

10.10

### stancl/tenancy version

3.7

**Comment by stancl** [comment]
What do you mean by "Livewire TPM (Tandem Property Management)"?

**Comment by jehoshaphatbc** [comment]
> * Initiate file upload process within Livewire TPM.

I mean the livewire-tmp folder directory. I used WithFileUploads livewire to upload images to the tenant, but the temporary images were stored in central storage, not tenant storage, so when I uploaded the image file I didn't know because it was stored in central storage.

**Comment by AdlyAlimin** [comment]
@jehoshaphatbc has you find solution? im stuck at this for week to upload excel
