### ISSUE TITLE
Asset broken image

### ISSUE THREAD

**Issue by lucassmacedo** [stancl/tenancy#1171]
### Bug description

Issue with Accessing Uploaded Files using **FilesystemTenancyBootstrapper** and **InitializeTenancyByDomainOrSubdomain**

### Steps to reproduce

Hello,

I am currently using FilesystemTenancyBootstrapper with its default configuration in a Laravel environment. In my AppServiceController, I have set up the following configuration:

`        TenantAssetsController::$tenancyMiddleware = InitializeTenancyByDomainOrSubdomain::class;
`
While file uploads are functioning correctly, I encounter an issue when trying to retrieve the uploaded assets. Specifically, when using {{ tenant_asset($file) }} to get the image URL, the image appears broken in the browser.

The file in question does exist in the designated folder and can be opened normally when accessed directly. However, the problem arises when I try to access the file via the URL (e.g., /tenancy/assets/logo.jpg).

![image](https://github.com/archtechx/tenancy/assets/3357243/f6d2fae5-412d-460e-ad3e-e906540f665f)
 

### Expected behavior

Shows the image correctly

### Laravel version

10.33

### stancl/tenancy version

3.7

**Comment by feraar** [comment]
I am also facing this issues. In my case, I am using spate medialibrary and I am able to upload correctly - tenant paths are honoured. When generating the urls I have tried using asset() and tenancy_asset(), the latter having  asset_helper_tenancy set to false. In both cases, it seems the asset functions are not honouring the tenant specific url path.

**Comment by stancl** [comment]
This seems like more like a usage issue than a bug so I recommend asking on [our Discord](https://archte.ch).
