### ISSUE TITLE
Laravel Passport Message Unauthenticated

### ISSUE THREAD

**Issue by emad313** [stancl/tenancy#1172]
### Bug description

{
    "message": "Unauthenticated."
}

Token Successfully generate from tenancy or a subdomain. But When It pass from header, Response Unauthenticated

### Steps to reproduce

{
    "message": "Unauthenticated."
}

### Expected behavior

{
    "message": "Unauthenticated."
}

### Laravel version

10.10

### stancl/tenancy version

3.7

**Comment by stancl** [comment]
For support regarding integrations, use [our Discord](https://archte.ch/discord).

**Comment by emad313** [comment]
> For support regarding integrations, use [our Discord](https://archte.ch/discord).

I am asking on the discord, but no one has responded to me. and I am trying in a different way. This is working properly with Laravel 9, but for Laravel 10, it always shows as unauthenticated.

Hopefully, it will be checked by the stancl/tenancy team.
