### ISSUE TITLE
PathTenantResolver does not forget the tenant route parameter when resolving from cache

### ISSUE THREAD

**Issue by piotrjoniec** [stancl/tenancy#1174]
### Bug description

https://github.com/archtechx/tenancy/blob/0b248f937dd4799aa42ecdbd2fc73c05ddb943bb/src/Resolvers/PathTenantResolver.php#L30C28-L30C28

### Steps to reproduce

Set PathTenantResolver::$shouldCache = true;

### Expected behavior

Expected: The tenant route parameter should always be forgotten.
Actual: The tenant route parameter is only forgotten on the initial request. Cached requests fail, because of a controller method parameter mismatch.

### Laravel version

10.37.3

### stancl/tenancy version

3.7.2

**Comment by stancl** [comment]
Hey, sorry for getting to this late.

Does adding this to the resolver fix the issue for you?
```php
public function resolved(Tenant $tenant, ...$args): void
{
    $route = $args[0];

    $route->forgetParameter(static::$tenantParameterName);
}
```

**Comment by piotrjoniec** [comment]
@stancl Yes, this fixes the problem.

**Comment by stancl** [comment]
Thanks a lot for reporting this and testing the fix!
