### ISSUE TITLE
Subdomain resolver middleware doesn't work with testing/localhost subdomain

### ISSUE THREAD

**Issue by rjp2525** [stancl/tenancy#1175]
### Bug description

When using the subdomain middleware to initialize tenancy, it considers "localhost" in "tenant.localhost" to be a domain extension, leading to tests failing for unable to resolve.

This was followed per the (sponsor) documentation for tests.

### Steps to reproduce

Following the documentation for [frictionless testing setup](https://sponsors.tenancyforlaravel.com/frictionless-testing-setup), and using the `InitializeTenancyBySubdomain` middleware on the group in `TenancyServiceProvider`

```php
protected function mapRoutes()
{
    Route::namespace(static::$controllerNamespace)
        ->name('tenant.')
        ->middleware([
            PreventAccessFromCentralDomains::class,
            InitializeTenancyBySubdomain::class,
            'web',
        ])
        ->group(base_path('routes/tenant.php'));
}
```

Running the test suite with "test.localhost" as the tenant subdomain results in:

![image](https://github.com/archtechx/tenancy/assets/1334865/e12817c6-4adf-4e82-bd5e-3ff15d9d4a40)

### Expected behavior

The subdomain resolver should probably account for localhost domains?

Not sure the implications of having that logic live directly in the subdomain middleware on production apps, but I got it to work by using a custom domain locally (test.<app-name>.local) and having my local DNS resolve it that way. This isn't super ideal for things like running tests on GitHub actions though

### Laravel version

10.37.0

### stancl/tenancy version

3.7.2

**Comment by stancl** [comment]
`*.local` and `*.localhost` resolve to loopback on most operating systems by default.
