### ISSUE TITLE
$tenant->delete() doesn't delete associated db

### ISSUE THREAD

**Issue by skills-up** [stancl/tenancy#1177]
### Bug description

I'm creating the user's on central app, and allowing them to create multiple tenants, as they please.
When deleting a user, I want to delete all associated tenants as well. Now, while the data is being deleted from central database, the corresponding tenant databases remain intact. I'm using 't_' as the tenant database prefix.

### Steps to reproduce

1. Change `database.prefix` to `t_` in `config/tenancy.php`
2. Add `owner_id` attribute to `tenants` migration, as foreign key referencing `users.id` with ON DELETE CASCADE
3. Setup user creation logic to create and link a tenant, when a new user is registered
4. Register a new user, and verify corresponding tenant, and tenancy db are created
5. Delete the user, and you'll notice that while the corresponding entries are deleted from tenants and domains tables in central db, the corresponding tenants db isn't deleted

### Expected behavior

Tenant db should have also been deleted when the tenant was deleted

### Laravel version

10.40.0

### stancl/tenancy version

8.3.1

**Comment by stancl** [comment]
SQL servers can't run PHP. If you use `ON DELETE CASCADE`, it will be the SQL server deleting the tenant record, not Laravel. Therefore none of Laravel's events will be fired.

I'd suggest using Laravel's events to delete the tenant record instead of `CASCADE`.

**Comment by skills-up** [comment]
The issue persists even without ON DELETE CASCADE.

I've called the following:
```
$user->tenants()->delete();
$user->delete();
```

The tenant gets deleted, along with associated domains. But the tenant DB remains intact.

**Comment by stancl** [comment]
Please take a look at how Eloquent works under the hood. This has nothing to do with tenancy.

`$user->tenants()->delete()` doesn't delete databases because it *also* doesn't trigger events. Laravel doesn't fetch each tenant to delete it individually here, it instead tells the SQL server to bulk delete tenants that match certain filters.

To delete a user's tenants with databases, you'd need to first fetch the model instances before calling `delete()` on them individually.

**Comment by skills-up** [comment]
Thanks @stancl
This solved the issue. Apologies for making assumptions regarding delete events getting triggered on collection.
