### ISSUE TITLE
tenants:run --tenants option not working

### ISSUE THREAD

**Issue by josiahgerald** [stancl/tenancy#1178]
### Bug description

I tried to run a command for a single tenant using the --tenants option and passing the tenant id but it still runs the command for all tenants.
I noticed this because there was a console info that should be displayed when its done with the command. But the message rather than being one, its four output equivalent to the number to tenant in the system.

### Steps to reproduce

I created a command and ran it using php artisan tenants:run --tenants=the tenant id and other options and argument, but it still runs all for all tenants.

### Expected behavior

Its should work as described in this doc https://tenancyforlaravel.com/docs/v3/console-commands for running tenant aware command. 

### Laravel version

9.52.15

### stancl/tenancy version

3

**Comment by stancl** [comment]
Not a bug in the package, either usage issue or related to the command you're running with `tenants:run`

https://github.com/archtechx/tenancy/commit/d268a06f5d8d98bbd0aa0c6fb7a4381c0bdc5c85
