### ISSUE TITLE
Laravel Passport Database Connection to Tenant Token Issue

### ISSUE THREAD

**Issue by soyjonathanespinosa** [stancl/tenancy#1179]
### Bug description

Laravel Passport Can´t access to protected route with Personal Tokens due give SQLSTATE[42S02]: Base table or view not found error, is connecting to Central Database and not to the tenant database.

I use passport v11.

### Steps to reproduce

-> Make and attempt to login with user information.
-> Then createToken.
-> Token Issued.
-> Then send Bearer token to route with auth:api, and give error: SQLSTATE[42S02]: Base table or view not found: 1146 Table *.oauth_access_tokens' doesn't exist (SQL: select * from `oauth_access_tokens` where `id` = 5a6c72a2574b081f857a3e53e3cda9d603346965d5bfacd38c9de852d80cef7191d25b01284501b3 limit 1)"

### Expected behavior

Access to protected route with the issued token, but, is not connecting to the tenant database.

### Laravel version

9.19

### stancl/tenancy version

3.5

**Comment by stancl** [comment]
For issues with integrations please use [our Discord](https://archte.ch/discord), or send corrections to the docs repo. This isn't a bug in tenancy.
