### ISSUE TITLE
Setting up username and password for db

### ISSUE THREAD

**Issue by ahmed-esmail-1** [stancl/tenancy#1184]
### Bug description

Dear reader,

I have set `Tenant::create([
    'tenancy_db_username' => 'foo',
    'tenancy_db_password' => 'bar',
]);` and after that I am getting an error 

>    Illuminate\Database\QueryException

  SQLSTATE[HY000] [1045] Access denied for user 
  
**I just want to create a name and password for each tenant db to monitor and control traffic** while keeping the connection and default db the same.

### Steps to reproduce

Follow this
https://tenancyforlaravel.com/docs/v3/customizing-databases/

### Expected behavior

Connection with db

### Laravel version

8.1

### stancl/tenancy version

v3

**Comment by stancl** [comment]
Please use [our Discord](https://archte.ch/discord) for support questions. This is not a bug in the package.

**Comment by ahmed-esmail-1** [comment]
There is a bug when I connect to the database that is in azure devops, while in local it is working, have you faced this before ?

 php artisan migrate


   INFO  Preparing database.

  Creating migration table ........................................ 225ms DONE

   INFO  Running migrations.

  2019_09_15_000010_create_tenants_table .......................... 363ms FAIL

   Illuminate\Database\QueryException

  SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key d
efined (Connection: mysql, SQL: alter table `tenants` add primary key (`id`))

  at vendor\laravel\framework\src\Illuminate\Database\Connection.php:822
    818▕                     $this->getName(), $query, $this->prepareBindings($b
indings), $e
    819▕                 );
    820▕             }
    821▕
  ➜ 822▕             throw new QueryException(
    823▕                 $this->getName(), $query, $this->prepareBindings($bindi
ngs), $e
    824▕             );
    825▕         }
    826▕     }

  1   vendor\laravel\framework\src\Illuminate\Database\Connection.php:580
      PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1068 Mu
ltiple primary key defined")

  2   vendor\laravel\framework\src\Illuminate\Database\Connection.php:580
      PDOStatement::execute()
