### ISSUE TITLE
Livewire tmp path

### ISSUE THREAD

**Issue by AdlyAlimin** [stancl/tenancy#1187]
### Bug description

when upload using livewire, file will be store in tmp folder (livewire_tmp) before store permanently into storage. when upload using tenant route, all upload file will store in central storage and not in tenant aware storage.

![image](https://github.com/archtechx/tenancy/assets/31163650/ad48e188-5cb7-44e8-9a32-cbf11ad2fe56)

error when to store permanently into storage:

fopen(C:\laragon\www\auditapptenant\storage/tenant_79aafb48-98ca-4f71-9b44-90b558a224f1/app\livewire-tmp/cIMWmTcd2HNBQumlrMf6mZYK9HYyl0-metaRGF0YSBJbXBvcnQueGxzeA==-.xlsx): Failed to open stream: No such file or directory

tenant identification using Stancl\Tenancy\Middleware\InitializeTenancyByDomainOrSubdomain[](url)

### Steps to reproduce

use Stancl\Tenancy\Middleware\InitializeTenancyByDomainOrSubdomain
upload using subdomain tenant route
store file permanently into storage

### Expected behavior

livewire_tmp folder exist in tenant aware storage

### Laravel version

10.43.0

### stancl/tenancy version

3.7.4

**Comment by stancl** [comment]
If you're on Livewire 3, try this in `TenancyServiceProvider::boot()`:
```
FilePreviewController::$middleware = ['web', InitializeTenancyByDomain::class]; // specify the right identification middleware
```
And set the `livewire.temporary_file_upload.middleware` config key to `['throttle:60,1', InitializeTenancyByDomain::class]` (again replacing your identification middleware there).

**Comment by AdlyAlimin** [comment]
Thanks you. This has fix the issue. Maybe this need to documented in V4.

**Comment by stancl** [comment]
Updated in docs
