### ISSUE TITLE
Tenancy()->initialize not working when Telescope installed

### ISSUE THREAD

**Issue by gabebritto** [stancl/tenancy#1189]
### Bug description

After we installed Telescope in project, the function tenancy()->initialize turns to not work.

When the function is used, the system throws an exception of undefined variable in Contract\Tenant

### Steps to reproduce

Install Telescope in a Laravel Project with Tenancy and try to run tenancy()->initialize in central context function.

### Expected behavior

Exception throwed and system stop working.

### Laravel version

10.5

### stancl/tenancy version

3.7.0

**Comment by stancl** [comment]
Please use [our Discord](https://archte.ch/discord) for support questions.
