### ISSUE TITLE
InitializeTenancyByPath does not respect route model binding

### ISSUE THREAD

**Issue by zagreusinoz** [stancl/tenancy#1190]
### Bug description

The InitializeTenancyByPath middleware does not respect the route model binding for the tenant model, it only uses the id field.

### Steps to reproduce

In the tenant routes:
`Route::middleware([InitializeTenancyByPath::class])->prefix('/{tenant}')->get('/test', function () {
        return 'This is your multi-tenant application. The details of the current tenant are ' . tenant('id') . ' - ' . tenant('slug');
    }); `

In the Tenant model:
`public function getRouteKeyName(): string
    {
        return 'slug';
    }`

When using a slug for the tenant in the URL then the Tenant model is not found, it still looks for the id.

### Expected behavior

The middleware should respect the route model binding native behaviour so that this can be customised as required using the resolvers that our solution requires.

https://laravel.com/docs/10.x/routing#route-model-binding 

### Laravel version

10.x

### stancl/tenancy version

3.7.4

**Comment by stancl** [comment]
Try overriding the `getTenantKeyName()` method instead

**Comment by zagreusinoz** [comment]
Thanks @stancl that works. Can this be changed to a suggestion for the next version?

**Comment by stancl** [comment]
I can see that it might seem like a bug/inconsistency here, but it's not. The package interacts with the models exclusively using the tenant keys. The identification is *not* done using route model binding, it's done using custom middleware that uses the tenant key.

Won't be changed in the next major version since that'd be more confusing and inconsistent than the current approach, even if it isn't perfectly intuitive.

**Comment by vanderb** [comment]
As quick side note.
To use properties from tenant's data-field just declare it arrow-based:
````php
    public function getTenantKeyName(): string
    {
        return 'data->FIELD';
    }
````

**Comment by stancl** [comment]
Regarding what I wrote in the previous comment, I managed to implement that in v4 (also related to https://github.com/archtechx/tenancy/issues/1198).

Now the resolver can be configured to use a different column than the tenant key and this syntax:
```php
Route::get('/{tenant:slug}/foo', ...);
```
is supported.
