### ISSUE TITLE
laravel default locale not working on tenant domains.

### ISSUE THREAD

**Issue by Muazzamkhan95** [stancl/tenancy#1191]
### Bug description

i am working on Laravel app and setup languages on main domain and assigned central database connection so translations got fetched from the central database. switching between locale is working fine on main domain but somehow tenancy deleting locale session on redirects.
any suggestions on that?

### Steps to reproduce

languages on main domain and assigned central database connection so translations got fetched from the central database.

### Expected behavior

languages on main domain and assigned central database connection so translations got fetched from the central database.

### Laravel version

8.1.12

### stancl/tenancy version

3.7

**Comment by stancl** [comment]
Please use [our Discord](https://archte.ch/discord) for support questions.
