### ISSUE TITLE
Single-database tenancy: make table index

### ISSUE THREAD

**Issue by hai-shift** [stancl/tenancy#1193]
im using Single-database tenancy

and i want to make a index to my table like this
$table->index(['tenant_id', 'is_active']);

in my service table 
 but when i look at the query i get this:

this is my query:
return Service::query()
        ->where('is_active',true)
        ->get()

`select * from "booking_services" where "is_active" = 1 and "services"."tenant_id" = 1 and "booking_services"."deleted_at" is null`

we can see the first the query do "is_active" = 1  and after that "booking_services"."tenant_id" = 1

i make a index first the tenant_id and after that the is_active
howi can fix the query First of all make the tenant_id first and after that the is_active

i can do like this:
`->withoutTenancy()
->where('tenant_id',$this->tenant_id)->where('is_active',true)->get()`

but i didnt want to make that every query

how can fix it

thanks

**Comment by reneroth** [comment]
It does not matter. Your SQL database will use the index no matter in which order the WHERE statements are.

You can check this yourself by taking your SQL query and prepending it with `EXPLAIN`, e.g.:

```sql
EXPLAIN SELECT * FROM booking_services WHERE is_active = 1 AND tenant_id = 1 AND deleted_at IS NULL;
EXPLAIN SELECT * FROM booking_services WHERE tenant_id = 1 AND is_active = 1 AND deleted_at IS NULL;
```

In both cases, the response column `key` should return something like `booking_services_tenant_id_is_active_index`, indicating your index is being used.

If this still does not work, it is something else about your setup. I notice in your code it says `"services"."tenant_id"` – that's a different table than `booking_services` – was that a typo, or are you scoping to a relationship/join here?

**Comment by stancl** [comment]
I think the WHERE clause order can sometimes matter, but it's possible that this is only the case with composite indices? It'd make sense that when there are multiple WHERE clauses on the same "level", the DB engine would reorder them to make use of any defined indices.

**Comment by reneroth** [comment]
SQL will reorder the WHERE clauses to make use of the most efficient indexes - even (and especially) for composite indexes :)On 11. May 2024, at 15:33, Samuel Štancl ***@***.***> wrote:﻿
I think the WHERE clause order can sometimes matter, but it's possible that this is only the case with composite indices? It'd make sense that when there are multiple WHERE clauses on the same "level", the DB engine would reorder them to make use of any defined indices.
