### ISSUE TITLE
After upgrading from Laravel 10x to Laravel 11x error in TenancyServiceProvider.php

### ISSUE THREAD

**Issue by 413D3Z** [stancl/tenancy#1195]
### Bug description

Illuminate\Routing\Router::group(): Argument #1 ($attributes) must be of type array, string given, called in D:\laragon\www\REDACTED\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 357

### Steps to reproduce

Used Laravel Shift Upgrade Laravel 10x to Laravel 11x

This part in the TenancyServiceProvider.php was causing the above error

```
  protected function mapRoutes()
    {
        if (file_exists(base_path('routes/tenant.php'))) {
            Route::group(base_path('routes/tenant.php'));
        }
    }
```
    
    
    So I changed it to 
    
```
        protected function mapRoutes()
    {
        if (file_exists(base_path('routes/tenant.php'))) {
            require base_path('routes/tenant.php');
        }
    }
```

An the error was resolved.

### Expected behavior

This is my first time using this process so forgive me, I guess my expected behavior was for it to not give me an error =)

### Laravel version

11.0.7

### stancl/tenancy version

3.8

**Comment by colinmackinlay** [comment]
I had a similar error and fixed it differently:
```
        if (file_exists(base_path('routes/tenant.php'))) {
            Route::namespace('')
                ->group(base_path('routes/tenant.php'));
        }
```
This code is directly copied from the current version of `TenantServiceProvider.php`.

The issue arises I think because that file is published on install and doesn't get updated when `tenancy` gets updates. I think it changed a while back.

**Comment by stancl** [comment]
Yeah, we use `Route::namespace(...)->group()` now
https://github.com/archtechx/tenancy/blob/72b1b48edde3c4cdc5899b565476778bac462955/assets/TenancyServiceProvider.stub.php#L121-L127
