### ISSUE TITLE
please show , how to use laravel in backend and next.js for forntend

### ISSUE THREAD

**Issue by webactor724** [stancl/tenancy#1196]
hello By separating the backend from the frontend, many advantages are added to the projects, but the project should be divided into two parts, the front part is based on node.js and the backend part is based on Laravel and the domain address of each tenant with the front end next.js be executed

If you have worked on this topic before, please post your experience.

**Comment by stancl** [comment]
When you were opening this issue, there was a link to the proper place for support questions.

**Comment by vahidalvandi** [comment]
Thank you I found it solution with set header method
