### ISSUE TITLE
Table migrated in central db instead of tenant db

### ISSUE THREAD

**Issue by filipprober** [stancl/tenancy#1197]
### Bug description

Hey,

I've got this problem:
<img width="1013" alt="image" src="https://github.com/archtechx/tenancy/assets/65421448/4e339e9a-c950-4ccf-a7e0-062f13ebf4eb">

I have my create_personal_access_tokens_table inside of my tenant folder.

But when I'm running the migration, it creates a tenant table inside of my central db:
<img width="823" alt="image" src="https://github.com/archtechx/tenancy/assets/65421448/1b11ff72-cf74-4a33-8023-ce8af224f9f4">

Why is this?

### Steps to reproduce

The source code is available on GitHub and you can clone it:
`git clone https://github.com/filip-codes/laravel-tenancy`

-> `cd laravel-tenancy`
-> `composer install`

Setup your .env file and run `php artisan migrate`.

### Expected behavior

create_personal_access_tokens_table should be migrated within tenant db, not central db.

### Laravel version

10.10

### stancl/tenancy version

3.8

**Comment by stancl** [comment]
Odds are you haven't **moved** the migration there, you **copied** it, and a dependency is adding the migration to the central migration "stack" behind the scenes.

The migration comes from Sanctum. The migration is published using `$this->publishesMigrations()` in the Service Provider

https://github.com/laravel/sanctum/blob/d1de99bf8d31199aaf93881561622489ab91ba58/src/SanctumServiceProvider.php#L43

Maybe that method also registers the migrations implicitly, without just publishing them? https://github.com/laravel/framework/blob/6b2de05ce6a60ada38f1dfe1fa74706b652fc896/src/Illuminate/Support/ServiceProvider.php#L284

Maybe if you include a migration with the same name in `database/migrations`, but don't create any tables inside, it will run it without actually affecting your database (besides keeping track of the migration).

This isn't a bug in tenancy, so please use the [appropriate support channel](https://archte.ch/discord).

The command you're running is a Laravel command, and it's not **all** tenant migrations that are getting executed for the central database, only one of the three you have in `database/migrations/tenant`, so this isn't an issue on our end.

**Comment by filipprober** [comment]
Solved it by ignoring default Sanctum migrations.

Thank you.
