### ISSUE TITLE
Ability to use a custom column in PathTenantResolver instead of only id

### ISSUE THREAD

**Issue by tijanidevit** [stancl/tenancy#1198]
#### Description
A dev should be able to specify the column he wants to use for the PathTenantResolver.

#### Why this should be added
I am creating an API and I am using PathTenantResolver, but I want to be able to use slug of the Tenant as the column for resolving the tenant instead of id.

We can use `PathTenantResolver::resolvingColumn`

**Comment by stancl** [comment]
Implemented in v4, both using a configurable column and `Route::get('/{tenant:slug}/foo', ...)`.

**Comment by tijanidevit** [comment]
> Implemented in v4, both using a configurable column and `Route::get('/{tenant:slug}/foo', ...)`.

Is v4 available now?

**Comment by stancl** [comment]
https://github.com/archtechx/tenancy/issues/654#issuecomment-1411545903
