### ISSUE TITLE
Setting all parts of connection for a tenant goes wrong

### ISSUE THREAD

**Issue by psaulus** [stancl/tenancy#1200]
### Bug description

I would like to provide a separate database parameters for each tenant for future scalability. So, for example, _tenatA_ could have host, port, username etc. different from _tenatnB_.

I've put these parameters to the tenants table in central database in the _data_ column in this format:

```
{
  "tenancy_db_host": "tenants-db",
  "tenancy_db_name": "tenant_test2",
  "tenancy_db_port": 3306,
  "tenancy_db_username": "test2",
  "tenancy_db_password": "test2"
}
```

But still, even with all these parameters, the application shows me _TenantDatabaseDoesNotExistException_ exception, because it looks for the database into default = central database. I've debugged that, and I see that even without set _tenancy.template_tenant_connection_ config MySQLDatabaseManager and all connected abstracts operates on central set connection or could operate on the template if that would be set, but it doesn't take data from the _tenants_ table for a good row.

Connected references:
* vendor/stancl/tenancy/src/TenantDatabaseManagers/MySQLDatabaseManager.php:24
* vendor/stancl/tenancy/src/Bootstrappers/DatabaseTenancyBootstrapper.php:31

### Steps to reproduce

I've described them above I think so.

### Expected behavior

I would see that, it should, when the connection data are set in the _tenants_ table in the central connection, take these parameters and try to find the table by them like it is described in the documentation - [Documentation part](https://tenancyforlaravel.com/docs/v3/customizing-databases#specifyng-other-connection-details)

### Laravel version

11.0.8

### stancl/tenancy version

3.8.0

**Comment by stancl** [comment]
Are you using a pre-created database, or having tenancy create the database for you?

**Comment by psaulus** [comment]
I checked that CreateDatabase job from the package wasn't enough, so I've disabled it in the provider and replaced with my own, which creates a database. I've checked double time that database exists and all user and permissions are properly set.

**Comment by stancl** [comment]
There's a known bug in v3 where creating databases on another host (specified via either `tenancy_db_host` or `tenancy_db_connection`) doesn't know correctly and instead tries to create the database on the same database host as the central connection.

> But still, even with all these parameters, the application shows me TenantDatabaseDoesNotExistException exception, because it looks for the database into default = central database. I've debugged that, and I see that even without set tenancy.template_tenant_connection config MySQLDatabaseManager and all connected abstracts operates on central set connection or could operate on the template if that would be set

This sounds similar to that.

In v4 we've solved this by introducing a new connection -- `tenant_host_connection` -- used for connecting to the proper database server per the tenant config. This is a wontfix in v3 since it'd require some breaking changes, and with v4 being close to release we prefer to not make any breaking changes in v3.
