### ISSUE TITLE
how to configure tenancy for Laravel on Laravel 11 version

### ISSUE THREAD

**Issue by Mazharqwe** [stancl/tenancy#1201]
### Bug description

Any body please guide me how to add configure tenancyforlaravel on larvel 11

### Steps to reproduce

i have installed fresh laravel 11 version but in this version a lot things has changed 

### Expected behavior

in Laravel 11 app/providers is not same as Laravel 10 service provider section has changed

### Laravel version

11

### stancl/tenancy version

3

**Comment by joelstein** [comment]
See #1180.
