### ISSUE TITLE
Laravel 11 cannot access subdomain on multi-database setup

### ISSUE THREAD

**Issue by krekas** [stancl/tenancy#1202]
### Bug description

After setting up the multi database and registering a user I'm always redirected from subdomain to the domain.

Seems like it in the `TenancyServiceProvider` the `makeTenancyMiddlewareHighestPriority()` breaks it. Changing the namespace fixes it.

```diff
foreach (array_reverse($tenancyMiddleware) as $middleware) {
-     $this->app[\Illuminate\Contracts\Http\Kernel::class]->prependToMiddlewarePriority($middleware);
+    $this->app[\Illuminate\Foundation\Http\Kernel::class]->prependToMiddlewarePriority($middleware);
}
```

### Steps to reproduce

Fresh multi database setup

### Expected behavior

Access to the subdomain.

### Laravel version

11.1.0

### stancl/tenancy version

3.8.0

**Comment by stancl** [comment]
You likely followed some steps here wrong https://github.com/archtechx/tenancy/pull/1180. After properly setting up tenancy in L11, this logic for me works the exact same way it did in L10.
