### ISSUE TITLE
Issue with Laravel Nova Image not compatible with subdomain

### ISSUE THREAD

**Issue by ali-irawan** [stancl/tenancy#1203]
### Bug description

Using:
 - Laravel Tenancy
 - Laravel Nova Image Field

When render in Index page the URL shown as URL from central domain instead of tenant domain 

### Steps to reproduce

I am using SaaS Boilerplate, for multi-tenancy, with subdomain

use case
- tenant1
- tenant2

When using Nova Image Field (upload the image), using this code
```
            Image::make('Image', 'image_url')
                ->disableDownload()
                ->prunable()
                ->path('/stores')
                ->hideFromDetail(), 
```
with this expected to be stored in storage (assume filesystems using local)

- storage/tenant1/stores/file1.jpg

In the database stored as
stores/file1.jpg

### Expected behavior

When rendered in the Nova index page, the URL is shown as
```http://localhost/storage/stores/file1.jpg```

Expected as
```http://tenant1.localhost/storage/stores/file1.jpg```

### Laravel version

10.7

### stancl/tenancy version

3.7

**Comment by stancl** [comment]
Please use [our Discord](https://archte.ch/discord) for support questions. This repo is only for tracking bugs in tenancy itself, not integrations.
