### ISSUE TITLE
Reset Password for Tenant not working

### ISSUE THREAD

**Issue by ali-irawan** [stancl/tenancy#1204]
### Bug description

from the SaaS boiler plate, the tenant reset password not working.

### Steps to reproduce

After getting an email to Reset Password, click on the Reset Password sent to
```http://tenantname.localhost/reset-password/{token}?email=myemail@domain.com```

- the password_reset_token data stored in tenant database -> this OK
- the route end up with 404, no reset-password route for tenant

### Expected behavior

The reset password should available in Tenant routes

### Laravel version

10.7

### stancl/tenancy version

3.7

**Comment by stancl** [comment]
- For boilerplate bug reports please use the boilerplate repo.
- It has been discussed [before](https://github.com/tenancy-for-laravel/saas-boilerplate/issues/5), we'll be implementing a proper fix soon.
