### ISSUE TITLE
Preventing Timestamps from Being Auto-inserted into the data Column

### ISSUE THREAD

**Issue by masatokawasakii** [stancl/tenancy#1205]
Dear Stancl\Tenancy Maintainer

I am currently encountering a challenge with the tenants table, specifically regarding the data JSON column. I have observed that the created_at and updated_at timestamps are being automatically inserted into this column, which is not the desired behavior for my application.

I have reviewed the documentation but was unable to locate any instructions or guidelines on how to prevent these timestamps from being included in the data column. Could you kindly provide guidance or point me to the relevant section in the documentation that addresses this?

Any advice on how to customize the Tenant model to exclude these timestamps from the data column would be greatly appreciated.

Thank you for your time and assistance.

Best regards,

**Comment by stancl** [comment]
Any column that's set on the model and isn't included in `getCustomColumns()` will go into the data column.

To avoid this, either add the column to `getCustomColumns()` or stop it from being set, in this case likely via `$timestamps = false`.
