### ISSUE TITLE
Undefined constant RedisCluster::OPT_PREFIX

### ISSUE THREAD

**Issue by lucasromanojf** [stancl/tenancy#1207]
### Bug description

Hello,

We upgraded a project which uses tenancy (version 3.8.0) to Laravel 11, and also php to 8.3.

When deploying to Laravel Vapor, we received this error during deploy. We are using the php-8.3:al2-arm runtime.

Any ideas? We confirmed that the redis client being used is php redis and not predis.

Thanks! 

### Steps to reproduce

Deploy L11 project to Vapor with php-8.3:al2-arm runtime using redis as cache. 

### Expected behavior

Deploy should finish without errors

### Laravel version

11.2

### stancl/tenancy version

3.8.0

**Comment by stancl** [comment]
The Redis bootstrapper expects phpredis to be installed.

> We confirmed that the redis client being used is php redis and not predis.

Confirm that the *php extension* is installed.

Additionally notice that it's saying the property doesn't exist on `RedisCluster`. Might be related to your Redis setup.

**Comment by lucasromanojf** [comment]
I was able to fix it by creating my own RedisTenancyBootstrapper extending package's and changing all occurrences of

`$client::OPT_PREFIX`

To

`\Redis::OPT_PREFIX`

Maybe It is not the best solution but works for me for now.

Thanks!

**Comment by stancl** [comment]
Interesting, in the case of clusters it's possible the actual client instance is a `RedisCluster` instance, but it still supports setting opts defined on the `Redis` class. I'll look into this 👍🏻

**Comment by lucasromanojf** [comment]
Yeah I am not sure if I did the right thing here, but at least the error
stopped happening. I'm not sure if it creates side
effects.

**Comment by lucasromanojf** [comment]
It looks like it is related to phpredis 6. RedisCluster constants were removed and only Redis constants should be used, if I understood correctly in some searches. 

Also Laravel itself has a merged PR that changes all RedisCluster constant references to Redis:

https://github.com/laravel/framework/pull/48362
