### ISSUE TITLE
With laravel breeze and react ,Inertia.js not working after installing the package 

### ISSUE THREAD

**Issue by moslemparve** [stancl/tenancy#1209]
### Bug description

I recently installed the Laravel Breeze authentication package in Laravel application, which includes Inertia.js and React. Subsequently, I integrated the multitenancy feature using the package . However, after this integration, I encountered an issue where Inertia.js stopped working when attempting to navigate to the login URL.
![Screenshot from 2024-04-16 09-51-29](https://github.com/archtechx/tenancy/assets/40214868/f1696071-a38a-43fa-add8-07d57958ed62)

### Steps to reproduce

Install Laravel Breeze: composer require laravel/breeze --dev
Setup Laravel Breeze authentication: php artisan breeze:install
Integrate laravel-tenancy package: composer require stancl/tenancy
Attempt to navigate to the login URL.

### Expected behavior

Inertia.js should function normally and allow navigation to the login URL after integrating laravel-tenancy package.

### Laravel version

10.10

### stancl/tenancy version

3.8

**Comment by stancl** [comment]
For support questions, use [our Discord](https://archte.ch/discord).
