### ISSUE TITLE
Jestream Laravel Tenacy

### ISSUE THREAD

**Issue by esmultiservicios** [stancl/tenancy#1211]
### Bug description

I am using Laravel for Tenancy with Jetstream, but when my tenants routes register their tenan it is save on the man domain

so I have configured everything but I don't know what else

### Steps to reproduce

**Boostrap\app.php**
<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;
use Illuminate\Support\Facades\Route;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
/*         web: __DIR__.'/../routes/web.php',
        api: __DIR__.'/../routes/api.php', */
        using: function () {
            $centralDomains = config('tenancy.central_domains');
    
            foreach ($centralDomains as $domain) {
                Route::middleware('web')
                ->domain($domain)
                ->group(base_path('routes/web.php'));;
            }

            foreach ($centralDomains as $domain) {
                Route::prefix('api')
                ->domain($domain)
                ->middleware('api')
                ->group(base_path('routes/api.php'));
            }            
    
            Route::middleware('web')->group(base_path('routes/tenant.php'));
        },         
        /* commands: __DIR__.'/../routes/console.php', */
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {
        //
    })
    ->withExceptions(function (Exceptions $exceptions) {
        //
    })->create();

**Boostrap\providers.php**
<?php

return [
    App\Providers\AppServiceProvider::class,
    App\Providers\FortifyServiceProvider::class,
    App\Providers\JetstreamServiceProvider::class,
    App\Providers\TenancyServiceProvider::class,
];

**routes\tenant.php**
<?php

declare(strict_types=1);

use Illuminate\Support\Facades\Route;
use Stancl\Tenancy\Middleware\InitializeTenancyByDomain;
use Stancl\Tenancy\Middleware\PreventAccessFromCentralDomains;

/*
|--------------------------------------------------------------------------
| Tenant Routes
|--------------------------------------------------------------------------
|
| Here you can register the tenant routes for your application.
| These routes are loaded by the TenantRouteServiceProvider.
|
| Feel free to customize them however you want. Good luck!
|
*/

Route::middleware([
    'web',
    InitializeTenancyByDomain::class,
    PreventAccessFromCentralDomains::class,
])->group(function () {
    Route::get('/', function () {
        return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
    });
});

**routes\web.php**
<?php

use App\Http\Controllers\TenantController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::resource('tenants', TenantController::class)->except(['show']);
});

App\Models\Tenant.php
<?php

namespace App\Models;

use Stancl\Tenancy\Database\Models\Tenant as BaseTenant;
use Stancl\Tenancy\Contracts\TenantWithDatabase;
use Stancl\Tenancy\Database\Concerns\HasDatabase;
use Stancl\Tenancy\Database\Concerns\HasDomains;

class Tenant extends BaseTenant implements TenantWithDatabase
{
    use HasDatabase, HasDomains;
}

### Expected behavior

I expect if I am not create any tenant or domain the user can enter to other different central domain in my example my central domain is tenancy.test

### Laravel version

11

### stancl/tenancy version

3x

**Comment by stancl** [comment]
Jetstream isn't supported in Tenancy v3. It will be supported in the upcoming v4 release.

**Comment by esmultiservicios** [comment]
Do you have any idea when it will be available or where I can follow this?

**Comment by stancl** [comment]
All updates are posted [on our Discord](https://archte.ch/discord).

**Comment by esmultiservicios** [comment]
Hello I was reading your post

[Image]

Please I want to have access to tenancy v4.

If you can add me

Thank you so much

Enviado desde mi Samsung Mobile de Claro
Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stancl** [comment]
To join early access, follow the instructions on Discord. v4 is handled entirely there.
