### ISSUE TITLE
Tenancy is not working for Livewire

### ISSUE THREAD

**Issue by GBeushausen** [stancl/tenancy#1219]
### Bug description

The app works fine with everything but Livewire (3). When using Livewire, it tries to access the main database and not the tenants.

### Steps to reproduce

 So then i followed this doc: https://tenancyforlaravel.com/docs/v3/integrations/livewire/ and then tried to enable Universal Routes https://tenancyforlaravel.com/docs/v3/features/universal-routes . But the documentation is wrong. In bootstrap/app.php there is no ->withMiddleware function on $app. Without that its saying "Target class [universal] does not exist.". I guess i have to add it to kernel.php like this.
 `    protected $middlewareGroups = [
        'web' => [
            UniversalRoutes::class,
        ],
`
But then i get Object of type Stancl\Tenancy\Features\UniversalRoutes is not callable

### Expected behavior

The application should work with LiveWire 3 and the documentation should tell exactly how to achieve that.

### Laravel version

10

### stancl/tenancy version

3

**Comment by GBeushausen** [comment]
Probably this is more correct: 
`        'universal' => [
            UniversalRoutes::class,
        ],
`
But it's still the same "Object of type Stancl\Tenancy\Features\UniversalRoutes is not callable"

**Comment by GBeushausen** [comment]
Seems. like it just has to be an empty array
`        'universal' => [],
`
An updated documentation would be nice though.

**Comment by stancl** [comment]
It does say it should be an empty middleware group:
![CleanShot 2024-05-03 at 11  27 02@2x](https://github.com/archtechx/tenancy/assets/33033094/256e9563-2f3b-4052-b2bb-6dd4396dd7a0)

> updated documentation would be nice though

It is updated for Laravel 11. Unfortunately the app skeleton differences between L10 and L11 are too big and keeping docs for both versions would be messy on the current docs website.

**Comment by stancl** [comment]
https://github.com/stancl/tenancy-docs/commit/3f60cdbe58057986b23ffcda4273014791ebe1d5
