### ISSUE TITLE
Nested sub domain

### ISSUE THREAD

**Issue by salacsoft** [stancl/tenancy#1220]
### Bug description

Tenancy is not working properly on nested subdomain. 

### Steps to reproduce

I have a laravel project and installed tenancy. on the deployment server it uses subdomain, so upon creating tenant it will be nested subdomain. when i try to visit the tenant subdomain, its not getting in into the routes of my tenants.

### Expected behavior

it should handle the nested subdomain properly

### Laravel version

10

### stancl/tenancy version

3.7

**Comment by stancl** [comment]
Can you provide more context? Tenancy works just fine with any subdomain levels. The issue description doesn't really give any specifics.

**Comment by salacsoft** [comment]
usually the application is deployed to a domain then the tenancy will create subudomain for each tenant. however on my case the application is deployed in subdomain, so when the tenant is created it will be nested domain. 
for example my application is deployed in myapp.mydomain.com so the tenant domain will be tenant.myapp.mydomain.com

**Comment by stancl** [comment]
You haven't said what in Tenancy doesn't work when you use that setup. It just sounds like you're facing some unrelated issue.
