### ISSUE TITLE
Could Not Switch tenants when using Aritsan command 

### ISSUE THREAD

**Issue by ashishimple** [stancl/tenancy#1222]
### Bug description

In our project we log the erros using AWS cloudwatch, and when we run the laravel artisan command for multiple tenancy **without --tenants**  , when tenancies are switched
the new tenancy is not captured in cloudwatch logging 

does not work with  `php artisan tenants:run command:CloudWatchTest   `

this works when we mention particular tenant name --tenants=tenantName in artisan command

### Steps to reproduce

php artisan tenants:run command:CloudWatchTest 

`
// cloudwatch class
Class CloudWatchLoggerFactory
{

    public function __invoke(array $config)
    {
        $sdkParams = $config["sdk"];
        $tags = $config["tags"] ?? [];
        $name = $config["name"] ?? 'cloudwatch';

        // Instantiate AWS SDK CloudWatch Logs Client
        $client = new CloudWatchLogsClient($sdkParams);

        // Log group name, will be created if none
        $groupName = tenant('id') . '-' . config('app.env');

        // Log stream name, will be created if none
        $streamName = $config["stream"];

        // Days to keep logs, 14 by default. Set to `null` to allow indefinite retention.
        $retentionDays = $config["retention"];
		dump("CloudWatchLoggerFactory = ".  tenant('id'));  --------------------------->  tenant is not switch here <-------
        // Instantiate handler (tags are optional)
        $handler = new CloudWatch($client, $groupName, $streamName, $retentionDays, 1, $tags);

        // Create a log channel
        $logger = new Logger($name);
        // Set handler
        $logger->pushHandler($handler);

        return $logger;
    }`

my config/logging.php is as follows 

'cloudwatch' => [
            'driver' => 'custom',
            'via' => pathTo\Logging\CloudWatchLoggerFactory::class,
            'sdk' => [
                'region' => env('CLOUDWATCH_LOG_REGION', 'us-east-1'),
                'version' => 'latest',
                'credentials' => [
                    'key' => env('CLOUDWATCH_KEY'),
                    'secret' => env('CLOUDWATCH_SECRET')
                ]
            ],
            'retention' => env('CLOUDWATCH_LOG_RETENTION', 30),
            'level' => env('CLOUDWATCH_LOG_LEVEL', 'info'),
            'stream' => env('CLOUDWATCH_STREAM', 'laravel-log'),
        ],

### Expected behavior

I want to log tenant wise , by changing the 

` $groupName = tenant('id') . '-' . config('app.env');`

whenever the tenant is change in artisan command

### Laravel version

8.0.13

### stancl/tenancy version

3.5.0

**Comment by stancl** [comment]
The issue is likely that some class persists the current tenant (or state derived from it) and doesn't react to `tenant()` changing.

This isn't a bug in the package. For support questions use [our Discord](https://archte.ch/discord).
