### ISSUE TITLE
laravel 10 support

### ISSUE THREAD

**Issue by jlopez0313** [stancl/tenancy#1224]
### Bug description

Any body please guide me how to configure universal routes from tenancyforlaravel on larvel 10

### Steps to reproduce

i have installed fresh laravel 10 version but in new documentation a lot things has changed

### Expected behavior

in Laravel 11 app/providers is not same as Laravel 10 service provider section has changed

### Laravel version

10

### stancl/tenancy version

3

**Comment by stancl** [comment]
https://github.com/stancl/tenancy-docs/commit/3f60cdbe58057986b23ffcda4273014791ebe1d5

Use the proper channels for support questions.
