### ISSUE TITLE
Create Tenant will trigger Tenancy bootstrappers

### ISSUE THREAD

**Issue by luckykenlin** [stancl/tenancy#1231]
### Bug description

Create Tenant Will Trigger Tenancy Bootstrappers

I have a customer bootstrapper that should access the tenant database, but I run into the issue where the table is not found in the tenant database.

I found that creating a tenant will also trigger the tenancy bootstrappers. How can I avoid this?

### Steps to reproduce

laravel 11 with laravel tenancy

### Expected behavior

Should not trigger bootstrap Since we still on central zone.

### Laravel version

11

### stancl/tenancy version

3.8.4

**Comment by stancl** [comment]
Please use the right channels for support questions.
