### ISSUE TITLE
Jetstream will be supported in v4.

### ISSUE THREAD

**Issue by Silomalo** [stancl/tenancy#1235]
Jetstream will be supported in v4.

_Originally posted by @stancl in https://github.com/archtechx/tenancy/issues/549#issuecomment-1359967385_
    
Hello @stancl, has there been any improvement in integrating jetstream with the library, I have an existing project that am trying to add tenancy but I cant be able to login in tenant roots.
Kindly assist.

**Comment by Silomalo** [comment]
@stancl is there any way I can be able to go around the auth process? I am unable to log in and also I am not able to utilize the auth facade in Laravel.
Members any solution around this?

**Comment by stancl** [comment]
Use the right channels for support questions. Updates about v4 are posted on Discord.
