### ISSUE TITLE
Error There are no commands defined in the "tenancy" namespace. when run php artisan tenancy:install

### ISSUE THREAD

**Issue by Jhon-Henkel** [stancl/tenancy#1240]
### Bug description

the error occurs when you execute the second step of the documentation, that of running the command "php artisan tenancy:install"

### Steps to reproduce

Just execute documentation guide https://tenancyforlaravel.com/docs/v3/installation/

### Expected behavior

work properly

### Laravel version

11.18

### stancl/tenancy version

3.8.4

**Comment by stancl** [comment]
You likely skipped a step in the guide. If you need support, use the right channels for that, don't submit bug reports.

**Comment by Jhon-Henkel** [comment]
I didn't skip any step, because the step that causes the problem is the second one. I run composer require and tried running php artisan...

**Comment by stancl** [comment]
https://asciinema.org/a/WLTJ1FSCFqLiBFJjrUVG5C35f
