### ISSUE TITLE
CSRF token mismatch when InitializeTenancyByRequestData middleware is used

### ISSUE THREAD

**Issue by jialeee17** [stancl/tenancy#1244]
### Bug description

I'm building the APIs for my SPA using the [SPA Authentication](https://laravel.com/docs/11.x/sanctum#spa-authentication). I realized that when I apply any of the tenancy initialization middlewares such as InitializeTenancyByRequestData, I got the "CSRF token mismatch." issue. Is anyone facing the same issue?

### Steps to reproduce

1. Make a [request](https://laravel.com/docs/11.x/sanctum#spa-authenticating) to get CSRF token 
2. Make a [POST request](https://laravel.com/docs/11.x/sanctum#logging-in)

### Expected behavior

Receive 419 "CSRF token mismatch" error response 

### Laravel version

11.18.1

### stancl/tenancy version

3.8

**Comment by stancl** [comment]
Please use the right channels for support questions.
