### ISSUE TITLE
Postgres 

### ISSUE THREAD

**Issue by mahmoudreyaddev1** [stancl/tenancy#1248]
### Bug description

$tenant1 = App\Models\Tenant::create(['id' => 'foo']);

SQLSTATE[42601]: Syntax error: 7 ERROR:  zero-length delimited identifier at or near """"
LINE 1: create table "" ()
                     ^ (Connection: tenant, SQL: create table "" ()).

### Steps to reproduce

try creating tenant using 
$tenant1 = App\Models\Tenant::create(['id' => 'foo']);
doesn't work neither from tinker or from controller action

### Expected behavior

return Created Tenant Model

### Laravel version

8.2.0

### stancl/tenancy version

3.1.0

**Comment by stancl** [comment]
Please use our Discord for support questions.
