### ISSUE TITLE
Following steps on guide and errors when creating new tenants

### ISSUE THREAD

**Issue by timothymarois** [stancl/tenancy#1249]
### Bug description

Using Tinker example after following instructions https://tenancyforlaravel.com/docs/v3/quickstart

```

> $tenant1 = App\Models\Tenant::create(['id' => 'test']);

   WARNING  Undefined array key "local" in vendor/stancl/tenancy/src/Bootstrappers/FilesystemTenancyBootstrapper.php on line 90.

   WARNING  Undefined array key "public" in vendor/stancl/tenancy/src/Bootstrappers/FilesystemTenancyBootstrapper.php on line 90.

   BadMethodCallException  Call to undefined method Stancl\Tenancy\Database\Models\Tenant::database().
```

The trait for `database()` is available on the tenant model, but the one in vendor does not have that as its parent. but I'm not sure why its doing that. Looks like database was actually created, so all access is there, but still looks like this isn't refined. 

### Steps to reproduce

https://tenancyforlaravel.com/docs/v3/quickstart

### Expected behavior

Should create without errors

### Laravel version

11

### stancl/tenancy version

3

**Comment by stancl** [comment]
This just looks like a configuration issue in your app. Read the error message in depth and go look at the code.

> Call to undefined method Stancl\Tenancy\Database\Models\Tenant::database()

Tenancy doesn't call this model directly, it calls your *configured* tenant model.

The other errors are likely related to your filesystem configuration, see the mentioned lines of the filesystem bootstrapper to see what it's doing. My guess without looking at the code is that the default tenancy config references those two disks, but they don't exist in your app.

For support questions, use [our Discord](https://archte.ch/discord).

**Comment by timothymarois** [comment]
@stancl I found it, the default config calls the vendor tenant model by default here 

```
use Stancl\Tenancy\Database\Models\Tenant;
'tenant_model' => Tenant::class,
```

Fixed it by doing:
```
'tenant_model' => App\Models\Tenant::class,
```

**Comment by timothymarois** [comment]
Looking over the doc, I did miss that one part that says make sure to change the config. Thanks, no issue here. That is my fault.
