### ISSUE TITLE
Call to undefined method Stancl\Tenancy\Database\Models\Tenant::database()

### ISSUE THREAD

**Issue by jlopez0313** [stancl/tenancy#1250]
### Bug description

After run tenant create command, i got this error:
` Call to undefined method Stancl\Tenancy\Database\Models\Tenant::database().`
Then the 

### Steps to reproduce

i'm getting the issue, when i run this command line:
`$tenant1 = App\Models\Tenant::create(['id' => 'foo']);`
Then, the domain is not being createad, the new database does, but neither migrations nor seeders

### Expected behavior

The tenant is created

### Laravel version

10.10

### stancl/tenancy version

3.8

**Comment by stancl** [comment]
Follow the quickstart guide carefully.
