### ISSUE TITLE
No database is being created

### ISSUE THREAD

**Issue by plompd** [stancl/tenancy#1252]
### Bug description

I followed the instruction to setup this package. However, it doesn't create the tenant databases when creating a tenant and a domain using e.g. Tinker. What did I miss? Could it be permissions? I use a Mac with MySql installed and I configured my app to use the root user in my db connection.

### Steps to reproduce

Followed the installation guide.

### Expected behavior

Tenant databases are created

### Laravel version

latest

### stancl/tenancy version

latest

**Comment by stancl** [comment]
Please don't use bug reports for support questions.

**Comment by plompd** [comment]
Sorry.
