### ISSUE TITLE
Is it possible to use sub tenants?

### ISSUE THREAD

**Issue by SuperDJ** [stancl/tenancy#1254]
#### Description
Would like to make it possible to have some sort of sub tenant. For example I make a paas app for my customers/ tenants (main tenants). These tenants have their own customers/ tenants (sub tenants) that would also use the app. Would be nice to make it possible to identify the main tenants by subdomain and the sub tenants by path. The main tenants could each have their own database while the sub tenants are in the main tenants database.

#### References
- https://github.com/archtechx/tenancy/issues/654#issuecomment-846433642

**Comment by killua99** [comment]
This is extremely useful and what I'm looking for, I'm going to try to experiment myself and hack a bit building several tenants, have you tried this with the current setup?

**Comment by SuperDJ** [comment]
@killua99 no, at the moment I haven't tried anything yet. At the moment I could think of two possible solution for now. 

1. Create sub routes using another tenant identifier. But I think this is not going to work as the tenant identifiers could work against each other. Or not work at all as they both use the same methods making it impossible knowing which tenant needs to be used.
2. Use another packages such as [spatie tenancy](https://spatie.be/docs/laravel-multitenancy/v4/introduction). Altough not convenient it might work as you can use different methods to identify tenants. Also different methods for the current tenant are used.

A way to make something like this possible would be for example with a "level" of tenancy or relations. Then when using the `tenant()` and `tenancy()` methods add a "level" parameter. It could then look like `tenant(0)` for the main tenant and `tenant(1)` and so on for lower level tenants.

**Comment by stancl** [comment]
I'd need a very specific example of how this would be structured (including identification, database structure, etc) to consider this.

**Comment by avenjamin** [comment]
@SuperDJ could this be implemented by creating tenants as per normal but setting up a self reference type relationship?
Essentially a `parent_id` in your tenants table.

This article shows something similar:
https://joaorbrandao.medium.com/self-reference-laravel-model-fa8a7b37360d

**Comment by SuperDJ** [comment]
@avenjamin at the moment I don't think it will be possible to do in one package. As both the tenant and subtenant must somehow be accessible by `tenant()` and yet you need to distinguish between them. So for now I went with my second option use a second package so you can use `tenant()` and a method of that package for the subtenant, `Subtenant::current()` in case of Spatie.

**Comment by stancl** [comment]
Didn't get the details asked for above, closing for now.
