### ISSUE TITLE
Issue with Laravel Nova Tools Integration (API Requests to Backend)

### ISSUE THREAD

**Issue by HAL0594** [stancl/tenancy#1255]
### Bug description

After integrating the Tenancy package, the API request in nova tools no longer returns a response. Instead, my tools show the following error:

```
"message": "Target class [2] does not exist.",
    "exception": "Illuminate\\Contracts\\Container\\BindingResolutionException",
    "file": "/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php",
    "line": 914,
    "trace": [
        {
            "file": "/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php",
            "line": 795,
            "function": "build",
            "class": "Illuminate\\Container\\Container",
            "type": "->"
        },
```

I also added `InitializeTenancyByDomain::class` and `PreventAccessFromCentralDomains::class` to my API and web route groups in `kernel.php`, as well as to the middlewares in `nova.php`, but I still encountered the same issue.

Does anyone have any idea why this error occurs when making a request with Axios? Or is there an additional step, such as registering the provider or middleware, to make it work with the Tools? I appreciate any help in advance.

### Steps to reproduce

I recently started using the Tenancy package for an integration with Laravel Nova 4. I followed the steps in the official guide:

- [Quickstart](https://tenancyforlaravel.com/docs/v3/quickstart)
- [Nova Integration Guide](https://tenancyforlaravel.com/docs/v3/integrations/nova)
- [Sanctum Integration Guide](https://tenancyforlaravel.com/docs/v3/integrations/sanctum)

The connection with the domains and databases works well for Nova Resources. However, I'm encountering issues with API routes related to the Tools in my application.

My API routes are configured as follows in routes/api.php:

```php
<?php
use Illuminate\Support\Facades\Route;
use Stancl\Tenancy\Middleware\InitializeTenancyByDomain;
use Stancl\Tenancy\Middleware\PreventAccessFromCentralDomains;

Route::name('api.')->group(function () {
    foreach (File::allFiles(__DIR__ . '/api') as $partial) {
        require_once $partial->getPathname();
    }
});

Broadcast::routes(['middleware' => ['auth:sanctum', InitializeTenancyByDomain::class, PreventAccessFromCentralDomains::class]]);
```

For instance, if I had a file with routes in the /api directory (e.g., /api/tool.php), it would look like this:

```php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ToolController;
use Stancl\Tenancy\Middleware\InitializeTenancyByDomain;
use Stancl\Tenancy\Middleware\PreventAccessFromCentralDomains;

Route::middleware([
    'auth:sanctum',
    InitializeTenancyByDomain::class,
    PreventAccessFromCentralDomains::class,
])->group(function () {
    Route::post('/tool/abc', [ToolController::class, 'functionABC']);
});
```

For example, in the Laravel Nova Tools, I typically use Axios to make requests to the backend:

```javascript
await axios
    .post('/api/tool/abc', {
        input: '123',
    })
    .then((response) => {
        let info = response.data;
        this.form = info.form;
    })
    .catch((error) => {})
    .finally(() => {});
```

### Expected behavior

I expected the API requests made from Laravel Nova Tools using Axios to function correctly and return the expected response data from the backend after adding the required tenancy middlewares. Specifically, I anticipated receiving the correct form data in the response without encountering any errors related to tenancy or API routing.

### Laravel version

10.48.22

### stancl/tenancy version

3.8

**Comment by stancl** [comment]
Please don't spam our repos. There's no bug in tenancy here. When you were opening this issue, it said where suport questions go.
