### ISSUE TITLE
tenant_route domain or subdomain

### ISSUE THREAD

**Issue by mauritskorse** [stancl/tenancy#1259]
### Bug description

tenant_route only works for full domains and not when subdomains are passed.

I am trying to get the `tenant_route()` from central context to a tenant context. Some of my tenants use subdomain others have their own domain. Right now the tenant_route function assumes all passed domains are full domains and not subdomains. So when a subdomain is passed into tenant_route (for example using `tenant()->domains->first()->domain` ) the url that is created becomes something like https://sudomain/route/path instead of https://sudomain.central_domain/route/path.

possible solution would be something like adding
```
  if (!strstr($domain, '.')) {
      $domain = $domain.'.'.config('tenancy.central_domains')[0];
  }
```

### Steps to reproduce

```php
$domain = tenant()->domains->first()->domain;
$url = tenant_route($subdomain, 'app.dashboard');
// url becomes https://sudomain/route/path
```

### Expected behavior

https://sudomain.central_domain/route/path

### Laravel version

11

### stancl/tenancy version

3.8.4

**Comment by stancl** [comment]
I don't understand how this is a bug.

**Comment by stancl** [comment]
The only real change we can make here is renaming the argument from `$domain` to `$hostname` to clarify the behavior. There's nothing else that can be done to the code.

> $domain = $domain.'.'.config('tenancy.central_domains')[0];

What if there are multiple central domains, and a different one than `[0]` is meant to be used?

People have asked about this before, but it's really not a bug, at most you can submit an issue in the docs repo if you feel something should be clarified in the docs.

All other solutions would be flaky, for instance if we only used `[0]` if `count($centralDomains) === 1`, that would break apps if a new central domain is added.

**Comment by jasonspick** [comment]
Yeah, I think this is a bug, unless this is the intended functionality. Here are my results:


`$link = tenant_route($tenant->domain()->first()->domain,'dashboard.inventory.import-errors');`
        generates:  "http://stark-industries/dashboard/inventory/import-errors"
        expected:  "http://stark-industries.shopstable.local/dashboard/inventory/import-errors"

**Comment by stancl** [comment]
Please read my comment above, I don't understand your comment in response to what I wrote there.

**Comment by jasonspick** [comment]
Yeah, I glossed over the part about multiple central domains.  I guess it was implied that there is only 1 central. "Center" plural, doesn't make sense.
