### ISSUE TITLE
Invalid method in QueueTenancyBootstrapper

### ISSUE THREAD

**Issue by eskayamadeus** [stancl/tenancy#1266]
### Bug description

The following lines of code in **QueueTenancyBootstrapper.php** appear to be invalid. When you use queue:work to run a queued job, the constructor of this class is called.

The constructor in turn calls `$this->setUpPayloadGenerator()`.

The payload generator includes the code aforementioned:

```php
protected function setUpPayloadGenerator()
    {
        $bootstrapper = &$this;
        
        if (! $this->queue instanceof QueueFake) {
            $this->queue->createPayloadUsing(function ($connection) use (&$bootstrapper) {
                // we never get here because the createPayloadUsing() method doesn't exist on `$this->queue` object. 
                // it exists on \Illuminate\Queue\Queue or \Illuminate\Support\Facades\Queue facade
                return $bootstrapper->getPayload($connection);
            });
        }
    }
```

The `$this->queue->createPayloadUsing()` closure is never executed because the createPayloadUsing() method doesn't exist on the `$this->queue` class. 

In the constructor, we see that `$this->queue` is an instance of `use Illuminate\Queue\QueueManager`. This class does not have the `createPayloadUsing()` method. Instead, it is available on the Illuminate\Queue\Queue class [as seen here](https://github.com/laravel/framework/blob/646520ad682d98b5211c6e26092259cfbe130b5c/src/Illuminate/Queue/Queue.php#L288).

### Steps to reproduce

- Install the Tenancy package.
- In QueueTenancyBootstrapper, put `dd('here')`  inside the closure at `$this->queue->createPayloadUsing()`.
- Dispatch a queued job or event inside your code, to be run in a tenant context.
- Run `php artisan queue:work`
- The dumped string will never output because the code never reaches that point.

Alternatively,
- put `get_class_methods($this->queue)` on the line just after `if (! $this->queue instanceof QueueFake)`.
- run `php artisan queue:work`
- a list of methods will be displayed but it will not include `createPayloadUsing()`

### Expected behavior

The job should dispatch and execute when queue:work is used.

### Laravel version

10.48.22

### stancl/tenancy version

3.8.5

**Comment by stancl** [comment]
I don't really get this issue. Are you commenting on the implementation or reporting a bug? **Say what doesn't work for you as expected**.

> The following lines of code in QueueTenancyBootstrapper.php appear to be invalid. When you use queue:work to run a queued job, the constructor of this class is called.

Pretty sure that's irrelevant. The code you're talking about affects *payload creation*, which happens *before* jobs are being processed by the queue worker. This logic running in `queue:work` doesn't really do anything.

> The $this->queue->createPayloadUsing() closure is never executed because the createPayloadUsing() method doesn't exist on the $this->queue class.

That would throw an exception, not silently fail.

> In the constructor, we see that $this->queue is an instance of use Illuminate\Queue\QueueManager. This class does not have the createPayloadUsing() method. Instead, it is available on the Illuminate\Queue\Queue class [as seen here](https://github.com/laravel/framework/blob/646520ad682d98b5211c6e26092259cfbe130b5c/src/Illuminate/Queue/Queue.php#L288).

https://github.com/laravel/framework/blob/61e221c18a89780ed5b51b59f04c0b4c389a457d/src/Illuminate/Queue/QueueManager.php#L11

> The dumped string will never output because the code never reaches that point

Again, the worker is not concerned with payload creation, it's reading already created payloads and executing them.

> a list of methods will be displayed but it will not include createPayloadUsing()

- https://github.com/laravel/framework/blob/61e221c18a89780ed5b51b59f04c0b4c389a457d/src/Illuminate/Queue/QueueManager.php#L291
- https://github.com/laravel/framework/blob/61e221c18a89780ed5b51b59f04c0b4c389a457d/src/Illuminate/Queue/QueueManager.php#L128
- https://github.com/laravel/framework/blob/61e221c18a89780ed5b51b59f04c0b4c389a457d/src/Illuminate/Queue/Queue.php#L286

**Comment by eskayamadeus** [comment]
I fixed the issue by modifying my SerializesModels trait in my event class, but I will soon respond to your comment with a more detailed explanation.

**Comment by eskayamadeus** [comment]
For your reference, someone posted a similar issue [on Laracasts](https://laracasts.com/discuss/channels/laravel/help-needed-with-tenant-aware-jobs-in-stancltenancy-multi-database-setup?page=1)

**Comment by stancl** [comment]
If this is related to #1260, post a minimal repro there. Please don't include any speculations, just verified info. The linked Laracasts question is likely unrelated though, since it was posted before any changes were made to the queue logic, so there's something misconfigured in that person's setup.

And for support questions use our Discord.

**Comment by eskayamadeus** [comment]
I think you do not get my issue. The basic issue is that the `createPayloadUsing()` method will simply never execute because you are calling it on the QueueManager, but the QueueManager does not include such a method.

Am I missing something here?

**Comment by stancl** [comment]
Did you completely ignore [my reply above](https://github.com/archtechx/tenancy/issues/1266#issuecomment-2451145892)?
