### ISSUE TITLE
Tenant CacheManager doesn't work properly when called through store()

### ISSUE THREAD

**Issue by mybouhssina** [stancl/tenancy#1269]
### Bug description

I'm using laravel-settings that uses cache through the method store() as follow:
Cache::store()->put(...)
Since the CacheManager injected by CacheTenancyBootstrapper to replace the default one doesn't override the 'store' method the tags aren't added as expected.

### Steps to reproduce

Try the following, the first two don't work but the third does.
```php
Tenant::first()->run(fn() => Cache::store('redis')->put('doesnt_work', 'true'));
Tenant::first()->run(fn() => Cache::store()->put('doesnt_work_neither', 'true'));
Tenant::first()->run(fn() => Cache::put('works', 'true'));
```

### Expected behavior

The prefix should be added even when we make cache calls through the store() method.

### Laravel version

10.48.25

### stancl/tenancy version

3.8.5

**Comment by stancl** [comment]
Due to how cache tenancy logic is implemented in v3, using individual stores isn't supported. In v4 we instead use prefixes which let us apply them on actual cache store instances.

**Comment by mybouhssina** [comment]
Wow, that was a quick answer !
I see, but do you see a problem with the following implementation of the CacheManager:

```php
public function store($name = null)
{
    /**
     * @var $store Repository
     */
    $store = parent::store($name);

    if($$store->getStore() instanceof TaggableStore) {
        return $store->tags([config('tenancy.cache.tag_base') . tenant()->getTenantKey()]);
    }
    return $store;
}
```

Thank you
