### ISSUE TITLE
Error 419 with Fortify 

### ISSUE THREAD

**Issue by IsaacHatilima** [stancl/tenancy#1270]
### Bug description

The tenant domains cannot make POST request to Fortify defined routes, getting error 419.

### Steps to reproduce

1. Configure a laravel breeze app with react and fortify. 
2. Make post request to any Fortify route for example /login

### Expected behavior

User should be logged in of /login as on central domain but fails with 419 error code.

### Laravel version

11.33

### stancl/tenancy version

3.8

**Comment by stancl** [comment]
Please use the right support channels.

**Comment by IsaacHatilima** [comment]
Which is? It is not on your website.
