### ISSUE TITLE
I can't access tenant('id')

### ISSUE THREAD

**Issue by Tarhex** [stancl/tenancy#1274]
### Bug description

This is not a bug per se, I couldn't join the Discord group for reasons I don't know, that's why I'm posting this here.

I'm trying to access `tenant('id`) on the `AppServiceProvider.php` file and the `tenant.php` route file and it keeps returning null. I can access a tenant on the domain `abc.example.test` and `bcd.example.test` and I can also access `tenant('id')` on blade files, component files (livewire) and controller files.

I tried running `dd(Tenant::all(), Domain::all())` and it ran without issues, indicating that I have two tenants registered. I have cleared application cache but I'm still facing this issue. I have checked if anything is wrong with the configuration I did, I can't find any issues.

### Steps to reproduce

I don't know if you can replicate this.

### Expected behavior

Being able to access `tenant('id)` on AppServiceProvider

### Laravel version

11.9

### stancl/tenancy version

3.8.5

**Comment by stancl** [comment]
The [Discord invite link](https://archte.ch/discord) works just fine.

You can't access the current tenant until there is a current tenant. That determination happens during the middleware part of the request lifecycle.
