### ISSUE TITLE
Option to have Path Resolver Forget parameter based on config option

### ISSUE THREAD

**Issue by Rafeethu** [stancl/tenancy#1281]
#### Description
It's better to enable/disable `$route->forgetParameter(static::$tenantParameterName);` in Path Resolver via a config option so that in some projects we can keep the parameter in the url for better identification and also to use this parameter in controllers for other needs. 

[https://github.com/archtechx/tenancy/blob/22dcb8b0693cfb0dbbf91a3e515ad9a9e2d5e95b/src/Resolvers/PathTenantResolver.php#L30C21-L30C36](url)

#### Why this should be added
we can enable / disable this based on projects. Also this forgetParameter() is not documented.

**Comment by stancl** [comment]
You can use tenant().
