### ISSUE TITLE
Error  Class 'App\Providers\Event' not found

### ISSUE THREAD

**Issue by epirir** [stancl/tenancy#482]
I am trying to insert saptie-laravel-permission but it gives me this error when I paste the following code in the boot method.

versions.
"laravel / framework": "^ 7.0",
 "spatie / laravel-permission": "^ 3.16",
"stancl / tenancy": "^ 3.1.7"

Thank you.

public function boot()
    {
        Schema::defaultStringLength(191);

        Event::listen(TenancyBootstrapped::class, function (TenancyBootstrapped $event) {
            \Spatie\Permission\PermissionRegistrar::$cacheKey = 'spatie.permission.cache.tenant.'.$event->tenancy->tenant->id;
        });
    }

error:

 Error 

  Class 'App\Providers\Event' not found

  at app/Providers/AppServiceProvider.php:24
    20|     public function boot()
    21|     {
    22|         Schema::defaultStringLength(191);
    23| 
  > 24|         Event::listen(TenancyBootstrapped::class, function (TenancyBootstrapped $event) {
    25|             \Spatie\Permission\PermissionRegistrar::$cacheKey = 'spatie.permission.cache.tenant.'.$event->tenancy->tenant->id;
    26|         });
    27|

**Comment by stancl** [comment]
Import the facade.

```
use Illuminate\Support\Facades\Event;
```

**Comment by epirir** [comment]
Thanks a lot!!!! @stancl
