### ISSUE TITLE
Share Language Session Between Tenants & Central App

### ISSUE THREAD

**Issue by ousid** [stancl/tenancy#719]
#### Describe the bug
I created an issue https://github.com/archtechx/tenancy/issues/714 `13 days ago` but it seems, after searching, can't find the answer for it.

I'm trying to make my app `multi-language` and this seems to not going to work on tenant domains.

##  Steps to Produce

In the `route` file, I make shared file for both tenants & central domain:

```php
Route::get('lang/switch/{lang}', LanguageController::class)
   ->name('language.switcher');
```

In the `Language Controller`

```php
class LanguageController extends Controller
{
    public function __invoke($lang, Request $request)
    {
        $languages = ['en', 'fr'];

        if (in_array($lang, $languages)) {

            $locale = session()->put('lang', $lang);

            App::setLocale(session('lang') ?? 'fr');

        }

        return back(302);
    }
}
```
I created a `middleware` to determine if there is a session or not with the tenant existence

```php
    public function handle(Request $request, Closure $next)
    {

        $subdomain = Arr::first(explode('.', $request->getHost()));

        if (
            $tenant = tenancy()->find(strtolower($subdomain))
        ) {
            tenancy()->initialize($tenant);
        }

        $this->switchLanguage();

        return $next($request);
    }

    private function switchLanguage()
    {
        if (session()->has('lang')) {
            app()->setLocale(session()->get('lang'));
        }

        if (!session()->has('lang')) {
            app()->setLocale(config('app.locale'));
            session()->put('lang', config('app.locale'));
        }
    }
```

## The Problem
Let's say you accessed `https://domain.ltd/lang/switch/fr` to get the French version, and in the `central domain` this process working nicely, but in the `tenants` I can see the value of the `session`but the `local` seems it has no change.

Hope this make sense.

#### Setup
 - Laravel version: [e.g. 8.4.0]
 - stancl/tenancy version: [e.g. 3.4.0]

**Comment by stancl** [comment]
> I can see the value of the sessionbut the local seems it has no change.

Hm?

I mean, is this related to tenancy even, or is that your feature of changing locales?

I'd appreciate if you could make an actual minimal and reproducible example. You're mixing sessions with locale here - which part is the one that doesn't work? And can you just provide *that* code?

**Comment by ousid** [comment]
It turns out, my mistake not the tenancy neither Laravel framework.

What I did is, register the middleware inside the `routeMiddleware` kernel property, and somehow it called the middleware before the controller (still doesn't figure out how?) So, I switched the middleware into `middlewareGroups` under the `web` middleware, and it works perfectly.

Thanks, @stancl,  For your help and providing this awesome package.

### Update:
I just discovered the tenancy life cycle in your docs and understand why, thanks again!

![image](https://user-images.githubusercontent.com/21012933/133598962-f2b521f7-bf42-4024-a3e2-bb31f3990d84.png)
