### ISSUE TITLE
PDOException thrown when creating a new tenant from Nova (PHP 8)

### ISSUE THREAD

**Issue by WillyReyno** [stancl/tenancy#720]
#### Describe the bug

Since upgrading to PHP 8, the Tenant creation process does not work properly when triggered from a Nova resource. 

We created a Tenant Resource in Laravel Nova which was working perfectly fine with PHP 7.4, the events were properly triggered, and we could use our new tenant app without any issue.

Now we are getting a `There is no active transaction` PDO Exception

The exception does not block the JobPipeline, the tenant is created in the central database, and the tenant database is also properly created & migrated.

I can also confirm the exception is not thrown when manually creating a Tenant with `new Tenant()` or within seeders.

I don't know if the following can help, but here's what I found after a few searches : 
- https://github.com/laravel/framework/issues/35161 (issue regarding seeders) 
- https://github.com/laravel/framework/pull/35988 (pull request but testing related)
- https://laravel.com/docs/8.x/database#implicit-commits-in-transactions (laravel documentation warning about implicit commits) 

#### Steps to reproduce

Using PHP 8 :
- Create a Tenant Resource in Laravel Nova
- Use the Create form on the resource to create a new tenant
- See the Exception.

#### Setup

- PHP 8.0.10
- Laravel v8.61.0
- Laravel Nova v3.29.0
- stancl/tenancy v3.4.4

**Comment by stancl** [comment]
Is this related to tenant creation or just Nova? And if it's just Nova, how does it create tenants?

**Comment by WillyReyno** [comment]
I think it's just Nova, because when creating a tenant through a seeder or a simple route containing `$tenant = new Tenant(); [...] $tenant->save()` it doesn't throw any exception. 

What do you mean how? 

All I know is that I'm using Nova the regular way, meaning that I have a Resource (CRUD) for my Tenant and when I use the creation form : 
- the Tenant is correctly created in my central db
- the event in JobPipeline of my TenancyServiceProvider are triggered : 
   - Tenant database is created
   - Tenant database is seeder
- But after that, the exception is thrown.

Thanks for your help

**Comment by stancl** [comment]
What if you queue the DB creation?

**Comment by WillyReyno** [comment]
It works! 

The only issue I had was regarding my TenantObserver's `created` method, which was throwing a `TenantDatabaseDoesNotExistException`, but I moved the code into a Job in the JobPipeline and everything works fine now.

Thanks for your help!

**Comment by stancl** [comment]
Right, the issue then was probably Nova wrapping the create logic in a transaction, but Tenancy would also handle DB creation which now can't be inside a DB transaction

**Comment by jwktje** [comment]
I'm having this issue too. Was the solution to queue something somewhere? Can you explain how you fixed it @WillyReyno?

**Comment by WillyReyno** [comment]
@jwktje in `TenantServiceProvider.php` I changed `shouldBeQueued(false)` to `shouldBeQueued(true)` on `TenantCreated`'s  `JobPipeline`. 

For example: 

```php
Events\TenantCreated::class => [
                JobPipeline::make([
                    Jobs\CreateDatabase::class,
                    Jobs\MigrateDatabase::class,
                ])->send(function (Events\TenantCreated $event) {
                    return $event->tenant;
                })->shouldBeQueued(true), // here
            ],
```

I already had queues running on my project since we use them for various stuff, so that was the only thing to do for me.

**Comment by jwktje** [comment]
@WillyReyno Yup that fixed it. That's great! Thanks for the quick response. This makes a lot of sense.

**Comment by ugurdnlr** [comment]
This method did not solve my problem. I still keep getting the same error when I create tenant from Nova. It does all the operations (such as creating a database, adding records) but throw exception

**Comment by scramatte** [comment]
Same problem here with Nova 4

**Comment by sajidparwez** [comment]
just wrap the code in event() method in TenancyServiceProvider.php file.

 public function events()
    {

        try {
            \DB::beginTransaction();
            return [
                // Tenant events
                Events\CreatingTenant::class => [],
                Events\TenantCreated::class => [
                    JobPipeline::make([
                        Jobs\CreateDatabase::class,
                        Jobs\MigrateDatabase::class,
                        // Jobs\SeedDatabase::class,
    
                        // Your own jobs to prepare the tenant.
                        // Provision API keys, create S3 buckets, anything you want!
    
                    ])->send(function (Events\TenantCreated $event) {
                        return $event->tenant;
                    })->shouldBeQueued(true), // `false` by default, but you probably want to make this `true` for production.
                ],
                
                Events\SavingTenant::class => [],
                Events\TenantSaved::class => [],
                Events\UpdatingTenant::class => [],
                Events\TenantUpdated::class => [],
                Events\DeletingTenant::class => [],
                Events\TenantDeleted::class => [
                    JobPipeline::make([
                        Jobs\DeleteDatabase::class,
                    ])->send(function (Events\TenantDeleted $event) {
                        return $event->tenant;
                    })->shouldBeQueued(true), // `false` by default, but you probably want to make this `true` for production.
                ],
    
                // Domain events
                Events\CreatingDomain::class => [],
                Events\DomainCreated::class => [],
                Events\SavingDomain::class => [],
                Events\DomainSaved::class => [],
                Events\UpdatingDomain::class => [],
                Events\DomainUpdated::class => [],
                Events\DeletingDomain::class => [],
                Events\DomainDeleted::class => [],
    
                // Database events
                Events\DatabaseCreated::class => [],
                Events\DatabaseMigrated::class => [],
                Events\DatabaseSeeded::class => [],
                Events\DatabaseRolledBack::class => [],
                Events\DatabaseDeleted::class => [],
    
                // Tenancy events
                Events\InitializingTenancy::class => [],
                Events\TenancyInitialized::class => [
                    Listeners\BootstrapTenancy::class,
                ],
    
                Events\EndingTenancy::class => [],
                Events\TenancyEnded::class => [
                    Listeners\RevertToCentralContext::class,
                ],
    
                Events\BootstrappingTenancy::class => [],
                Events\TenancyBootstrapped::class => [],
                Events\RevertingToCentralContext::class => [],
                Events\RevertedToCentralContext::class => [],
    
                // Resource syncing
                Events\SyncedResourceSaved::class => [
                    Listeners\UpdateSyncedResource::class,
                ],
    
                // Fired only when a synced resource is changed in a different DB than the origin DB (to avoid infinite loops)
                Events\SyncedResourceChangedInForeignDatabase::class => [],
            ];
            
          
            \DB::commit();
          } catch(\Exception $e) {
             \DB::rollback();
             // Handle Error
          }


        
    }

**Comment by stancl** [comment]
That’s not how PHP works, the try {} will not do anything.
