### ISSUE TITLE
Setting tenancy in cpanel

### ISSUE THREAD

**Issue by vhgah** [stancl/tenancy#722]
Hey, Thanks for creating such a great package, i just finished a pharmacy management saas project, i work with cpanel. And I have a few things to share. 
First: create new database in phpmyadmin cpanel, you have to use:
$cPanel->execute('uapi', 'Mysql', 'create_database', $nameDatabase);
and create subdomain:
$cPanel->execute('api2',"SubDomain", "addsubdomain" , $subdomain);
you have to configure dns. When running, there may be an error: file_get_content xxx just delete cache in bootstrap and everything word fine.

if you use another database name:
config(['database.connections.mysql.database' => '']);
DB::connection("mysql")->table("national_medicines_list");

**Comment by stancl** [comment]
There's no plan to support cpanel, sorry. We could add features for it but I view using it as a bad practice and you should really use something like Ploi, Forge, or Vapor instead.
