### ISSUE TITLE
NGINX headers not working when served via tenant

### ISSUE THREAD

**Issue by philip-niewold** [stancl/tenancy#723]
#### Describe the bug
When trying to cache static files we noticed the customer headers in the nginx conf file are not added to the response served over the tenant domain.

#### Steps to reproduce
Add the following to the nginx config to cache the static files and visit a file.
`    	# browser caching
	location ~* \.(jpg|jpeg|png|gif|ico|css|woff2|js|svg)$ {
	expires 7d;
	}	
`

#### Expected behavior
We expect the expires header to be added to the response headers when requesting the file via the tenant. 

When we request a static file via the main domain example.com/js/uikit.js we get the expires header as expected. But when we request the file via a tenant, in example: tenant1.example.com/js/uikit.js we do not get the expires header. 

We think it has something to do with the fact that the files in the second example are returned using the tenancy package. But we don't know why that would cause the header to not be added.

#### Your setup
 - Laravel version: 8.61.0
 - stancl/tenancy version: 3.4.4

**Comment by stancl** [comment]
> But when we request the file via a tenant, in example: tenant1.example.com/js/uikit.js we do not get the expires header.

I don't think this is related to the package

> We think it has something to do with the fact that the files in the second example are returned using the tenancy package

If the route is `/js/uikit.js`, there's no tenancy route caching this. It's just the asset being served. The package doesn't affect this at all as far as I know.

**Comment by Laripoli** [comment]
Hey, I think I have a similar problem, I have a css file in my tenant's storage, when I try to fetch it, it returns the file but the content-type header is 'text/plain', if I move the same file to the global storage it is returned with the correct content-type header text/css

**Comment by stancl** [comment]
We've addressed this in v4 by making headers in `TenantAssetController` configurable. In v3 you can set up your own route.
