### ISSUE TITLE
TenantCouldNotBeIdentifiedOnDomainException 

### ISSUE THREAD

**Issue by sarmenb** [stancl/tenancy#724]
### Problem

This is for whoever is getting the TenantCouldNotBeIdentifiedOnDomainException for when a tenant does not exist

#### Solution

What i did is in the Providers/TenancyServiceProvider in the boot method i put this and it works like a charm.

```
InitializeTenancyByDomain::$onFail = function ($exception, $request, $next) {
            return redirect('http://my-domain.com'); //the domain you want redirected to, or you can also show a custom error page
};
```

#### Your setup
 - Laravel version: [e.g. 8.61.0]
 - stancl/tenancy version: [3.4]

**Comment by andreasmatuszewski** [comment]
If this does not work for someone - check if you are using [universal routes](https://tenancyforlaravel.com/docs/v3/features/universal-routes). You have to deactivate universal routes to use this solution.
