### ISSUE TITLE
using laravel breeze on  central domain and twnant

### ISSUE THREAD

**Issue by sarmenb** [stancl/tenancy#725]
#### Describe the bug
this isnt a bug, but what inwad wondering how do you implement breeze when you have it setup for the central domain as well as a tenant?

i have a tenant named sample.centraldomain.test and when i try to login i get an error saying that the user im trying to login with wasnt found. then i realized its looking for the user in the central domain instead of the tenant database.

#### Your setup
 - Laravel version: [e.g. 8.2.0]
 - stancl/tenancy version: [e.g. 3.1.0]

**Comment by stancl** [comment]
Please respect the issue templates and don't spam the repository. I usually block for this.

**Comment by sarmenb** [comment]
ok sorry

[Sarmen B - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=182eaa)	[182eaa]

On September 27, 2021 at 6:31 GMT, Samuel Štancl ***@***.***> wrote:

Please respect the issue templates and don't spam the repository. I usually block for this.
