### ISSUE TITLE
Single DB Tenancy using multiple tables with tenant_id as prefix

### ISSUE THREAD

**Issue by ssarljames** [stancl/tenancy#727]
I'm not sure if this is already available but I actually having a hard time getting a resource for this.

I'm planning to implement multi-tenancy using a single database by not using **tenant_id** columns on each tenant table but creating multiple tables with the prefix of tenant_id.

So here's the target DB structure

**Tenant 1 Tables:**

- tenant_1_users
- tenant_1_posts
- tenant_1_comments

**Tenant 2 Tables:**

- tenant_2_users
- tenant_2_posts
- tenant_2_comments

If this is not available yet, do we have a chance to have this in the future?

Or can you guys can help me with a possible workaround for this.

Thank you.

**Comment by stancl** [comment]
Hey, 

thanks for the feature suggestion, but this is (likely) not going to be implemented.

I'd need to hear a few good use cases for this approach to decide to implement it.

Thanks

**Comment by stancl** [comment]
Thinking about it - it'd probably not be hard to _implement_ it. But I find the solution kinda ugly and not very flexible, though that's similar to general single db tenancy.

Can you share why you'd like to use this instead of the other approaches? Might re-consider for v4 if there are good reasons

**Comment by ssarljames** [comment]
@stancl Single DB is the only option I have because our subscription on the server doesn't allow us to create a database dynamically. This option was chosen because table prefixes provide separate unique keys per tenant table and backup can be done by filtering the table prefixes only, not by filtering the data using the "tenant_id" column.
