### ISSUE TITLE
Allow Subdomain identification and Path identification in the same application

### ISSUE THREAD

**Issue by abdunnasir** [stancl/tenancy#730]
It would be great if tenant can be identified by Subdomain or Path in the same application.
So if we create a tenant with subdomain, he will be identified by subdomain.

If it's possible, tenants could choose between path or subdomain.

**Comment by stancl** [comment]
I said mention this in the pinned issue, not open a new issue. Please move the suggestion to that thread. Thanks!

**Comment by gabebritto** [comment]
Any news about this feature?

**Comment by stancl** [comment]
There isn't anything preventing you from using multiple identification approaches in a single application. You just need the routes to be separately defined.
