### ISSUE TITLE
Delete subdomains and identify by sessions?

### ISSUE THREAD

**Issue by alexv96** [stancl/tenancy#732]
I am trying to make a paid app, for which I would have 2 plans, for the moment the difference would be the subdomain.

Example:

Basic plan:
- No subdomain.
- It does not have integrated wsp access.
- Basic functionalities

Plus Plan:
- It has its own subdomain.
- Integration with Whatsapp API and others.
- Basic functionalities + others.

Base URL: http://www.propower.test

So I was wondering if with this library of tenancy, is it possible or how I could work with all tenants in basic plan with the same URL example http://www.propower.test/login all enter the same base URL, and when they are already logged in no subdomain is added but to save the tenant ID as a session variable.

**Comment by stein-j** [comment]
Hello @alexv96,

have you been able to work out what you want to do ? If so please close your issue.
A tenant can be identified by its domain, subdomain, path or query data. [https://tenancyforlaravel.com/docs/v3/tenant-identification](https://tenancyforlaravel.com/docs/v3/tenant-identification)
If you need help you can always join the discord, you can find the link [https://tenancyforlaravel.com/](https://tenancyforlaravel.com/)
