### ISSUE TITLE
Email verification link for central domain instead of tenant domain

### ISSUE THREAD

**Issue by neppoz** [stancl/tenancy#741]
#### Describe the bug
Hi everybody,

i implemented the OnBoarding Flow with domains and it is working fine. I have on problem. My application requires verified Users. Here is my function in the job creating the tenant

```
$this->tenant->run(function ($tenant) {
            $adminUser = User::create(
                $tenant->only(['name', 'email', 'password', 'lang', 'privacy_confirmed_at'])
            );
            User::findOrFail($adminUser->id)->roles()->sync([User::IS_ADMIN]);
            **$adminUser->sendEmailVerificationNotification();**

            $tenant->update([
                'name' => '', // We don't need this anymore
                'ready' => true,
            ]);
        });
```

The problem is that the user get's a verification link, but unfortunately from the central domain and not from the tenant domain. Any suggestions?

 - Laravel version: 8.0
 - stancl/tenancy version: 8.0

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://discord.gg/vHjEyrw

Thanks
