### ISSUE TITLE
Support for schema:dump

### ISSUE THREAD

**Issue by obrunsmann** [stancl/tenancy#748]
I felt in love with the `schema:dump --prune` command to clean up the messy migrations folder. It's not that much urgent and just a nice feature for developer experience imho. Maybe a suggestion for #654  :)

**Comment by stancl** [comment]
This feature is a bit complex, because the command needs a database connection. Going to hold this off until more people request it 👍🏻

**Comment by jonerickson** [comment]
I second this. For large projects with several migrations, this becomes a necessity.

**Comment by masiorama** [comment]
I second this too.

**Comment by lucasromanojf** [comment]
Me too

**Comment by stancl** [comment]
https://github.com/archtechx/tenancy/commit/7d98ebb5d177a1ac30ec0a7d248c4cd254abce4a

**Comment by miagg** [comment]
Oh yes please!

**Comment by massiws** [comment]
@stancl can this feature be merged also into 3.x branch?

**Comment by stancl** [comment]
No. The feature required several more changes since it was added. I don't want to maintain the same new code in two branches.

**Comment by massiws** [comment]
> No. The feature required several more changes since it was added. I don't want to maintain the same new code in two branches.

Reasonable. 

Waiting v-4.x to be released, I've created a custom command based on [merged PR](https://github.com/archtechx/tenancy/pull/807): only a little change was necessary.
If someone is interested can be found [here](https://gist.github.com/massiws/03867e2be58b907f612527008af2e8ec).

**Comment by vitorfba** [comment]
> > No. The feature required several more changes since it was added. I don't want to maintain the same new code in two branches.
> 
> Reasonable.
> 
> Waiting v-4.x to be released, I've created a custom command based on [merged PR](https://github.com/archtechx/tenancy/pull/807): only a little change was necessary. If someone is interested can be found [here](https://gist.github.com/massiws/03867e2be58b907f612527008af2e8ec).

You're a lifesaver, thanks a ton!
