### ISSUE TITLE
Permission Cache or Tenant Roles addition causes Central DB roles to be changed

### ISSUE THREAD

**Issue by livinglegend13** [stancl/tenancy#753]
I am using very popular jeremykenedy/laravel-roles package. https://github.com/jeremykenedy/laravel-roles
This is similar to Spatie but there are some additions to it. Looks like similar to issue # 230 there seems to be caching of permission to save DB queries. I browsed all the package repo for laravel-roles and could not find PermissionRegistrar similar to Spatie.
This is the similar issue like @can uses central DB in tenant app #230

Is there a way to disable cache for roles for jeremykenedy/laravel-roles package or laravel-auth repo. I know this might not be stancl tenancy issue but help will definently be appreciated as many folks jeremykenedy package for roles and auth.

#### Steps to reproduce

Install Laravel Auth https://github.com/jeremykenedy/laravel-auth  (This contains Laravel Roles package too)
Install Stancl Tenancy package with multi database setup
Create New Role in Tenant e.g. Admin
New role will also be replicated now in Central DB without using Syncable

All other items do not replicate/sync including creation of users etc. Only Roles replicate possibly due to caching feature somewhere.

#### Expected behavior
Tenant role changes should not affect central roles

#### Your setup
 - Laravel version: 8
 - stancl/tenancy version: 3.4.5

**Comment by stancl** [comment]
Is this a bug with this package or related to integrating with another package? If the latter then this shouldn't be tagged as a bug

**Comment by livinglegend13** [comment]
Sorry about that..definitely not a bug. I am unable to remove the bug label. This is an issue rather than bug. Appreciate your time to respond on this.

**Comment by stancl** [comment]
I'll tag this as an integration issue 👍🏻

**Comment by stancl** [comment]
Actually, going to hold this off until more people request this. Since it's an integration issue, not a core issue.
