### ISSUE TITLE
Class "Stancl\Database\Models\Tenant" not found

### ISSUE THREAD

**Issue by LarryBarker** [stancl/tenancy#756]
### Bug description

Installed on a Laravel 8 project, followed quick start guide and am faced with this error:
`Class "Stancl\Database\Models\Tenant" not found`

### Steps to reproduce

1. run `composer require stancl/tenancy`
2. Follow quick start guide

### Expected behavior

Application should load without error

### Laravel version

8.*

### stancl/tenancy version

3.4

**Comment by aeq-dev** [comment]
Did you set 'tenant_model' => \App\Models\Tenant::class in config/tenancy.php and run config:cache ?

**Comment by stancl** [comment]
Yeah that's clearly just a missing import

**Comment by LarryBarker** [comment]
I did. Not sure what the issue was. I removed the package, reinstalled and it's working now.
