### ISSUE TITLE
tenant database access on NovaServiceProvider boot method

### ISSUE THREAD

**Issue by bsormagec** [stancl/tenancy#763]
### Bug description

When I try to get tenant data on the novaServiceProvider boot method it is not working. 

### Steps to reproduce

composer install optimistdigital/nova-settings
Then go NovaServiceProvider add a select field with data from any tenant user table and it returns error table not found.

### Expected behavior

Just need to get data from the tenant on NovaServiceProvider's boot method.

Thanks.

### Laravel version

8.76.0

### stancl/tenancy version

^3.4

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://discord.gg/vHjEyrw

Thanks
