### ISSUE TITLE
Migrate to phpcsfixer

### ISSUE THREAD

**Issue by stancl** [stancl/tenancy#767]
We should move from styleci to our phpcsfixer config in [archtechx/template](https://github.com/archtechx/template)

**Comment by stancl** [comment]
The PR should target `master`, rather than `3.x`

**Comment by erikgaal** [comment]
Now that [Pint](https://github.com/laravel/pint) is being introduced, might it be worth to use that instead?

**Comment by stancl** [comment]
We'll go with php-cs-fixer for consistency across our repos 👍🏻

**Comment by stancl** [comment]
Resolved in #902
