### ISSUE TITLE
Exception: There is no active transaction

### ISSUE THREAD

**Issue by kkbt** [stancl/tenancy#772]
### Bug description

For every new registered user, a new tenant (with database) should be created automatically. 
Above mentioned exception is raised when trying to register a new user.
Without the event listener (trying to create a new tenant upon user registration) no such exception is raised.

### Steps to reproduce

[Shell script (link)](https://gist.github.com/kkbt/184b489e4e89cfc9587bd3d3962800c6)

### Expected behavior

Creating a new tenant (with database).

### Laravel version

8.77.1

### stancl/tenancy version

3.4.6

**Comment by stancl** [comment]
It's a bit hard to understand the code from the shell script. But either way, this is not a bug with the package and is related to your use.

A couple of things to note:
- Laravel cannot run cross-db queries or `Schema::create()` when inside a transaction
- I don't see the point of having tenants and teams linked 1:1 yet as separate entities. Why not make the teams your tenants?
- Jetstream is not supported in v3 anyway. There's information about this on our Discord

**Comment by kkbt** [comment]
Thank you for the quick and helpful answer.
Making the teams tenants would be the best way, however, I'm not experienced with this tenancy package to see how to implement this right away.
As of my knowledge, teams are provided by Jetstream only: https://jetstream.laravel.com/2.x/features/teams.html
So if v3 of Tenancy for Laravel doesn't support Jetstream, it also doesn't support teams (if I am not mistaken), which means it can't be used for this purpose (teams = tenants).
I found your explanation here: https://github.com/laravel/framework/pull/40165

```
Motivation

In v3 of Tenancy for Laravel, one of the biggest limitations our users deal with is that controllers which use constructor DI are incompatible with multi-tenancy.

This means that Fortify, Jetstream, and many other packages cannot be used out of the box.

```

**Comment by kkbt** [comment]
See also: https://github.com/laravel/framework/pull/40165#issuecomment-1003575193
