### ISSUE TITLE
Mysql 5.6 does not support JSON fields

### ISSUE THREAD

**Issue by liuyong888** [stancl/tenancy#781]
### Bug description

Database migration file error, Mysql 5.6 does not support JSON fields

### Steps to reproduce

php artisan migrate

### Expected behavior

I do not understand the function of the "data" field in the file '2019_09_15_000010_create_tenantS_table' .
Is he required, and if so, must he be of json type?

### Laravel version

8.57.0

### stancl/tenancy version

3.5.1

**Comment by liuyong888** [comment]
@stancl

**Comment by stancl** [comment]
Not a bug. Use a supported DB engine.

The data column is for storing internal metadata. You could create columns for those, but if we add any custom later on, your app wouldn't work. So it's used as the column where *anything that doesn't have a dedicated column* goes.
