### ISSUE TITLE
Filesystem related issues

### ISSUE THREAD

**Issue by chieft3ch** [stancl/tenancy#785]
### Bug description

Storing a file in the app works fine:
`tap($this->path, function () use ($path) {
            $this->package->forceFill([
                'path' => $path->storePublicly(
                    'packages', ['disk' => 'public']
                ),
            ])->save();
        });`
        
The image gets stored in the storage/$tenant/app/public/packages folder.

My issues are when I am trying to retrieve/display the file. The tenant_asset() returns app.com/tenancy/assets/packages/imageid.jpg

From my understanding of the filesystem bootstrapper this should link it to the public URL of that tenant?

### Steps to reproduce

Store a file how you would normally do in laravel `Storage::disk('public')->put($image);`

Try and retrieve the file in the frontend `<img src="{{  tenant_asset($package->path) }}" />`

(A short sbs but thats all their is to it really).

I have tried both asset() and tenant_asset() both with no luck

### Expected behavior

Expected to return the public logo/image when requesting from tenant_asset

### Laravel version

8.12

### stancl/tenancy version

3.4

**Comment by stancl** [comment]
> My issues are when I am trying to retrieve/display the file. The tenant_asset() returns app.com/tenancy/assets/packages/imageid.jpg

And what's the problem with that?

**Comment by chieft3ch** [comment]
The Image doesn't load. I know we can't do a storage link but no image is returned on that path. Apologies I wasn't clear on that.
<img width="296" alt="Screenshot 2022-01-20 at 11 27 15" src="https://user-images.githubusercontent.com/38211102/150330286-f8bd98cf-a095-467f-b96e-cc3d30f359a4.png">

**Comment by stancl** [comment]
If you visit /tenancy/assets/packages/2MBfl1h.....jpg you should see the file correctly. This seems like a usage issue, I recommend re-reading the filesystem docs
