### ISSUE TITLE
form request

### ISSUE THREAD

**Issue by david34corbalan** [stancl/tenancy#789]
### Bug description

hello, I'm trying to make an api, and I have the user routes, an edit and a show, the edit has a form request as validation, that if all the data to be validated does not arrive, it returns the data of the user show in you see the error 422
route/tenant.php
![image](https://user-images.githubusercontent.com/43279485/151389488-06e83aa4-bece-4b95-8c6f-1286aef820dc.png)

controller
![image](https://user-images.githubusercontent.com/43279485/151389646-ee965d19-7d82-421d-aaa2-3419a0d8fa12.png)

postman
route show user:
![image](https://user-images.githubusercontent.com/43279485/151389893-d7875d7e-4b1e-4d06-ba30-4e36fa1e48a8.png)

route, edit user without name
![image](https://user-images.githubusercontent.com/43279485/151389997-6d6433dd-6c31-4774-a650-206d350f962a.png)

route, edit user with name
![image](https://user-images.githubusercontent.com/43279485/151393326-4466e883-e136-4447-bcc8-b45ef0d27899.png)

form request:
![image](https://user-images.githubusercontent.com/43279485/151390081-3c4a0d71-565e-4416-a6ad-171ce14de788.png)

within the web prefix, form requests work fine. it only happens in the api prefix

### Steps to reproduce

create 2 api routes, one get and one put.

create 1 controller, with 2 functions for the above routes

create 1 form request for the put function

### Expected behavior

the expected thing is that it returns the error 422 with the validations that failed

### Laravel version

"^8.40"

### stancl/tenancy version

"^3.5.1"

**Comment by stancl** [comment]
Seems like a support question. Also, review your controller. It's likely the constructor injection you're using.

**Comment by david34corbalan** [comment]
I deleted the injection and it does not solve the problem
