### ISSUE TITLE
`tenant()->delete()` bug

### ISSUE THREAD

**Issue by plakhin** [stancl/tenancy#791]
### Bug description

As mentioned in https://github.com/archtechx/tenancy/issues/774#issuecomment-1018134788, `tenant()->delete()` hangs.
I'm using multi-database tenancy

Digging a bit deeper  I found that the problem is https://github.com/archtechx/tenancy/blob/f08e33afd80d14d99eb0595261cb100f981d4b52/src/Jobs/DeleteDatabase.php#L32

Dump of `$this->tenant->database()->manager()`:
```
Stancl\Tenancy\TenantDatabaseManagers\MySQLDatabaseManager {#3368
  #connection: "tenant_template"
}
```

Further:
https://github.com/archtechx/tenancy/blob/f08e33afd80d14d99eb0595261cb100f981d4b52/src/TenantDatabaseManagers/MySQLDatabaseManager.php#L43 hangs.

the statement is `` DROP DATABASE `laravel_tenant__acme` ``

dump of `$this->database()`:

```
Illuminate\Database\MySqlConnection^ {#10647
  #pdo: Closure()^ {#10583
    class: "Illuminate\Database\Connectors\ConnectionFactory"
    this: Illuminate\Database\Connectors\ConnectionFactory {#6398 …}
    use: {
      $config: array:15 [
        "driver" => "mysql"
        "host" => "127.0.0.1"
        "port" => "3307"
        "database" => null
        "username" => "root"
        "password" => "password"
        "unix_socket" => ""
        "charset" => "utf8mb4"
        "collation" => "utf8mb4_unicode_ci"
        "prefix" => ""
        "prefix_indexes" => true
        "strict" => true
        "engine" => null
        "options" => []
        "name" => "tenant_template"
      ]
    }
    file: "./vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php"
    line: "179 to 191"
  }
  ...
```  

I don't see anything wrong here.

`$this->database()->statement('show databases;')` returns `true`

If I connect to the DB with MySQL client and execute `` DROP DATABASE `laravel_tenant__acme` `` it works fine.

Tried ``dd($this->database()->statement("DROP DATABASE `{$tenant->database()->getName()}`"));`` - it hangs.

@stancl can you help please?

### Steps to reproduce

1. install `stancl/tenancy` package, configure for multi-database, use `tenant_template` as a template for tenant DB connection (when using 'tenant' as a name of template connection, all works fine with v3.4.6)
2. create tenant
3. exec `tenant()->delete()`

### Expected behavior

`tenant()->delete()` should delete tenant and drop it's database.

### Laravel version

8.8.0

### stancl/tenancy version

3.5.1 and 3.4.6

**Comment by stancl** [comment]
Was this introduced in 3.4.6? Try this on an earlier version to test that

**Comment by plakhin** [comment]
Tried 3.4.2-3.4.6, doesn't work. Also tried different tenant template connection names, works only with `tenant` on 3.4.2-3.4.6.
Previous versions are not compatible with Laravel 8.

**Comment by stancl** [comment]
What does your template connection look like? And do you have any database config inside the tenant data? As in `tenancy_db_*`

**Comment by plakhin** [comment]
```php
//config/database.php

        //Tenant
         'tenant_template' => [
            'driver'         => 'mysql',
            'url'            => env('DATABASE_URL'),
            'host'           => env('DB_HOST', '127.0.0.1'),
            'port'           => env('DB_PORT', '3306'),
            'database'       => null,
            'username'       => env('DB_USERNAME', 'forge'),
            'password'       => env('DB_PASSWORD', ''),
            'unix_socket'    => env('DB_SOCKET', ''),
            'charset'        => 'utf8mb4',
            'collation'      => 'utf8mb4_unicode_ci',
            'prefix'         => '',
            'prefix_indexes' => true,
            'strict'         => true,
            'engine'         => null,
            'options'        => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
```

**Comment by plakhin** [comment]
>  And do you have any database config inside the tenant data? As in tenancy_db_*

What do you mean by this?

**Comment by stancl** [comment]
If there are `tenancy_db_*` properties on the tenants

**Comment by plakhin** [comment]
If you mean `data` column of `tenants` table, there's only DB name there:
```json
{
	"updated_at": "2022-02-05 04:47:23",
	"tenancy_db_name": "laravel_tenant__acme",
	"maintenance_mode": null
}
```

And `tenancy_db_` is not found anywhere in the code.

PS. sorry for delayed answers, I had Covid and recovery process is very slow, so almost not working these days.

**Comment by plakhin** [comment]
I've tried to connect to DB with MySQL client. While `tenant()->delete()` is being executed (forever) I can see the `laravel_tenant__acme` database in `SHOW DATABASES;` output list, however I can't `USE Laravel_tenanc__acme;` it also hangs. Once I press `ctrl+c` to cancel `tenant()->delete()` in a tinker session, the database is deleted and is not in the `SHOW DATABASES;` list anymore.

**Comment by stancl** [comment]
That sounds like a strange configuration issue. I don't know why `tenant()->delete()` would run forever, or why a DB would hang. If more people report this with some specific context I'll reopen

**Comment by plakhin** [comment]
But this issue doesn't arise when `tenant` is being used as a name of tenant template connection...

**Comment by plakhin** [comment]
Tried to update to 3.5.2, still experience the issue.

**Comment by Andrei-Dr** [comment]
> I've tried to connect to DB with MySQL client. While `tenant()->delete()` is being executed (forever) I can see the `laravel_tenant__acme` database in `SHOW DATABASES;` output list, however I can't `USE Laravel_tenanc__acme;` it also hangs. Once I press `ctrl+c` to cancel `tenant()->delete()` in a tinker session, the database is deleted and is not in the `SHOW DATABASES;` list anymore.

Sounds like you're racing a transactional lock on the db, which gets lifted as you ctrl+c

**Comment by plakhin** [comment]
> Sounds like you're racing a transactional lock on the db, which gets lifted as you ctrl+c

Indeed! The problem is a transaction that never being committed or rolled back. We have an issue in one of our test suites that is quite tricky. However, that didn't arise before v3.5.

@Andrei-Dr Thank you very much!

**Comment by plakhin** [comment]
@stancl short simplified summary:
 I've fixed the bug by adding one line in `TestCase.php`:

```diff
public static function tearDownAfterClass(): void
{
+    app()->make('db')->connection()->disconnect();
    tenant()->delete();
}
```

There were no issue before v3.5, so I guess Central connection lifecycle was changed somehow and this is the reason. May be you'll find this report useful.
