### ISSUE TITLE
Docker image is failing to build

### ISSUE THREAD

**Issue by rawmarius** [stancl/tenancy#794]
### Bug description

After cloning the 3.x branch and running `docker-compose up -d` (or build) then the following error appears:
`failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql     && docker-php-ext-install -j$(nproc) gd pdo pdo_mysql pdo_pgsql pdo_sqlite pgsql zip gmp bcmath pcntl ldap sysvmsg exif     && pecl install redis-5.3.2     && docker-php-ext-enable redis     && pecl install pcov     && docker-php-ext-enable pcov     && echo "pcov.enabled = 1" > /usr/local/etc/php/conf.d/pcov.ini]: exit code: 1`

### Steps to reproduce

Clone 3.x repo (currently at 3.5.1) and then run `docker-compose up -d`

### Expected behavior

That the docker image builds correctly and then I'd like to be able to run the tests

### Laravel version

"illuminate/support": "^6.0|^7.0|^8.0"

### stancl/tenancy version

3.5.1

**Comment by stancl** [comment]
Did you manage to fix this somehow?

**Comment by rawmarius** [comment]
No I didn't try much. But I did find something great I even implemented on my projects at work (also because I needed to upgrade to PHP8.1 and Laravel 9) : https://kool.dev
They have a repo of all [their php images](https://github.com/kool-dev/docker-php). I think that could be used here. 
And for the db's then the official database images could be used. That would help a lot for the development and testing process. If you're open to the idea I could try making it run with an updated docker-compose.yml file.

**Comment by stancl** [comment]
I see. I first thought it's related to pcov, but after experimenting it seems like this fixed the issue for me: https://github.com/archtechx/tenancy/commit/5026f54a6d4482226951d3a8196218ea41434db4#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557

So I just changed phpredis `5.3.2` to `5.3.7`
