### ISSUE TITLE
Cannot install on laravel 9

### ISSUE THREAD

**Issue by Steven73041** [stancl/tenancy#801]
### Bug description

Hello, I tried on fresh laravel 9 installation to install the package but i get error for illuminate/support.

My composer.json requires
`
    "require": {
        "php": "^8.0",
        "fruitcake/laravel-cors": "^2.0.5",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^9.0.2",
        "laravel/sanctum": "^2.14",
        "laravel/tinker": "^2.7"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/breeze": "^1.8",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
`

### Steps to reproduce

1. composer create-project laravel/laravel test
2. cd test
3. php artisan migrate
4. composer require stancl/tenancy

### Expected behavior

Should install it as long as illuminate/support is in laravel framework.

### Laravel version

9.0.2

### stancl/tenancy version

3.5.1

**Comment by stancl** [comment]
See the pinned issue
