### ISSUE TITLE
Rendering Exceptions Laravel 8.x

### ISSUE THREAD

**Issue by jigzstar** [stancl/tenancy#805]
### Bug description

        $this->renderable(function (\Stancl\Tenancy\Exceptions\NotASubdomainException $e, $request) {
            return response()->view('errors.505', ['message' => 'URL is not a subdomain.'], 500);
        });

### Steps to reproduce

1. Try to go the central domain
2. Get Default 500 error page

### Expected behavior

1. Supposed to goto Custom Error view

### Laravel version

8.69

### stancl/tenancy version

3.4.5

**Comment by stancl** [comment]
Can you fill out the issue template in an actually useful way? There's nothing I can do with this except close it.

**Comment by jigzstar** [comment]
My apologies.

I think I put this in the wrong repo, I am using the SaaS Bolierplate, but can't seem to get the Exception handling to work, even when creating a new tenant.
