### ISSUE TITLE
Using central connection for creating tenant databases

### ISSUE THREAD

**Issue by F-Georg** [stancl/tenancy#806]
#### Description
I have two database connections in my project.
The database user of the "admin_connection" has all the MySQL privileges, like among others Create.
I use this connection in config/tenancy.php as 'central_connection'.
The database user of the "template_connection" only has the Select, Insert, Update and Delete MySQL privileges.
I use this connection in config/tenancy.php as 'template_tenant_connection'.

If I insert a tenant into the tenant table, for example with the tenant name "example_name", I get this error:
`SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'db_user_of_template_connection'@'localhost' to database 'example_name' (SQL: CREATE DATABASE `example_name` CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci``

I looked at the code and when creating a tenant database, in the handle function of CreateDatabase.php the following is executed:
`$this->tenant->database()->manager()->createDatabase($this->tenant);`
If I understood it right, in DatabaseConfig.php in the function manager() a database connection is selected through the function getTemplateConnectionName() in DatabaseConfig.php.
The function getTemplateConnectionName() returns the internal database connection of the tenant.
If there is no internal database connection of the tenant the template_tenant_connection is returned and if there is no template_tenant_connection either, the central_connection is returned.

In my case there is no internal database connection of the tenant.
Therefore the template_tenant_connection is used for creating the tenant database.
However in my case the template_tenant_connection doesn't have the necessary privilege for creating databases and I would like to keep it that way.

Is there a way to create a tenant database, if one wants to grant the privilege for creating databases only to the db user of the central_connection, but not to the db user of the internal database connection and not to the db user of the template_tenant_connection?

Would it be possible to change the createDatabase function so that by default the central_connection is used for creating tenant databases?

#### Why this should be added
This would make it possible to have tenant database connections with db users, that don't have the privilege for creating databases.

**Comment by stancl** [comment]
> If I insert a tenant into the tenant table, for example with the tenant name "example_name", I get this error

The tenants table is in the **central** DB, not the tenant DB. The central DB is meant to be managed by the main admin.

**Comment by stancl** [comment]
By inserting a tenant into the tenant table, did you mean creating a tenant using `Tenant::create()`, or inserting the record?

**Comment by F-Georg** [comment]
> By inserting a tenant into the tenant table, did you mean creating a tenant using `Tenant::create()`, or inserting the record?

@stancl:
Thank you very much for your answer!

I used `Tenant::firstOrCreate(['id' =>  'example_name']);` for creating the tenant.

> > If I insert a tenant into the tenant table, for example with the tenant name "example_name", I get this error
> 
> The tenants table is in the **central** DB, not the tenant DB. The central DB is meant to be managed by the main admin.

Yes, that's true.
And the insert into the tenants table in the central DB worked fine in my project.
However if I understood it right then in TenancyServiceProvider.php in the events() function the Jobs\CreateDatabase::class is executed as a reaction to the Events\TenantCreated::class.
And this creation of the tenant database is where I got the error message "Access denied", because my template_connection doesn't have the necessary privilege for creating databases.

**Comment by stancl** [comment]
Right, in that case I'll look into the template connection logic. I remember similar issues being brought up in the past.

> And the insert into the tenants table in the central DB worked fine in my project.

I was asking about that because inserting a record will have on effect on the tenant's DB. The whole logic needs to take place in PHP for it to be created.

Also, to get a bit more context:
> And this creation of the tenant database is where I got the error message "Access denied", because my template_connection doesn't have the necessary privilege for creating databases.

What privileges does the connection have? And what's the reason for it not having the privilege for creating databases?

**Comment by F-Georg** [comment]
> Right, in that case I'll look into the template connection logic. I remember similar issues being brought up in the past.

Great! Thank you very much!



> Also, to get a bit more context:
> 
> > And this creation of the tenant database is where I got the error message "Access denied", because my template_connection doesn't have the necessary privilege for creating databases.
> 
> What privileges does the connection have? And what's the reason for it not having the privilege for creating databases?

My template_connection only has the MySQL privileges Select, Insert, Update and Delete.

My preferred setting would be to have one connection with all privileges for when I need to make structural changes to databases and one db connection, which is used for user activities on the homepage, which can only Select, Insert, Update and Delete, but can not make structural changes to databases.
By this means I would like to minimize the risk that the database is compromised/changed in unwanted ways by users or other developers.

**Comment by stancl** [comment]
Are you using the permission controlled MySQL DB manager?

**Comment by F-Georg** [comment]
> Are you using the permission controlled MySQL DB manager?

@stancl:
Sorry for my late reply!
In the moment I'm using the mysql Command-line Client for managing the privileges of my connections.

**Comment by stancl** [comment]
If you used the permission controlled DB manager, you'd have one connection that manages the DB & user creation, and then each tenant would have their own DB user that only has access to their database.

Would that not be sufficient?

**Comment by F-Georg** [comment]
> If you used the permission controlled DB manager, you'd have one connection that manages the DB & user creation, and then each tenant would have their own DB user that only has access to their database.
> 
> Would that not be sufficient?

Many thanks for the tip!
That would be great to do so and that would absolutely fulfill my purposes.

May I ask what would be the best way to go about this?
I've been looking at the permission controlled DB manager.
If I understood correctly, the permissionControlled DB manager allows you to set the tenancy_db_connection when creating a tenant, which is then used to construct this tenant's database connection.
How could one go about setting the connection that is used for DB & user creation with the permission controlled DB manager?

**Comment by stancl** [comment]
Did you see the docs for it?

**Comment by F-Georg** [comment]
> Did you see the docs for it?

@stancl:
Yes, I saw the docs for it.
I'm not sure, if maybe I missed something.
However I only found information there about how to set the tenancy_db_connection, which is used to construct the tenant's database connection.

**Comment by stancl** [comment]
I'm asking because I don't understand why the `tenancy_db_connection` is important. You've mentioned it a few times, but the permission controlled DB manager can just work out of the box. You don't need any template connection changes.

You wrote:
> My template_connection only has the MySQL privileges Select, Insert, Update and Delete.
> My preferred setting would be to have one connection with all privileges for when I need to make structural changes to databases and one db connection, which is used for user activities on the homepage, which can only Select, Insert, > Update and Delete, but can not make structural changes to databases.
By this means I would like to minimize the risk that the database is compromised/changed in unwanted ways by users or other developers.

To do this, you don't need to create a separate connection and set it as the template. You only need the central connection **with permission to create databases and users** and then each tenant will have its own user with access limited to his database.

So I'm not sure what the relation to the template connection is. I may be missing something though. Do you want it to be different from the central connection in any way?

**Comment by F-Georg** [comment]
> I'm asking because I don't understand why the `tenancy_db_connection` is important. You've mentioned it a few times, but the permission controlled DB manager can just work out of the box. You don't need any template connection changes.
> 
> You wrote:
> 
> > My template_connection only has the MySQL privileges Select, Insert, Update and Delete.
> > My preferred setting would be to have one connection with all privileges for when I need to make structural changes to databases and one db connection, which is used for user activities on the homepage, which can only Select, Insert, > Update and Delete, but can not make structural changes to databases.
> > By this means I would like to minimize the risk that the database is compromised/changed in unwanted ways by users or other developers.
> 
> To do this, you don't need to create a separate connection and set it as the template. You only need the central connection **with permission to create databases and users** and then each tenant will have its own user with access limited to his database.
> 
> So I'm not sure what the relation to the template connection is. I may be missing something though. Do you want it to be different from the central connection in any way?

@stancl:
Sorry! 
I just realized that I had overlooked something regarding the permission controlled DB manager.
I was looking for the permission controlled DB manager in my project, when you wrote me about it, and I don't know why, but I had overlooked the place in tenancy.php, where the permission controlled DB manager is included and where its functionality is described.
I had therefore not fully understood its functionality before.
But now I have understood its function.
May I just briefly ask about the procedure with the permission controlled DB manager?:
I saw that the permission controlled DB manager is located in the vendor directory.
Would one change the grants in PermissionControlledMySQLDatabaseManager.php or would these changes be overwritten when doing a composer update?
Or would one otherwise create a customized version of the permission controlled DB manager with customized grants in the project and include it in tenancy.php?

**Comment by stancl** [comment]
> Would one change the grants in PermissionControlledMySQLDatabaseManager.php or would these changes be overwritten when doing a composer update?

The changes would be overwritten.

> Or would one otherwise create a customized version of the permission controlled DB manager with customized grants in the project and include it in tenancy.php?

What do you need to customize exactly?

**Comment by F-Georg** [comment]
> > Would one change the grants in PermissionControlledMySQLDatabaseManager.php or would these changes be overwritten when doing a composer update?
> 
> The changes would be overwritten.
> 
> > Or would one otherwise create a customized version of the permission controlled DB manager with customized grants in the project and include it in tenancy.php?
> 
> What do you need to customize exactly?

I wanted to customize the grants property of the permission controlled DB manager.

If I understood it right in the docs in tenancy.php, one can change the grants given to the db user of each tenant by customizing the grants property of the permission controlled DB manager.

By default the grants property contains different grants like among others "create" or "drop".

My preferred setting would be that the db user of each tenant is only granted with the grants "select", "insert", "update" and "delete".
So I would like to ask, if it would be possible for me to customize the grants property so that it only contains the select, insert, update and delete grants and, if yes, what would be the best way to go about this.

**Comment by stancl** [comment]
Ah. In that case, no this is not supported currently.

You can change the grants using `PermissionControlledMySQLDatabaseManager::$grants = ['your own grants]`, but then migrations won't work. The package uses the tenant connection for managing the schema inside the tenant's DB.

If you wanted to manage the schema using the central connection, you'd need completely custom logic for this and I can't really advise how you'd go about implementing that at this moment.

My recommendation is to just use the existing permission controlled MySQL DB manager. The users don't have access to other tenant databases or the central database, they simply manage their own database — including the schema.

**Comment by F-Georg** [comment]
> Ah. In that case, no this is not supported currently.
> 
> You can change the grants using `PermissionControlledMySQLDatabaseManager::$grants = ['your own grants]`, but then migrations won't work. The package uses the tenant connection for managing the schema inside the tenant's DB.
> 
> If you wanted to manage the schema using the central connection, you'd need completely custom logic for this and I can't really advise how you'd go about implementing that at this moment.
> 
> My recommendation is to just use the existing permission controlled MySQL DB manager. The users don't have access to other tenant databases or the central database, they simply manage their own database — including the schema.

@stancl:  
Many thanks for the information!
And thank you very much for taking the time to answer my questions!
I really appreciate it!
I think it's great that users don't have access to other databases and will therefore use the permission controlled MySQL DB manager.
