### ISSUE TITLE
Database connection [tenant] not configured on 3.5.1

### ISSUE THREAD

**Issue by Steven73041** [stancl/tenancy#808]
### Bug description

Hello, We updated from 3.4.4 to 3.5.1 and we have the following strange behaviour.

While we can return something from tenant db, we try to access the main database outside of closure $tenant->run and we get error "Database connection [tenant] not configured.

Nothing changed in code.
https://www.loom.com/share/3768edf109c44807b25e5f983105f7b6

### Steps to reproduce

`$skin = Skin::find(1);
$player = $skin->run(function () use ($request, $skinSettings, $skin) {
 return Player::find(1);
});
$player->country = Country::find($player->country_id);
`

Whenever i try to read or return the $player outside closure, i get error. I tried something like:

`$skin = Skin::find(1);
$player = $skin->run(function () use ($request, $skinSettings, $skin) {
 return Player::find(1);
});
Log::info($player);
$player->country = Country::find($player->country_id);`
Failed, cannot even pass the Log.

`$skin = Skin::find(1);
$player = $skin->run(function () use ($request, $skinSettings, $skin) {
 return Player::find(1);
});
tenancy()->initialize($skin);
Log::info($player);
$player->country = Country::find($player->country_id);`
Worked! It wrote to laravel.log but I cannot get country from main database, i must use tenancy()->central();

So without tenancy()->initialize($skin); i cannot access a model got from tenant.
If i do that, I have to use tenancy central to run on main database which wasn't like it before.

### Expected behavior

So without tenancy()->initialize($skin); i cannot access a model got from tenant.
If i do that, I have to use tenancy central to run on main database which wasn't like it before.

### Laravel version

8

### stancl/tenancy version

3.5.1

**Comment by stancl** [comment]
The issue is likely that the tenant's model is being used *after* the tenant connection is removed. Even calling `toArray()` interacts with the model's (missing) connection

**Comment by Steven73041** [comment]
Even logging it to laravel.log. Is there a fix for it? v3.4.6 is working but we need v3.5+ because we want to stop passing model ids from job to job and pass whole tenant's model without need to query them manually again and again.
![image](https://user-images.githubusercontent.com/44755563/154663334-acc1f11c-48e6-4808-97e5-f099bc51d736.png)

**Comment by stancl** [comment]
In 3.5 we fixed how connections are handled. Keeping an open `tenant` connection when the app is not in the tenant context is not how the package intends to work currently.

You should do everything tenant-related inside the tenant context. And only return the actual data (not models) from `$tenant->run()`.

I'll also be trying to add this https://github.com/laravel/framework/pull/40515 to the Laravel core, which should partially fix the issue for use cases like `->toArray()`. But we won't be keeping the entire connection around in the wrong context.

**Comment by Steven73041** [comment]
So before 3.5 we had opened connection that's why we could use the model. Now we can't use it. 
Can't we use it with the attached properties and relationships? 
I mean that after Player::with('currency')->find(1); We can have a model as player and currency property but out of tenant context we couldn't get player's country relationship because we didn't query it inside tenant. I think after changing this logic, a lot of code should be re-written to follow tenancy()->central and returning std classes or dto from tenant context. We will never be able to get a model outside of tenant to use in jobs. We will never be able to have a default the central connection and return data from tenancy context as we used to.
If i understand wrong please correct me!

**Comment by stancl** [comment]
If you're querying the tenant and central context at once, with models in different contexts, why not enforce the connection on the models via traits? If I understood the question correctly

**Comment by Steven73041** [comment]
Well yes, in controller method we query inside tenant and outside. Some relationships are out of tenant's db. Like general models currency or country. These are ok by the time we use tenancy()->central() to get them inside model method. Problem in 3.5 is that we cannot access the model var we got from tenant with whatever data has on it. I don't know if someone else did the migration and what type of changes they did. We try to avoid refactoring whole app which works like the loom.

**Comment by stancl** [comment]
I still don't really understand the problem you have. Could you show some actual code?

**Comment by Steven73041** [comment]
We want to have the passed model outside of tenant closure, use it's properties and get data out of tenancy, Maybe we want to pass whole object to a job without the context of tenancy because will be executed with main-central database. What can we change so the code in loom video will work in latest varsion as well? As less changes as possible.
Code: https://pastebin.com/q2EMkPt1
Model: https://pastebin.com/yP8LzaNz
Sorry for formatting, pastebin killed it.
Code will be refactored and be shorten for readability but it is a working code in 3.4.4 and not in 3.5.1

**Comment by stancl** [comment]
> Maybe we want to pass whole object to a job without the context of tenancy because will be executed with main-central database

You shouldn't be doing this. The model is a tenant model. If you're not in the context of the tenant who owns that model, you should use parts of the data. Not whole model instances. By design, it doesn't really make sense to have "dead" models. You can't use it to write data, so the variable should make it clear — by being e.g. an array rather than a model instance.
