### ISSUE TITLE
Aggregated data from all tenants from central application

### ISSUE THREAD

**Issue by RishabSwift** [stancl/tenancy#809]
#### Description
I'm not sure if this feature exists or there's an existing approach to go about this, but it would be great to be able to get all data from all tenants from the central application for reporting purposes.

A simple dumbed down example would be seeing all posts across all tenants, their comments, and tags in the central application, along with what subdomain they belong to.

#### Why this should be added
For reporting purposes, gathering statistics, and more.

**Comment by stancl** [comment]
You can use `tenancy()->all()->runForEach()` for this. How you aggregate the result is up to you — the package can't really offer a single way to do that

**Comment by mcadet** [comment]
@RishabSwift did you see https://tenancyforlaravel.com/docs/v3/synced-resources-between-tenants?

**Comment by stancl** [comment]
Syncing resources and aggregating data are different things. I think he wants the former here.

Either way, this is implemented so I'm closing

**Comment by fdabek1** [comment]
> `tenancy()->all()->runForEach()`

When I run this it says that the `all()` method does not exist.  And looking at the `Tenancy.php` class I do not see it in there.  Am I doing this incorrectly?

Edit: The correct way is `Tenant::all()`, but having this helper method on `tenancy()` would be nice.

**Comment by stancl** [comment]
Ah sorry, you're right. `tenancy()->all()` was the syntax in v2, now we removed the method because it's easy to do that with Eloquent 👍🏻
