### ISSUE TITLE
Tenant user can't login

### ISSUE THREAD

**Issue by sham7890** [stancl/tenancy#810]
### Bug description

If the user is not in the central database then the tenant users can't log in to their database.

### Steps to reproduce

In the central database, I can create a user and log in using the main domain e.g. laravel.test without any error. But, when I create a user in the tenant database e.g. user1 and log in with that user in sub.laravel.test then I can't log in and I get Too many loops error. If I duplicate the same user from the tenant database to the central database then I can log in to the tenant database in sub.laravel.test.

### Expected behavior

I want that the tenant user must log in to their database if it's user is in tenant database.

### Laravel version

8

### stancl/tenancy version

3.5

**Comment by stancl** [comment]
That's related to your app, not the package

**Comment by sham7890** [comment]
Any idea how to fix it because I checked and everything is fine from my view.

**Comment by solomon-ochepa** [comment]
I'm having the same issue please. How do we fix it?
