### ISSUE TITLE
db:wipe does not wipe views

### ISSUE THREAD

**Issue by masiorama** [stancl/tenancy#811]
#### Description
It would be nice to be able to wipe views too of a tenant db, along with the real tables.
Right now the package takes care only of tables.

It should be a trivial job, since it can be accomplished passing a parameter (`'--drop-views' => true`) to db:wipe on 

`/stancl/tenancy/src/Commands/MigrateFresh.php`
#### Why this should be added
I think it can help in cases when you work with views, and it has no side effects in case no views are not present.

I can create a pull request once @stancl 's feedback is positive about that.

**Comment by stancl** [comment]
What's the issue with views in specific? I don't see the relation between tenancy and views

**Comment by masiorama** [comment]
Sorry, I didn't explain well enough.
I encountered a problem when using a tenancy command from shell.
In particular, if you have one or more mysql views in your tenant db, if you trigger via shell

`php artisan tenants:migrate-fresh`

You can notice that those views are not removed when purging the db.

Editing as I suggested in the opening of the thread I can remove the views too along with the tables.

Hope I explained myself better this time.

**Comment by stancl** [comment]
Does `migrate:fresh` drop views normally?

**Comment by masiorama** [comment]
Nope, you have to add `'--drop-views'`, but, tecnically, without that the db is not "wiped" as the command `db:wipe` suggests...

It could be solved mimicking what migrate:fresh does passing the parameter above, which `tenants:migrate-fresh` does not.
What do you think?

**Comment by stancl** [comment]
I don't think `migrate:fresh` has `--drop-views`?

**Comment by masiorama** [comment]
From what I can see here it does.
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Console/Migrations/FreshCommand.php
Or maybe I misunderstood your comment.

**Comment by stancl** [comment]
Ah right, I was looking at Refresh.

In that case, yes, we could support this. Either by changing the `tenants:migrate-fresh` command to extend the `migrate:fresh` command, or by adding the option to the existing command.

**Comment by masiorama** [comment]
Nice, tell me if I can help with a pull and I will handle it in the next few days. Thanks!

**Comment by stancl** [comment]
Yeah, a PR would be appreciated :)

**Comment by masiorama** [comment]
Hello @stancl, I forked the repo and made my modification. Before I make a PR here I would like to know if you agree with it. Thanks!

**Comment by stancl** [comment]
Commented there 👍🏻

**Comment by stancl** [comment]
Implemented 👍🏻
