### ISSUE TITLE
Central Cache without specific tenant id tags

### ISSUE THREAD

**Issue by marksitko** [stancl/tenancy#816]
#### Description
A global cache accessor to store once central values which are accessible from each tenant without specific tenant id keys. 

#### Why this should be added
This could be useful if you want to store something once in the cache driver and share it potentially with all tenants.

#### Pseudo Solution - not tested extensively
- Extend the Cache Facade methods with central Variants e.g. `centralPut`, `centralGet` 
- Add Logic to `Stancl\Tenancy\CacheManager` to check if `method` starts with `central`, replace `central` from method name and store to cache via `$this->store()` <- without calling `tags()`

**Comment by stancl** [comment]
Not sure if it's documented but I think you can use the GlobalCache for this? https://github.com/archtechx/tenancy/blob/3.x/tests/GlobalCacheTest.php

**Comment by marksitko** [comment]
Oh didn't see that. I searched but doesn't find it.

But yes, that's exactly what i'm thinking of. Great Thank you for your help, quick reply and this great package  🙏
