### ISSUE TITLE
[3.x] Requirements for Laravel 9.x

### ISSUE THREAD

**Issue by suleymanozev** [stancl/tenancy#818]
#### Description
What are the requirements for the package to be ready for Laravel 9.x? I'm sorry issues are too complicated. Which issues need to be resolved for it to be ready for laravel 9.x.

#### Why this should be added
Question

**Comment by Grummfy** [comment]
see
* https://github.com/archtechx/tenancy/pull/802
* https://github.com/archtechx/tenancy/issues/654

**Comment by suleymanozev** [comment]
#802 I've tested locally. All tests passed. What are you waiting for?

**Comment by suleymanozev** [comment]
@stancl @Grummfy

**Comment by stancl** [comment]
See what I wrote in the linked issues
