### ISSUE TITLE
Add interface to allow more

### ISSUE THREAD

**Issue by Grummfy** [stancl/tenancy#820]
Today the package is nice and solve the problem quiet nicely. But there is some shortcut present, with some hardcoding that force to use the package in a certain way.

Some extra work to add some interface and service layer could open some door, like having the tenant detail (configuration, domain, whatever) coming from an API (or a filesystem or whatever data system).

Just by using a repository service that give you the tenant and domain, even if it seems useless open everything

If you choose to droop this idea, at least be explicit about the requirement because it's a big limitation.

### What's my usage?

I have some services that communicate together. Each service rely on a specific tenant. Some service inside a specific tenant have specific configuration. But The fact that it's this or this tenant is declared inside a service that expose it through an API ... It could also came from a filesystem (like we start with). So for me the fact that I need an extra schema just for the tenant is useless, but all the other mechanism exposed in this package are totally interesting so it's bad that I need to override several class just to implement a version without database...

thanks

**Comment by stancl** [comment]
Do you mean that tenants themselves should be changed into a repository w/ an interface, instead of requiring Eloquent?

**Comment by Grummfy** [comment]
Not changed, just add interface that are what's required. So instead of assuming that Tenant Interface is an eloquent model just use the interface for itself.

So in my need, I will understand that I'm out of the normal way (aka using eloquent) I would probably require to implement a "repository" service that can return the tenant using domain, path, etc. But also some "model" that implement the tenant Interface.

So this package would provide an implementation using eloquent and other people can implement whatever they want.


For example, in the DomainResolver, it could be something like this
Instead of 
```
    public function resolveWithoutCache(...$args): Tenant
    {
        $domain = $args[0];

        /** @var Tenant|null $tenant */
        $tenant = config('tenancy.tenant_model')::query()
            ->whereHas('domains', function (Builder $query) use ($domain) {
                $query->where('domain', $domain);
            })
            ->with('domains')
            ->first();

        if ($tenant) {
            $this->setCurrentDomain($tenant, $domain);

            return $tenant;
        }

        throw new TenantCouldNotBeIdentifiedOnDomainException($args[0]);
    }
```
we would get this :
```
    public function resolveWithoutCache(...$args): Tenant
    {
        $domain = $args[0];
        $tenant = $this->repository->findTenantByDomain($domain);
        
        if ($tenant) {
            $this->setCurrentDomain($tenant, $domain);

            return $tenant;
        }

        throw new TenantCouldNotBeIdentifiedOnDomainException($args[0]);
    }

// and inside the repository
// ...
    public function findTenantByDomain(string $domain): Tenant
    {
        return config('tenancy.tenant_model')::query()
            ->whereHas('domains', function (Builder $query) use ($domain) {
                $query->where('domain', $domain);
            })
            ->with('domains')
            ->first();
    }

```

I understand that this suggestion could take time and could not worth it... It's why in this case I would just update the documentation and put a limitation about the limit of the package

**Comment by stancl** [comment]
> Not changed, just add interface that are what's required. So instead of assuming that Tenant Interface is an eloquent model just use the interface for itself.

Right. As I mentioned on Discord, we did this in v2 (with Redis & Eloquent storage drivers supported out of the box), and it eventually became extremely limiting.

We use a ton of Eloquent features in all of the peripheral logic (e.g. commands), which makes using an interface painful.

It's much better to find a way to make Eloquent work for you, e.g. by syncing the data somehow or by using an alternative driver (such as https://github.com/baopham/laravel-dynamodb).

**Comment by Grummfy** [comment]
Ok, like I say, not problem, but in this case, update the website or the documentation to make it more explicit that it's considered as mandatory or something similar.

**Comment by stancl** [comment]
I think this explains that models are used clearly enough: https://tenancyforlaravel.com/docs/v3/tenants

Thanks for the suggestion either way!
