### ISSUE TITLE
Quick guide errors

### ISSUE THREAD

**Issue by nezaboravi** [stancl/tenancy#821]
### Bug description

1) When following quick guide, and implementing:
`class Tenant extends BaseTenant implements TenantWithDatabase`  i am required to implement database() method and cant find any documentaitona about it.
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/1515172/157734893-f2b5c6d0-c97e-4ca0-8fd3-bc6064382896.png">

I have added this and after it i got created tenant:
```
 public function database(): DatabaseConfig
    {
        return new DatabaseConfig($this);
    }

```
2) Following quick guide further more `$tenancy->domains()->create(['domain' => 'wtf.localhost'])` i am getting error:
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/1515172/157734436-24eed42c-df0d-48bd-a1e4-daac6be8ebdc.png">

### Steps to reproduce

Follow quick guide and create everything as in guide.

### Expected behavior

Expecting to create a domain.

### Laravel version

9

### stancl/tenancy version

3.1.0

**Comment by stancl** [comment]
You didn't add the trait for domains
