### ISSUE TITLE
Unable to use database session driver

### ISSUE THREAD

**Issue by woganmay** [stancl/tenancy#824]
### Bug description

This may be related to the issue described in #702 . Given the following components:

* PHP 8.1.2 + PostgreSQL
* laravel/framework 9.5.1
* laravel/jetstream 2.6.8
* laravel/sanctum 2.14.2
* stancl/tenancy 3.5.2
* SESSION_DRIVER=database

I see some strange behavior: The session table within a tenant database populates correctly, but for some reason, I get an exception saying that the `sessions` relation does not exist. It's as if it's able to create the session, but not read it back afterwards.

### Steps to reproduce

1. Create a laravel/laravel project
2. composer-require stancl/tenancy
3. Follow the Quickstart guide at https://tenancyforlaravel.com/docs/v3/quickstart
4. Create a Tenant
5. Install Jetstream via the guide at https://jetstream.laravel.com/2.x/installation.html
6. Configure Jetstream and Fortify to use the InitializeTenancyByDomain and PreventAccessFromCentralDomains middleware
7. Try to open a tenant page

The session driver creates a new record in the tenant's database table, then somehow fails to read it, then crashes with an exception.

### Expected behavior

Seeing as it's able to create the session record in the database, it should have no problem reading it back, so I'd expect sessions to work normally.

### Laravel version

9.5.1

### stancl/tenancy version

3.5.2

**Comment by woganmay** [comment]
Just to illustrate my confusion! How was it able to write the record to the table, for the correct tenant, but then fail with that exception? I ended up digging all the way into the Connection classes, and determined that the tenant database connection config was not being applied correctly.

This is after setting Fortify to use the correct middleware, too.

![image](https://user-images.githubusercontent.com/225550/158470485-ef16c32f-7b99-4678-823d-bf11a91303f4.png)

**Comment by woganmay** [comment]
Did some more troubleshooting (dumping out every SELECT) - it looks like the InitializeTenancyByDomain middleware is doing what it's supposed to, but by the time the session driver tries to read from the database, it hasn't applied the new connection settings yet:

    local.INFO: [SELECT][database=laravel] select * from "tenants" where exists (select * from "domains" where "tenants"."id" = "domains"."tenant_id" and "domain" = ?) limit 1  
    local.INFO: [SELECT][database=laravel] select * from "domains" where "domains"."tenant_id" in (?)  
    local.INFO: [SELECT][database=laravel] SELECT datname FROM pg_database WHERE datname = 'tenant_cust-a'  
    local.INFO: [SELECT][database=laravel] select * from "sessions" where "id" = ? limit 1  
    local.ERROR: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "sessions" does not exist


For now we're forced to proceed the `file` driver. The solution on #702 pertains to getting Fortify to work, but oddly enough, once we're using `file` for sessions, Fortify works just fine. I'm not sure if either package updated since September 2021, but we had no trouble authenticating with Fortify to different tenants. So maybe #702 is not relevant?

**Comment by stancl** [comment]
By "on v3.5.2", do you mean that it worked in a previous version, or simply that this is the version you're using?

**Comment by woganmay** [comment]
@stancl I'm actually not sure right now (if it worked in a previous version) - I think Laravel 9 started defaulting to database sessions, my previous projects all use file-based sessions so I don't think we've triggered this issue before. Consider this as "this is the version we started using today".

**Comment by stancl** [comment]
Note that the file-based sessions are not recommended https://tenancyforlaravel.com/docs/v3/session-scoping/#storing-sessions-in-the-database

> The session table within a tenant database populates correctly, but for some reason, I get an exception saying that the sessions relation does not exist

This sounds like Fortify is using the central DB at that point in the lifecycle. Likely because it does some stuff prior to our route-level middleware being executed.

**Comment by hitoridev** [comment]
@woganmay did you found the solution for this? instead changing session driver to 'file'? I have same issue too..thanks for help..

**Comment by marcuschristiansen** [comment]
Has anyone tried storing the sessions in Redis DB? Would that solve the issue?

**Comment by thanhtoan1196** [comment]
> @woganmay did you found the solution for this? instead changing session driver to 'file'? I have same issue too..thanks for help..

anyone have any solution?

**Comment by stancl** [comment]
Should be fixed in v4

**Comment by ismaail** [comment]
Using **database** for session storage still gives this issue.

--- 

Workaround found [here](https://github.com/archtechx/tenancy/issues/702)

`bootstrap/app.php` register **TenancyServiceProvider** first.

```php
App\Providers\TenancyServiceProvider::class,
App\Providers\AppServiceProvider::class,
```

in `AppServiceProvider` file

```php
use Illuminate\Support\Facades\Request;
use Stancl\Tenancy\Database\Models\Domain;
use Stancl\Tenancy\Resolvers\DomainTenantResolver;
use Stancl\Tenancy\Tenancy;


public function boot(): void
{
    $host = Request::getHost();
    $domainIsTenant = (new Domain)->where('domain', $host);

    if ($domainIsTenant->exists()) {
        $tenancy = app(Tenancy::class);
        $tenantResolver = app(DomainTenantResolver::class);

        $tenancy->initialize(
            $tenantResolver->resolve($host)
        );
    }
}
```
