### ISSUE TITLE
Base table or view not found in laravel resource route functions

### ISSUE THREAD

**Issue by dipaksarkar** [stancl/tenancy#825]
### Bug description

Resource route without index and create there is an issue that Base table or view not found: 1146 ...
But it's working when used Discount::find(id); Same for all tenant model.

### Steps to reproduce

I'm using multi database tenency and created api routes with laravel resource route it's an example of my controller function
``/**
     * Display the specified resource.
     *
     * @param  \App\Models\Discount $discount
     * @return \Illuminate\Http\Response
     */
    public function show(Discount $discount)
    {
        return response()->json(new DiscountResource($discount->load([
            'products',
            'collections',
            'buys_products',
            'buys_collections',
            'gets_products',
            'gets_collections',
            'customers',
            'group',
            'countries',
            'logs',
            'logs.created_user',
            'logs.media',
        ])), 200);
    }``

### Expected behavior

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'eravel.discounts' doesn't exist (SQL: select *, (CASE
                            WHEN
                                (enabled = 1 AND starts_at <= CURDATE() AND ends_at IS NULL) OR
                                (enabled = 1 AND starts_at <= CURDATE() AND ends_at IS NOT NULL AND ends_at > CURDATE()) THEN "Active"
                            WHEN enabled = 1 AND ends_at IS NOT NULL AND ends_at <= CURDATE() THEN "Expired"
                            WHEN enabled = 1 AND starts_at > CURDATE() THEN "Scheduled"
                            ELSE "Disabled" END
                        ) as status, (CASE
                            WHEN
                                (enabled = 1 AND starts_at <= CURDATE() AND ends_at IS NULL) OR
                                (enabled = 1 AND starts_at <= CURDATE() AND ends_at IS NOT NULL AND ends_at > CURDATE()) THEN 1
                            ELSE 0 END
                        ) as is_active from `discounts` where `id` = 1 and `discounts`.`deleted_at` is null limit 1)

### Laravel version

8.12

### stancl/tenancy version

3.5

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://discord.gg/vHjEyrw

Thanks

**Comment by dipaksarkar** [comment]
@stancl Thanks, I have fix it. :)
