### ISSUE TITLE
Error 429 "Too many requests" when I make a get API request with JWT

### ISSUE THREAD

**Issue by JRafael91** [stancl/tenancy#826]
### Bug description

when I make a protected request from "postman" or my web application, I send it a token(JWT), it shows me the error 429.

### Steps to reproduce

for test purposes leave the route unprotected, and without a token the request works.
without token.
![image](https://user-images.githubusercontent.com/39107286/158690633-460fbf40-8493-4392-bcc4-21edce7f95b5.png)

with token.
![image](https://user-images.githubusercontent.com/39107286/158690797-14f11a24-4647-4a14-b4a2-b7b230a0ee07.png)

### Expected behavior

return 200 OK.

### Laravel version

8.82

### stancl/tenancy version

3.5

**Comment by stancl** [comment]
Probably a misconfigured rate limiter?

Not sure why this would be related to the package

**Comment by JRafael91** [comment]
the problem is rare, only that the problem arose when installing and configuring the package, also change the speed limiter, apparently the problem occurs when passing an "Authorization" through the header, choose to create a custom jwt, possibly have a conflict with tymon/jwt-auth package.
