### ISSUE TITLE
Continuous support for PHP <7.4

### ISSUE THREAD

**Issue by yvan-burrie** [stancl/tenancy#827]
### Bug description

After the update from 3.5.1 to 3.5.2, you have added `public static bool $forceRefresh = false;` in `src/Bootstrappers/QueueTenancyBootstrapper.php`. This typed property is only available in PHP 7.4. It is quite a radical change to make on a minor version. Would you be able to fix this for PHP 7.2 (or 7.3) compatibility? Your awesome package works perfectly on Laravel 6 with PHP 7.2. Cheers!

### Steps to reproduce

Run `composer install` on a PHP 7.2 environment using tenancy 3.5.2.

### Expected behavior

NA

### Laravel version

6.x

### stancl/tenancy version

3.5.2

**Comment by stancl** [comment]
Ah sorry, didn't realize this wasn't available in the support versions. Pushed a fix now, updated our CI build to use 7.3 instead of 7.4, and will tag a release shortly. Thanks!
