### ISSUE TITLE
S3 uses incorrect paths in v3.5.2

### ISSUE THREAD

**Issue by stancl** [stancl/tenancy#828]
### Bug description

See https://github.com/archtechx/tenancy/pull/802#issuecomment-1074008301 and https://github.com/archtechx/tenancy/issues/739#issuecomment-1067763548

### Steps to reproduce

Upgrade to v3.5.2 with S3 used for storage

### Expected behavior

The paths should be prefixed correctly

### Laravel version

8 or 9

### stancl/tenancy version

3.5.2

**Comment by stancl** [comment]
@jtomek @miketimeturner Could you run `composer require stancl/tenancy:3.x-dev` and test if the issue persists?

**Comment by stancl** [comment]
Seems like the tests are failing due to an unrelated issue.
- `49ebb75` pass 6 days ago: https://github.com/archtechx/tenancy/actions/runs/1998379508/attempts/1
- `49ebb75` fail today: https://github.com/archtechx/tenancy/actions/runs/1998379508

**Comment by jtomek** [comment]
It's looking good. 👍
