### ISSUE TITLE
InitializeTenancyByDomain is executed after StartSession middleware

### ISSUE THREAD

**Issue by omaressaouaf** [stancl/tenancy#829]
### Bug description

as written in the title . InitializeTenancyByDomain is executed after the StartSession middleware because it belongs to a route group (tenants routes). while the StartSession belongs to the web group. with this setup when you use the database as the session driver, the application will always store the session in the central database whether you are in the central application or the tenant one.

I have tried to tweak this by adding my own InitializeTenancyByDomain middleware that extends the original one and adds a check for central domains in order not to fire the exception  "Tenant could not be identified". and adds it before the StartSession in the global stack so it can run before it in order for the session to be stored properly in the tenant database. it works on page refresh. but when i try to run a login code that initializes the tenancy manually . it does not switch to the tenant context and it keeps storing the session in the central database which is weird.

### Steps to reproduce

Added my own InitializeTenancyByDomain that extends the original one to check for central domains because I want to place it in the global stack before StartSession middleware.

```php

<?php

declare(strict_types=1);

namespace App\Http\Middleware;

use Closure;
use Stancl\Tenancy\Middleware\InitializeTenancyByDomain as OriginalInitializeTenancyByDomain;

class InitializeTenancyByDomain extends OriginalInitializeTenancyByDomain
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        //Skip for central domains
        if (in_array($request->getHost(), config('tenancy.central_domains'), true)) {
            return $next($request);
        }

        return $this->initializeTenancy(
            $request,
            $next,
            $request->getHost()
        );
    }
}

```

Adds it the global stack before StartSession

```php

<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        // \App\Http\Middleware\TrustHosts::class,
        \App\Http\Middleware\TrustProxies::class,
        \Fruitcake\Cors\HandleCors::class,
        \App\Http\Middleware\PreventRequestsDuringMaintenance::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\InitializeTenancyByDomain::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \App\Http\Middleware\SetLocale::class
    ];
  #kernel file ...

```

now the session is stored properly in the tenant database if in the tenant app (tenant subdomain) or the central database if in the central domains. but . the problem is I am trying the build the login in the central app where the tenant can enter his tenant subdomain and email and address and log him in and redirects to his subdomain. 
this is the method responsible for login in AutenticateSessionController (laravel breeze).

```php
    /**
     * Handle an incoming authentication request.
     *
     * @param  \App\Http\Requests\Auth\LoginRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(LoginRequest $request)
    {
        $tenant = Tenant::find($request->tenant_id);

        $tenant->run(function () use ($request) {
            $request->authenticate();

            $request->session()->regenerate();
        });

        return Inertia::location("http://{$tenant->domains[0]->domain}");
    }


```

everything works properly the tenancy is initialized it looks for the user in the right database. **but the bug is when it stores the session it stores it in the central instead of the tenant database which is very weird. considering the middleware setup above.**

### Expected behavior

after the tenancy is initialized it should store the session the tenants database not the central

```php

 $tenant->run(function () use ($request) {
         $request->authenticate();

         $request->session()->regenerate();
  });

```

### Laravel version

8.65

### stancl/tenancy version

3.4

**Comment by stancl** [comment]
> InitializeTenancyByDomain is executed after the StartSession middleware because it belongs to a route group (tenants routes). while the StartSession belongs to the web group. with this setup when you use the database as the session driver

I don't think the groups have an effect on anything? Laravel just follows the middleware priority

**Comment by omaressaouaf** [comment]
thanks for responding quickly. 
so I must place the InitializeTenancyByDomain before StartSession in the $middlewarePriority  group as well to solve the problem ?

**Comment by omaressaouaf** [comment]
I just tried to put the InitializeTenancyByDomain middleware first in the priority group but it did not solve the issue. the session is still being stored in the central database

**Comment by omaressaouaf** [comment]
```php

    /**
     * The priority-sorted list of middleware.
     *
     * This forces non-global middleware to always be in the given order.
     *
     * @var string[]
     */
    protected $middlewarePriority = [
        \App\Http\Middleware\InitializeTenancyByDomain::class,
        \Illuminate\Cookie\Middleware\EncryptCookies::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \Illuminate\Contracts\Auth\Middleware\AuthenticatesRequests::class,
        \Illuminate\Routing\Middleware\ThrottleRequests::class,
        \Illuminate\Routing\Middleware\ThrottleRequestsWithRedis::class,
        \Illuminate\Contracts\Session\Middleware\AuthenticatesSessions::class,
        \Illuminate\Routing\Middleware\SubstituteBindings::class,
        \Illuminate\Auth\Middleware\Authorize::class,
    ];

```

**Comment by omaressaouaf** [comment]
it appears that the issue does not have to do with the middleware but the manual initialization feature does not switch the session connection to the tenant database . it switches other database operations but not the session one . it still writes to the central database. this is very weird. i think when initializing the tenancy manually not only it should switch the database but also the session connection. in config("session.connection")  ??

**Comment by stancl** [comment]
> the manual initialization feature does not switch the session connection to the tenant database . it switches other database operations but not the session one . it still writes to the central database. this is very weird

It's not weird — it just switches the **default** connection. If you already persisted the previous connection in some state prior to this, it will use the previous connection.

Sessions in general work well with this package. You can also take a look at the docs. I'm not sure why you're having this issue because it isn't a problem generally.

**Comment by omaressaouaf** [comment]
The problem is i am running that code from the central application (login) but as you can see i run it through the tenant context. So the expected behaviour is to save the session to the tenant database not the central one

**Comment by omaressaouaf** [comment]
I hope the issue is clear. It's supposed to save the session to the tenant's DB because the authentication and session code is inside the callback passed to the run method. But it still saves it to the central DB . That's what is driving me crazy 😅

**Comment by stancl** [comment]
Ah. Well, if you're trying to use a tenant session while on a central domain, that's not going to work when you use different domains for tenants.

**Comment by omaressaouaf** [comment]
I see. By the way it's just subdomains. So is there anyway we can get around this. Because i am trying to build the login system in the central app and authenticate the tenant then redirect him to his corresponding subdomain.  Is there anyway to achieve this with this package while the session driver is database? Because a central login is very common in multi tenant applications ?

**Comment by stancl** [comment]
You can redirect the tenant to his domain and trigger a login there via the impersonation feature. The SaaS boilerplate uses this approach and it works great both with subdomains and with 2nd level domains.

Anyway, I'm closing this since it's not really a bug — more of a support question. Feel free to join our Discord to get help.

**Comment by omaressaouaf** [comment]
Ok thank you for your help . I will look into the impersonation feature to achieve this for sure
