### ISSUE TITLE
Async resource syncing throws exception: Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by Gaspertrix** [stancl/tenancy#830]
### Bug description

Enabling [queueing](https://tenancyforlaravel.com/docs/v3/synced-resources-between-tenants/#queueing) for UpdateSyncedResource throws an exception:

> Serialization of 'Closure' is not allowed

### Steps to reproduce

1. Enable [resourcers syncing](https://tenancyforlaravel.com/docs/v3/synced-resources-between-tenants/)
2. Enable [queueing](https://tenancyforlaravel.com/docs/v3/synced-resources-between-tenants/#queueing) for listener
3. Update some synced model

### Expected behavior

UpdateSyncedResource listener should be queued.

-------------

I think SyncedResourceSaved event should use SerializesModels trait to be able to serialize synced and tenant models

### Laravel version

8.83.5

### stancl/tenancy version

3.5.3

**Comment by stancl** [comment]
This relates to your deployment. You need to use a server/queue setup that allows serializing Closures.

**Comment by Gaspertrix** [comment]
@stancl 
> This relates to your deployment. You need to use a server/queue setup that allows serializing Closures.

Laravel solves this issue by itself using a custom (de)serialization for eloquent models in SerializesModels trait. There is not need to use a custom library o queue setup.
I think it would be good to use this native solution, what do you think?


```
In this example, note that we were able to pass an [Eloquent model](https://laravel.com/docs/8.x/eloquent) directly into the queued job's constructor. Because of the SerializesModels trait that the job is using, Eloquent models and their loaded relationships will be gracefully serialized and unserialized when the job is processing.

If your queued job accepts an Eloquent model in its constructor, only the identifier for the model will be serialized onto the queue. When the job is actually handled, the queue system will automatically re-retrieve the full model instance and its loaded relationships from the database. This approach to model serialization allows for much smaller job payloads to be sent to your queue driver.
```
