### ISSUE TITLE
Unit Testing does not connect to tenant domain

### ISSUE THREAD

**Issue by chrisb34** [stancl/tenancy#831]
### Bug description

When launching a unit test with the default setup, any connection to the tenant sub-domain fails.  The documentation states:

> Also, tests use localhost as the central domain. This is set in phpunit.xml's env. The reason for this is that changing the central domains config in setUp() doesn't work — the config is read before setUp() is executed to register the central routes.

However, the default config uses a domain called saas.test and not local host.

I have changed the phpUnit.xml
``
    <server name="APP_URL" value="http://tenant.saas.test"/>
``
and tenantTestCase.php
``
            config(['app.url' => 'http://saas.test']);

            /** @var UrlGenerator */
            $urlGenerator = url();
            $urlGenerator->forceRootUrl('http://tenant.saas.test');

            $this->withServerVariables([
                'SERVER_NAME' => 'tenant.saas.test',
                'HTTP_HOST' => 'tenant.saas.test',
            ]);
``
AssertSee, AssertUrl return the correct domain (tenant.saas.test) but other operations like post, put etc fail.  it appears that the user is not being recognised.  i tried forcing the unit test with 
``
        $this->actingAs( Auth::user() );
``
but this doesn't make any difference.

### Steps to reproduce

$this->get('posts')->assertSee('foo');

### Expected behavior

pass

### Laravel version

9.4.1

### stancl/tenancy version

3.5.2

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://discord.gg/vHjEyrw

Thanks
