### ISSUE TITLE
Session write should be removed in ScopeSessions.php

### ISSUE THREAD

**Issue by lanrenbulan** [stancl/tenancy#833]
### Bug description

If the developer forgets to write the tenant session after logging in, for example, modify the x-tenant-id when the next request is made, the middleware will judge that there is no session and write the tenant of the new request, breaking the restriction of the session scope.

```
class ScopeSessions
{
    public static $tenantIdKey = '_tenant_id';

    public function handle(Request $request, Closure $next)
    {
        if (! tenancy()->initialized) {
            throw new TenancyNotInitializedException('Tenancy needs to be initialized before the session scoping middleware is executed');
        }

        // Remove the below
        /*
        if (! $request->session()->has(static::$tenantIdKey)) {
            $request->session()->put(static::$tenantIdKey, tenant()->getTenantKey());
        } else {
            if ($request->session()->get(static::$tenantIdKey) !== tenant()->getTenantKey()) {
                abort(403);
            }
        }*/

        // and add the below
        if ($request->session()->get(static::$tenantIdKey) !== tenant()->getTenantKey()) {
             abort(403);
        }

        return $next($request);
    }
}
```

### Steps to reproduce

Do not write session after login, modify the x-tenant-id when the next request is made, the middleware will judge that there is no session and write the tenant of the new request, breaking the restriction of the session scope.

### Expected behavior

Direct forced check session.

### Laravel version

v9.1.2

### stancl/tenancy version

v3.5.4

**Comment by stancl** [comment]
Please fill out the template

**Comment by lanrenbulan** [comment]
I don't understand why I write a session when it is judged that it doesn't exist, which makes me very confused. Please help me.

**Comment by stancl** [comment]
Not sure what the problem is. The `if (! ...)` case sets the value.
