### ISSUE TITLE
Universal route default to central on Redis queue

### ISSUE THREAD

**Issue by zarulizham** [stancl/tenancy#842]
### Bug description

Hi, 

When dispatching notification using redis as queue connection, it seems the usage of route() will be defaulted to central.

I have a notification that includes login route in the markdown. When user received the email, the login is not being redirected to tenant but central instead.

This issue did not happened if `QUEUE_CONNECTION=sync`

### Steps to reproduce

1. Crete notification with `route('login')` in the markdown
2. Set `QUEUE_CONNECTION=redis`
3. Dispatch the notification

### Expected behavior

The login route in the email should be tenant, not central since the notification being dispatched in tenant site.

### Laravel version

9.7.0

### stancl/tenancy version

3.5.5

**Comment by stancl** [comment]
This is not really a bug since Tenancy can't make assumptions about how your routing works. It's up to you if you use domain identification or anything else.

I believe this issue was mentioned before here on GitHub. I recommend searching for that.

**Comment by zarulizham** [comment]
It seems my issues almost same with this one. Since im using URL::signedRoute as well. #249

**Comment by zarulizham** [comment]
Fixed by following https://github.com/archtechx/tenancy/issues/249#issuecomment-897367116

It doesn't have issue with queue/redis.
