### ISSUE TITLE
Redis cache storing wrong tenant name?

### ISSUE THREAD

**Issue by a-ssassi-n** [stancl/tenancy#844]
### Bug description

I have two tenants with Id: `first` and `second`. And my cache driver is set to Redis.

In my controller I am adding a value to cache like so:
`Cache::put("name", tenant()->id);`

To retrieve this data:
`Cache::get("name");`

This works fine and displays the correct names for both tenants.

But when I try to fetch the keys of the cache, the Redis CLI gives me these keys:

```
myapp_cache:2deec9455c60ae3b6bdd13e5228ed6fbed455a2d:name
myapp_cache:eae589c9ff5e298a44422d7d0c7bdcd3f307e9e5:name
```

The documentations says that the Tenant ID is added to the cache key, but here I see random generated string "2deec9455c60ae3b6bdd13e5228ed6fbed455a2d" and "eae589c9ff5e298a44422d7d0c7bdcd3f307e9e5"

What are these strings?

I wouldn't care about this as it was working fine, but for some reason, on my Central DB connection, I need to retrieve some data that is stored in the Cache of each tenant.

So I am not able to do this:
`Cache::get(config('tenancy.cache.tag_base') . $tenant->id . ':name');`

But when I do 
`Cache::get('eae589c9ff5e298a44422d7d0c7bdcd3f307e9e5:name')` I get the data.

How is that random string generated?

### Steps to reproduce

`Cache::put("name", tenant()->id);`

In Redis CLI: `keys *`

**Output:**
```
myapp_cache:2deec9455c60ae3b6bdd13e5228ed6fbed455a2d:name
myapp_cache:eae589c9ff5e298a44422d7d0c7bdcd3f307e9e5:name
```

### Expected behavior

The expected output for Cache Keys:

```
myapp_cache:tenantfirst:name
myapp_cache:tenantsecond:name
```

### Laravel version

6.0

### stancl/tenancy version

3.5

**Comment by a-ssassi-n** [comment]
Solved. To access the tenant's cache on the Centeral Route, I did this:

```
 foreach ($tenants as $tenant) {
    tenancy()->initialize($tenant->id);
    $cacheData = Cache::get('name');
    dd($cacheData);
}
```

This works fine, but I am still confused what are those random strings on the Redis cache key 😕

**Comment by stancl** [comment]
iirc those are the tags on the key. Not the key itself. We don't change the key
