### ISSUE TITLE
Tenant aware broadcasting with authentication

### ISSUE THREAD

**Issue by iamsubingyawali** [stancl/tenancy#845]
### Bug description

This may not be technically a bug, but I didn't find anything related to broadcasting in the docs. I am creating a simple restaurant management system API which fires a broadcasting event when a customer places an order from the mobile app and the restaurant will receive that event on a desktop client. I am using `laravel-websockets` for broadcasting. I am using tenancy in this project as this will be used in multiple restaurants with their own users and data.

For simplicity and testing purpose, I am using a separate Vue project and Postman to test the broadcasting. It worked fine and the broadcast was successfully received by Vue while using public channel, but I couldn't make it work using private channel and authentication.

I am using sanctum for authentication, so I modified the `BroadcastServiceProvider` as below:

```
class BroadcastServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Broadcast::routes(['middleware' => ['auth:sanctum']]);
        require base_path('routes/channels.php');
    }
}
```

I created a channel route in `routes/channels.php` to handle the request and authentication:

```
Broadcast::channel('customer-order', function ($user) {
    return $user->role == "admin" || $user->role == "staff";
});
```

Below is the defined broadcast channel on my `OrderPlaced` event

```
....
/**
 * Get the channels the event should broadcast on.
 *
 * @return \Illuminate\Broadcasting\Channel|array
 */
public function broadcastOn()
{
    return new PrivateChannel('customer-order');
}
....
```

I am using simple Vue.js app to listen to broadcasts:

```
import Echo from "laravel-echo";
import Pusher from "pusher-js";
window.Pusher = Pusher;

const token = "1|OZdkQFNRDpUxHNnXD7MFAyqlVo9dMCesA2ZkIDRz"

window.Echo = new Echo({
  broadcaster: 'pusher',
  key: 'laravel_socket',
  wsHost: '127.0.0.1',
  authEndpoint: 'http://localhost/my-app/public/broadcasting/auth',
  encrypted: true,
  forceTLS: false,
  wsPort: 6001,
  wssPort: 6001,
  disableStats: true,
  enabledTransports: ['ws', 'wss'],
  auth : {
    headers : {
        Authorization: "Bearer " + token,
        Accept: "application/json",
    }
},
})

window.Echo.private('customer-order')
    .listen('OrderPlaced', (e) => {
    console.log(e)
})
```
With this configuration, Vue.js app cannot connect to the socket server because server responds with `POST http://localhost/my-app/public/broadcasting/auth 401 (Unauthorized)`

Again, everything works if I use public channels for broadcasting and listening without any reference to tenancy and authentication. My main concern is how do I set up to use tenancy aware broadcasting with authentication?

### Steps to reproduce

-

### Expected behavior

-

### Laravel version

9.7.0

### stancl/tenancy version

3.5.6

**Comment by iamsubingyawali** [comment]
@stancl Is there any info about broadcasting and authentication for now so that I could continue my development till it officially gets it way to the documentation.

**Comment by stancl** [comment]
I think this may have been discussed on our Discord

**Comment by iamsubingyawali** [comment]
Yeah, very briefly. I asked that question but that was a workaround kind of solution. Is there anything else that this package provides? 

I implemented that solution too but still not able to authorize. I am getting 401.

**Comment by iamsubingyawali** [comment]
I finally found the solution

The solution was to specify all tenancy related middlewares in `BroadcastServiceProvider`.

```
class BroadcastServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Broadcast::routes(['middleware' => ['auth:sanctum', InitializeTenancyByRequestData::class, CheckTenantForMaintenanceMode::class, AdminMiddleware::class]]);
        require base_path('routes/channels.php');
    }
}
```
I am checking for user roles in `AdminMiddleware` so we can just return `true` in `routes\channels.php` else we can check for roles withing the route too.

```
Broadcast::channel('customer-order', function ($user) {
    return true;
});
```

As I am using request data for tenant identification, an additional header is required in `laravel-echo`:

```
...
auth : {
    headers : {
        Authorization: "Bearer " + token,
        Accept: "application/json",
       'X-Tenant': 'my-tenant',
    }
},
...

```

**Comment by jonathanpmartins** [comment]
Would be nice to have some documentation about this. I'm ready to migrate my app to use tenancy and broadcasting is a big thing.

**Comment by eskiesirius** [comment]
Thank you so much for asking this! Because I want to create same system

**Comment by LiXunGuan** [comment]
Recently prepared to use soketi and broadcast system, but did not find relevant documentation.
It is recommended to add a description in the V4 version of the document

**Comment by jonathanpmartins** [comment]
Would be nice to have some docs about this on V3. Even though it says something like: "- we do not support it. You should manage it yourself." When is the planned release date for V4?

**Comment by stancl** [comment]
Going to decide how we handle broadcasting when I work on v4. Will probably share some updates soon

**Comment by zainspresso** [comment]
I discovered that this is dangerous as the authentication works but the channels are just one big Channel, for example; 
You have two tenants; tenant1 and tenant2 with separate databases.
There  is user with id 10 on tenant 1 and also on tenant2.
You broadcast to id 10 on tenant1 with private channel me.10
You only want the user on tenant1 to receive the message but the message is received on both tenants because the user ID is the same. I fixed this by adding the tenant id in the private channel so; me.<tenantid>.<userid>. A other option would be different pusher keys for each tenant
I discovered this by accident but I wanted to share this with you.

**Comment by jonathanpmartins** [comment]
Thanks! Will take a look on my implementation!

**Comment by LiXunGuan** [comment]
> Going to decide how we handle broadcasting when I work on v4. Will probably share some updates soon

Is there any documentation on multi-tenant broadcast handling now?

**Comment by J5Dev** [comment]
Just wanted to hop in here and add to this one, while it isn't a solution (yet), certainly something to consider.

We are using Soketi for our socket service, and as such are using the Apps feature of that to manage our socket client access. This allows for db usage to manage 'apps', which we are doubling up with our tenants db, so as to allow each tenant to have their own broadcasting system, isolated from other clients.

Now, this gives the ability to simply create a custom bootstrapper which will swap out the required credentials (specifically app id & secret) within Laravel regarding the broadcaster. This is something I hope to work on in the next week or so, and presume would be what you are looking for @LiXunGuan

The only problem I see is that this is made easy due to the abilities of Soketi or other Pusher service such as Pusher Channels or Laravel-Websockets, but maybe won't be so simple with something like laravel-echo-server or other custom service.

But could be tackled using/providing various 'sub' bootstrappers for the more mainstream broadcasting engine configurations.

Will see what I can come up with as part of my experimentation and feed back :)

**Comment by dloused** [comment]
Adding my two cents:
In my case (SPA frontends / API backend) i needed to handle brodcasting routes both for the central app and the tenant app.

Just added the below in the routes/api.php 

```
 if (request()->hasHeader('X-Tenant')) {
Broadcast::routes(['middleware' => ['auth:sanctum',InitializeTenancyByRequestData::class]]);
} 
else {
Broadcast::routes(['middleware' => ['auth:sanctum']]);
}

**Comment by juanxodj** [comment]
Thanks to your solution it worked for me! But now I have a problem with Pusher. In the face-to-face channels, the connection in each tenant works correctly, but with private channels they always appear as: Occupied. Has this happened to anyone else?

**Comment by Fsmash** [comment]
I see that there is currently a tenancy bootstrapper for broadcasting in the works to be in the next release so take my current solution with a grain of salt if 4.x is out. 

The issue with @iamsubingyawali solution is as @zainspresso pointed out. That ultimately, an event being handle by whatever driver and server combo you choose is "session-less". The channel name needs to contain something that uniquely identifies the tenant. The tenant ID would be an obvious choice. 

`Broadcast::channel('order.{tenant}', function ($user, $tenant) {
  return $tenant === tenant()->id;
});
`

If tenant isolation is a concern, then as @J5Dev suggested multiple servers can be a solution especially with soketi. But along with other potential security issues and the complexity/hassle of implementation and maintenance, I feel like my solution is a lot simpler and secure if you have a typical tenancy setup that identifies tenants by domain/subdomain.

https://tenancyforlaravel.com/docs/v3/session-scoping/#using-a-middleware-to-prevent-session-forgery

By utilizing one of the session scoping strategies suggested, you can simply use `InitializeTenancyBySubdomain::class` as one of the specified middlewares for `Broadcast::routes(...)`. Or whatever equivalent middleware based on your tenancy setup. 

You should only use `InitializeTenancyByRequestData::class` if you aren't identifying the tenant by domain or subdomain. Like a SPA with sanctum or an API with passport for example.

**Comment by MuscledGeek** [comment]
@J5Dev Hi man, I know I'm pretty late to the party.. would you mind to share how you manage to override the broadcast settings?

I added a listener called "SetPusherCredentials" in the **TenancyServiceProvider.php** file, in the **Events\TenancyInitialized** event,  wich attempts to set the broadcast settings for current tenant but unfortunatelly, this gets executed after the BroadcastManager setup so default .env vars are used.

I'm also using **soketi** and the so called **apps** feature.

Thanks in advance.

**Comment by stancl** [comment]
https://tenancy-v4.pages.dev/broadcasting/

**Comment by giuseppe-osenda** [comment]
for anyone coming here with this problem with laravel reverb following what's explained in this  [stackOverflow](https://stackoverflow.com/questions/78567228/pusher-broadcasting-with-tenancyforlaravel-user-not-recognized) discussion worked for me
