### ISSUE TITLE
Is it possible to use a subdomain as the central domain?

### ISSUE THREAD

**Issue by mauricehofman** [stancl/tenancy#846]
### Bug description

I`m trying to use a subdomain as the central domain (for a staging env).

For example:

**staging.multi-tenancy.com** should be the central domain 
**customer.staging.multi-tenancy.com** should load the customers tenant.

When setting **staging.multi-tenancy.com** as a central domain in de tenancy.php config file, i receive the following error:

Tenant could not be identified on domain staging.multi-tenancy.com.

It sees 'staging' as a tenant. 

Is this possible?

### Steps to reproduce

- add a domain with subdomain in config file
- deploy
- visit staging.domain.com

### Expected behavior

Having subdomain as a central domain.

### Laravel version

9.8

### stancl/tenancy version

3.5.6

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://discord.gg/vHjEyrw

Thanks

**Comment by japr8985** [comment]
Hi! i have the same problem, how can i fixed?
