### ISSUE TITLE
sanctum authentication  and request data middleware are not working together

### ISSUE THREAD

**Issue by muhammad-salman-khalid** [stancl/tenancy#850]
### Bug description

Hello, first of all, thank you for all the good work done with this package. I have set up a multi-database tenancy by using Request data identification following the steps in the stancl/tenancy docs. Everything works fine but when I was doing security tests I have noticed that since a user is authenticated, he is able to request data from all tenants (routes protected by auth:sanctum middleware).but if I add  InitializeTenancyByRequestData MW after auth:sanctum it starts giving unauthenticated error.
I am using a Laravel 8 API with Laravel Sanctum. How could I prevent that? .
I have read the docs exhaustively; I have searched in the Discord Community of the package and I cannot figure out how to avoid showing data from users in other databases.
For example, a tenant called 'foo' authenticates in its own database. If he tries to request data from another tenant he can return the data from another database/ tenant by simply changing the header parameter X-tenant to a required. This is working without InitializeTenancyByRequestData  MW but with InitializeTenancyByRequestData  it returns unauthenticated .So actually I have 2 issues one is you alread addressed but it was for path identification not for InitializeTenancyByRequestData  .kindly help me out on this issue as well as unauthenticated issue  .If I use session scopping I got Tenancy needs to be initialized before the session scoping middleware is executed this error . 

Here's my code

Route::middleware([
    'web',
//    'auth_tenant',
    'auth:sanctum',
    InitializeTenancyByRequestData::class,
    PreventAccessFromCentralDomains::class,

])->group(function () {

    Route::prefix('branch/')->group(function () {
//        Route::get('/list', function () {
            Route::get('list',  [BranchController::class, 'get_list']);
            Route::get('{id}', [BranchController::class, 'get_branch']);
            Route::post('add', [BranchController::class, 'store']);
            Route::post('update', [BranchController::class, 'update']);
            Route::get('change-status/{branch_id}/{status}', [BranchController::class, 'change_status']);
//        });
    });
    Route::prefix('user/')->group(function () {
        Route::get('list',  [UserController::class, 'get_list']);
        Route::get('{id}', [UserController::class, 'get_user']);
        Route::post('add', [UserController::class, 'store']);
        Route::post('update', [UserController::class, 'update']);
        Route::get('change-status/{user_id}/{status}', [UserController::class, 'change_status']);
    });

    Route::prefix('group/')->group(function () {
        Route::get('list',  [GroupController::class, 'get_list']);
        Route::get('{id}', [GroupController::class, 'get_group']);
        Route::post('add', [GroupController::class, 'store']);
        Route::post('update', [GroupController::class, 'update']);
        Route::get('delete/{group_id}', [UserController::class, 'delete']);
    });
    Route::get('/', function () {
        return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
    });

});

### Steps to reproduce

installed laravelfor tenancy package and configure multi -tennat app and try to access tenant database after login with sanctum 

### Expected behavior

it should logged inn and return required data also return data for current tenant only not every tenant database 

### Laravel version

8.3

### stancl/tenancy version

3.10

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://discord.gg/vHjEyrw

Thanks
