### ISSUE TITLE
MustVerify first try sent to central domain not tenant subdomain

### ISSUE THREAD

**Issue by apricomsystems** [stancl/tenancy#851]
### Bug description

     $tenant->run(function($tenant){
            $user = User::create([
                'name' => $tenant->name,
                'email' => $tenant->email,
                'password' => $tenant->password,
            ]);

            event(new Registered($user));
        });

       class CustomVerifyEmail extends VerifyEmail
       {
           protected function verificationUrl($notifiable)
           {
               if (static::$createUrlCallback) {
                   return call_user_func(static::$createUrlCallback, $notifiable);
               }
  
               return URL::temporarySignedRoute('tenant.verification.verify',
                   Carbon::now()->addMinutes(Config::get('auth.verification.expire', 60)),
                   [
                       'id' => $notifiable->getKey(),
                       'hash' => sha1($notifiable->getEmailForVerification()),
                   ]
               );
           }
       }

Sent verification link has the central domain instead of the tenant domain after user is registered. On the tenant views, if i press resend, then it uses the correct subdomain but the first time is always central domain.

### Steps to reproduce

Followed Quickstart changing a couple of routes to only beeing available on the tenants (like te verification link tenant.verification.verify)

Tenant is created, domain is attached, user is created on tenant database all successfull.

### Expected behavior

Since i'm creating the user inside the closure, i expect the verification link created to be pointing to the domain of the tenant holding that user and not the central domain

### Laravel version

9.2

### stancl/tenancy version

3.5

**Comment by apricomsystems** [comment]
Had to change Illuminate\Routing\UrlGenerator to get this to work properly


    public function temporaryTenantSignedRoute($name, $expiration, $parameters = [], $absolute = true)
    {
        return $this->tenantSignedRoute($name, $parameters, $expiration, $absolute);
    }

    public function tenantSignedRoute($name, $parameters = [], $expiration = null, $absolute = true)
    {
        $this->ensureSignedRouteParametersAreNotReserved(
            $parameters = Arr::wrap($parameters)
        );

        if ($expiration) {
            $parameters = $parameters + ['expires' => $this->availableAt($expiration)];
        }

        ksort($parameters);

        $key = call_user_func($this->keyResolver);

        return tenant_route(tenant()->domains->first()->domain, $name, $parameters + [
            'signature' => hash_hmac('sha256', tenant_route(tenant()->domains->first()->domain, $name, $parameters, $absolute), $key),
        ], $absolute);
    }

**Comment by stancl** [comment]
> Since i'm creating the user inside the closure, i expect the verification link created to be pointing to the domain of the tenant holding that user

Tenants can have multiple domains. The package can't tell which domain is the right one. So this should be implemented in an app-specific way.

**Comment by apricomsystems** [comment]
> > Since i'm creating the user inside the closure, i expect the verification link created to be pointing to the domain of the tenant holding that user
> 
> Tenants can have multiple domains. The package can't tell which domain is the right one. So this should be implemented in an app-specific way.

I know that, but my function could easily be made to work with an aditional parameter so the user could provide the specific tenant domain on which to send the email or leave empty and send it through the default. I just think "not" having any way to send that email with the tenant domain while still beeing on the central domain is counter productive

Other than that your package is top notch!

**Comment by aeq-dev** [comment]
Hello @apricomsystems 
Did you try to extend UrlGenerator instead of updating the core class ?
@stancl, I'm facing the same issue, could you please share with us how do you implement it n an app-specific way? 
Thanks

**Comment by aeq-dev** [comment]
Okey ! I've just found a solution for this :)

**Comment by stancl** [comment]
Could you share it here so that others can find it?

**Comment by aeq-dev** [comment]
Yes Sure ;) it's just about one line of code **URL::forceRootUrl** : 
**1. For VerifyEmail :**
```
class VerifyEmailQueued extends VerifyEmail implements ShouldQueue
{
    use Queueable;

    protected function verificationUrl($notifiable)
    {
        if (static::$createUrlCallback) {
            return call_user_func(static::$createUrlCallback, $notifiable);
        }
        if (tenant('id'))
            URL::forceRootUrl(SharedHelper::tenantUrl());

        return URL::temporarySignedRoute(
            'verification.verify',
            Carbon::now()->addMinutes(Config::get('auth.verification.expire', 60)),
            [
                'id' => $notifiable->getKey(),
                'hash' => sha1($notifiable->getEmailForVerification()),
            ]
        );
    }
}
```
In User Model :
```
public function sendEmailVerificationNotification()
{
     $this->notify(new VerifyEmailQueued);
}
```
**2. For ResetPassword :** 
```
class ResetPasswordQueued extends ResetPassword implements ShouldQueue
{
    use Queueable;

    protected function resetUrl($notifiable)
    {
        if (static::$createUrlCallback) {
            return call_user_func(static::$createUrlCallback, $notifiable, $this->token);
        }
        if (tenant('id'))
            URL::forceRootUrl(SharedHelper::tenantUrl());
        return url(route('password.reset', [
            'token' => $this->token,
            'email' => $notifiable->getEmailForPasswordReset(),
        ], false));
    }
}

```
In User model: 
```
public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordQueued($token));
    }
```

**Finaly, here's the tenantUrl :** 
  ```
public static function tenantUrl()
    {
        $disallowed = array('http://', 'https://');
        foreach ($disallowed as $d) {
            if (strpos(env('APP_URL'), $d) === 0) {
                return 'http://' . tenant()->domain . '.' . str_replace($d, '', env('APP_URL'));
            }
        }
        return 'http://' . tenant()->domain . '.' . env('APP_URL');
    }
```

Enjoy :)

**Comment by Parables** [comment]
In any of your ServiceProviders(e.g: AppServiceProvider.php):

```php
    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
     URL::macro('signedTenantRoute', function (
            \BackedEnum|string $name,
            \DateTimeInterface|\DateInterval|int|null $expiration = null,
            array $parameters = [],
            bool $absolute = true,
            string|null $domain = null,
        ) {
            $this->ensureSignedRouteParametersAreNotReserved(
                $parameters = Arr::wrap($parameters)
            );

            if ($expiration) {
                $parameters = $parameters + ['expires' => $this->availableAt($expiration)];
            }

            ksort($parameters);

            $key = call_user_func($this->keyResolver);
               
            // generates the url as normally
            $url = $this->route($name, $parameters, $absolute);

            // checks if a domain was given or a tenant has been initialized
            // and modifies the host: e.g: http://localhost becomes http://abc.localhost
            if ($domain ??= tenant()?->domains?->first()?->domain) {
                $host = parse_url($url, PHP_URL_HOST);
                $url = str_replace($host, "$domain.$host", $url);
            }

            // signs the modified url to prevent any tampering/modification
            $signature = hash_hmac('sha256', $url, is_array($key) ? $key[0] : $key);
 
             // returns the url with the signature added to the query string 
            return match (str_contains(needle: '?', haystack: $url)) {
                true => $url . "&signature=$signature",
                false => $url . "?signature=$signature",
            };
        });
}

```
