### ISSUE TITLE
[Sanctum] Shared session between Central App and Tenants

### ISSUE THREAD

**Issue by CodeWrap** [stancl/tenancy#853]
### Bug description

Hello there,
my Tenancy setup consists of the following:

- A central app, which is available at **example.test** that includes Laravel Nova for tenant managemant
- SPA Tenants accessible via subdomains ***.example.test** e.g. foo.example.test
- For tenant identification I'm using the **InitializeTenancyByRequestData** Middleware and the X-Tenant Header
- All my SPAs and the central application use **sanctum session authentication**
- I'm using the **ScopeSessions Middleware** to prevent session sharing between tenants, which is working correctly
- All requests from the SPA are going to **HOST example.test** which prevents using the **PreventAccessFromCentralDomains Middleware**. So the use of the middleware leads to a 404 in my SPA

Kernel.php
```
tenant' => [
    'api',
    InitializeTenancyByRequestData::class,
    ScopeSessions::class
]
```

.env
```
APP_URL=http://example.test
SESSION_DOMAIN=.example.test
SANCTUM_STATEFUL_DOMAINS=*.example.test,*.example.test:4200
```
routes/tenant.php
```
Route::group(['middleware' => ['tenant', 'auth:sanctum']], function () {
   //
};
```
Since all apps use the same **SESSION_DOMAIN .example.test**, I can log into the central app, switch to a tenant and still be logged in.
However, the more serious problem is the reverse case. When a SPA user is logged in, he can switch to example.test and access all resources if the users share the same ID

I hope i didn't miss anything.

Would be great if you could help me

Many thanks in advance

### Steps to reproduce

see above

### Expected behavior

Session should not be shared between central and tenants

### Laravel version

9.8.1

### stancl/tenancy version

3.5

**Comment by stancl** [comment]
> I'm using the ScopeSessions Middleware to prevent session sharing between tenants, which is working correctly

So the `ScopeSessions` MW prevents the sessions from being shared between different tenants, but not between tenants and the central app?

**Comment by CodeWrap** [comment]
> So the `ScopeSessions` MW prevents the sessions from being shared between different tenants, but not between tenants and the central app?

yes, that's correct

**Comment by stancl** [comment]
Seems like you're using Sanctum though, I'm not sure if the middleware was meant for that as well.

Notice this: https://github.com/archtechx/tenancy/blob/3.x/src/Middleware/ScopeSessions.php#L18

The middleware throws an exception when a central domain is being used. So there's nothing leaking through it.

**Comment by stancl** [comment]
I believe there are no leaks with a traditional server-rendered multi-domain setup. Other ways to authenticate users or other routing setups might need some extra logic.
