### ISSUE TITLE
Complete Guide

### ISSUE THREAD

**Issue by Mo7mud** [stancl/tenancy#858]
#### Description
Is there any complete guide on how to build an app with this library?
Or working example on Github?
#### Why this should be added
I tried the docs but I can't bring it all together, Quick start is very very basic with the minimum thing and I can't understand how to do many things like how to work with many databases or multiple domains, I know it's there but like a puzzle every piece in a room.
Thank you very much

**Comment by stancl** [comment]
We'll be rewriting the docs from scratch for v4 👍🏻
