### ISSUE TITLE
There is no active transaction

### ISSUE THREAD

**Issue by stephenjason89** [stancl/tenancy#860]
### Bug description

When trying to create a tenant using graphql it throws me this error.

Weird thing is that everything works as expected.
Database being created, migrated, and seeded.

### Steps to reproduce

<img width="551" alt="image" src="https://user-images.githubusercontent.com/3810177/168383274-d24ee407-bb0c-4023-9c16-9637db26c536.png">

<img width="508" alt="image" src="https://user-images.githubusercontent.com/3810177/168383206-9d762376-422e-4baf-8a8a-c770c7a0aa34.png">

<img width="1780" alt="image" src="https://user-images.githubusercontent.com/3810177/168383623-a37fc35d-dbe0-4adc-9eaf-0f1e0b7ef3c4.png">

### Expected behavior

no errors

### Laravel version

laravel 9.2

### stancl/tenancy version

3.5.6

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://discord.gg/vHjEyrw

Thanks

**Comment by stephenjason89** [comment]
@stancl thank you. I will message there. Though, everything else on my setup is working fine. 
Error only happens when creating a tenant.

**Comment by ChrisThompsonTLDR** [comment]
Any solution for this?  I'm encountering it on a very basic Laravel app.

```php
        DB::transaction(function () use ($request) {
            $tenant = new Tenant;
            $tenant->save();

            $tenant->domains()->create([
                'domain' => $request->input('domain'),
            ]);
        });
```

and also

```php
        DB::beginTransaction();

        try {
            $tenant = Tenant::create();

            $tenant->domains()->create([
                'domain' => $request->input('domain'),
            ]);

            DB::commit();
        } catch (Exception $e) {
            DB::rollBack();
        }
```

**Comment by stancl** [comment]
You cannot call `Tenant::create()` in a DB transaction when `Tenant::create()` creates a new database.
