### ISSUE TITLE
Enable Add Central Domain From .env 

### ISSUE THREAD

**Issue by amjeed-ay** [stancl/tenancy#861]
Make central domain to be added from .env file, so that it can be updated anytime instead of updating from the config file "config/tenancy.php".

**Comment by eduance** [comment]
It does not sound like an env variable would be the way to go. Array is not a currently supported datastructure for environment variables. I would like to think of a better solution, why not simply update it from the config? What is the current problem you're facing?

**Comment by saninmersion** [comment]
@amjeed-ay 
just add `CENTRAL_DOMAIN=localhost` in your `.env `  and ` 'central_domain'    => env('CENTRAL_DOMAIN')` in your `config/app.php` 
then use in it `config/tenancy.php` as 
```
'central_domains'      => [
        config('app.central_domain'),
    ],

**Comment by stancl** [comment]
@eduance Yeah we'd need to `explode(',', env('CENTRAL_DOMAIN'))` — and people would need to know that `foo.com,bar.com` is the syntax. For that reason we don't use an env var by default in v3. But people are of course free to add them if they wish.

Also, I generally recommend using a single central domain.
