### ISSUE TITLE
separate routes  ?

### ISSUE THREAD

**Issue by VConsultingCH** [stancl/tenancy#862]
Hello,

How to separate routes / view specific to the central application and the routes of the tenants?

I have this error on some routes that are intended for the central:
Tenant could not be identified on domain ...

**Comment by amjeed-ay** [comment]
tenant's route should be in the `"routes/tenant.php"` then central application route in your web routes `"routes/web.php"`.
dont forget to add Initialize tenant middleware from `Stancl\Tenancy\Middleware\` to your tenant routes.

Also if you want to use the route for both tenant and central, you can and universal middleware by following the documentation. https://tenancyforlaravel.com/docs/v3/features/universal-routes/#universal-routes

**Comment by VConsultingCH** [comment]
A but yes, pfff not awake.
sorry for this stupid question.

Thank you and good day
