### ISSUE TITLE
Testing with Tenants

### ISSUE THREAD

**Issue by anabeto93** [stancl/tenancy#867]
### Bug description

Testing with mysql instead of sqlite shows errrors like `There is no active transaction` especially with using the `RefreshDatabase` trait in your test class. According to the discussion here [PHP 8.0 PDO::rollBack()](https://github.com/laravel/framework/issues/35380), this is a problem that occurs due to `"implicit commits."`

### Steps to reproduce

1. Setup a Laravel application using this package with MultiDB setup
2. Write a simple test where a tenant is created
```php
    use RefreshDatabase;

    /** @test */
    public function sample_test()
    {
        // Requires a tenant
        Tenant::factory()->create([
            'id' => Str::uuid()->toString(),
        ]);

        $this->assertEquals(1, Tenant::count());
    }
```
3. Run the test
```shell
./vendor/bin/pest --filter sample_test
```

Additional steps below not really required, but you can go to `TenancyServiceProvider` and comment out everything related to creating a new database for the new Tenant and migrating or seeding database under the `Events\TenantCreated > JobPipeline`.

4. Repeat step 3 above and observe the test pass.

Sample Test
![sample_test](https://user-images.githubusercontent.com/7607657/170833857-87a017fe-ca22-407c-92fb-03505d77fb92.png)

Result
![sample_test_result](https://user-images.githubusercontent.com/7607657/170833872-c17117d9-ac02-489c-8367-36a412134098.png)

### Expected behavior

The test should've passed without any problems. But it does not.

If no tenant is being created (leading to an implicit commit)

![no_db_created](https://user-images.githubusercontent.com/7607657/170833887-04a6b3dd-9dba-48d6-af1b-53a527bf2fda.png)

Test Passes
![test_passed_if_no_db_created](https://user-images.githubusercontent.com/7607657/170833897-f45f6259-0b4a-4770-8513-1677481d290c.png)

### Laravel version

8.1.0

### stancl/tenancy version

3.5.6

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks

**Comment by masiorama** [comment]
@anabeto93 did you solve this? I'm experiencing the same issue and up until now my only solution is to not rely on RefreshDatabase trait, but I guess it's not the right way to address the issue.

**Comment by brysonreece** [comment]
The solution is to commit the active transaction created by `RefreshDatabase`, create your tenant, then create a new transaction.

```php
DB::commit();
Tenant::create(...);
DB::beginTransaction();
```

This is because creating/deleting a Tenant database causes an _implicit commit_. For more information on implicit commits, see the Laravel documentation [here](https://laravel.com/docs/10.x/database#implicit-commits-in-transactions).
