### ISSUE TITLE
Using Tenancy slow down my app

### ISSUE THREAD

**Issue by quentin-tdclic** [stancl/tenancy#868]
### Bug description

Using Tenancy makes total execution time increase a lot : it doubles execution time.

On a fresh app without Tenancy :
![09-33-53](https://user-images.githubusercontent.com/49473364/171122864-35cfb718-f923-4023-8fae-dff94870ed9b.png)

On a fresh app with Tenancy :
![09-34-11](https://user-images.githubusercontent.com/49473364/171122938-bc05a454-a24f-4bb7-bc11-c80d5e97c53c.png)

On my real app, a huge page comes from 2s to 4.5s !

### Steps to reproduce

1. Create a fresh install of Laravel 8
    -> Create a migration for "elements" table
```
Schema::create('elements', function (Blueprint $table) {
    $table->id();
    $table->string('label', 255);
    $table->timestamps();
});
```
   -> Seed 10000 elements with `Element::factory(10000)->create();`
   -> Create a route containing `Element::get();` so we instantiate each element

2. Create another fresh install of Laravel 8 and install Tenancy
    -> reproduce steps above in Tenant context
    -> activate Domain cache with `DomainTenantResolver::$shouldCache = true;`

3. Access the route of each Lavarel install and compare execution times

### Expected behavior

It shouldn't take that long to figure out which Tenant context to use.

### Laravel version

8.83.14

### stancl/tenancy version

3.5.6

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://discord.gg/vHjEyrw

Thanks

**Comment by quentin-tdclic** [comment]
Hi !

Thank you for your quick answer.

I'm sorry to insist but the tests carried out and examples given come from fresh installations of _Laravel 8_ in one hand and _Laravel 8 + Tenancy_ in the other hand.

**Comment by stancl** [comment]
It's specific to your environment, your database engine, and the test you're using. Real world apps don't instantiate 10,000 models unless they have severe n+1 issues, and Tenancy doesn't "double" execution time. It makes extra DB calls, but it doesn't multiply your original execution time by two. That all is just dependent on your environment and code.
