### ISSUE TITLE
Error When Creating User after initialize tenant on custom TenantKeyname

### ISSUE THREAD

**Issue by amjeed-ay** [stancl/tenancy#871]
### Bug description

![Screenshot 2022-06-02 161556](https://user-images.githubusercontent.com/72697280/171663196-f0dc06a0-bbce-47ae-9934-bc3522f3eb9f.png)

When using Synced Resource, I change `getTenantKeyName` to my custom column `slug` instead of  `id`,  when creating new user after initialize tenant, it try to attach the user to the tenant on event : `updateResourceInCentralDatabaseAndGetTenants`

```
Pivot::withoutEvents(function () use ($centralModel, $event) {
     $centralModel->tenants()->attach($event->tenant->getTenantKey());  // <- this line
 });
```

It is trying to create pivot `tenant_users` with `global_user_id` and tenant `slug` instead of `id` because it uses the attribute `getTenantKey()`

### Steps to reproduce

When using Synced Resource, I change `getTenantKeyName` to my custom column `slug` instead of  `id`,  when creating new user after initialize tenant, it try to attach the user to the tenant on event : `updateResourceInCentralDatabaseAndGetTenants`

### Expected behavior

Model User should be created and attached to the initialed tenants without error even when using custom tenant_key_name on Tenant Model

### Laravel version

9.2

### stancl/tenancy version

3.5.7

**Comment by stancl** [comment]
Could you provide **all** of the _relevant_ code? It's difficult to understand what's your code and what's the package code that you're referring to.
