### ISSUE TITLE
Spatie Media Library

### ISSUE THREAD

**Issue by mbs047** [stancl/tenancy#877]
Hi @stancl,

I saw that you have documentation for how to install a few packages from Spatie but in my opinion, Spatie Laravel Media Library is the most important package, and currently, I'm facing some difficulty trying to install it, so could you please help me with that.

The error is related to caches and storage if i'm not wrong
```php
file_put_contents(/......./storage/tenant20f6482c-11d8-49b2-8aa6-70a96f4fb921/framework/cache/facade-c2f53e2d655810ac111b48d42b34b209861bb985.php): Failed to open stream: No such file or directory
```

**Comment by stancl** [comment]
See the right support channels
