### ISSUE TITLE
nWidart/laravel-modules routes and queries go to central Database 

### ISSUE THREAD

**Issue by Mo7mud** [stancl/tenancy#878]
### Bug description

I'm using nWidart/laravel-modules package in my project then I added tenancy package now every route inside each module calls data from central database not tenant database which causes table not found exception.

If I moved routes to routes/tenant.php it works fine but this means redoing a lot of work and breaks project modularity.

How to solve this issue 

### Steps to reproduce

Use nWidart/laravel-modules then add sancl/tenancy then try to open routes that inside modules routes file

### Expected behavior

Data should come from tenant database not central database

### Laravel version

8.40

### stancl/tenancy version

3.5

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks

**Comment by Mo7mud** [comment]
> Hey!
> 
> Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.
> 
> If you need quick support, you can visit our Discord community here: https://archte.ch/discord
> 
> Thanks

What's the proper setup for it with the modules package?
Is it in the docs?
I looked for it but didn't find it

**Comment by Mo7mud** [comment]
No help here
No help on Discord
No proper docs

**Comment by megadola** [comment]
@EgyptianM did you solve this issue?

**Comment by megadola** [comment]
@EgyptianM inside your modules' routes files (api.php and web.php) wrap your routes with

`Route::middleware([`
`    InitializeTenancyByDomain::class,`
`    PreventAccessFromCentralDomains::class,`
`])->group(function () {`
`         Route::namespace('\Modules\DynamicLists\Http\Controllers\Api\v1\')->group(function() {`
`//`
`         });`
`});`

You've to change the namespace with each module namespace

and don't forget to call
`use Stancl\Tenancy\Middleware\InitializeTenancyByDomain;`
`use Stancl\Tenancy\Middleware\PreventAccessFromCentralDomains;`

**Comment by a-di-ez** [comment]
@EgyptianM @megadola same issue, any solution?
