### ISSUE TITLE
Adding Laravel Vapor Deployment Guide

### ISSUE THREAD

**Issue by CovertError** [stancl/tenancy#882]
#### Description

just a guide for what needs to be done to deploy a multi-database multi-domain on Laravel vapor
#### Why this should be added

well currently as far as I looked I can't find one that explains this soo

**Comment by danmatthews** [comment]
Subscribing to this as we're currently in the throes of moving to Vapor, and using this tenancy package is in our near future!

**Comment by stancl** [comment]
There isn't really anything special about Vapor when it comes to multi-tenancy.

The only thing to keep in mind is that out of the box, Vapor doesn't let you use HTTPS certificates for customer domains. You might be able to use SAN certificates, but those are limited and generally not recommended.

Instead, you need to use something like Caddy to deal with the HTTPS certificates. Laravel News has an article about this: https://laravel-news.com/unlimited-custom-domains-vapor
