### ISSUE TITLE
'php artisan tenants:migrate-fresh' should ask confirmation in production env

### ISSUE THREAD

**Issue by KazutakaYamane** [stancl/tenancy#888]
### Bug description

'php artisan tenants:migrate-fresh' command doesn't ask confirmation in production env.
'php artisan tenants:migrate' and  'php artisan tenants:seed' ask confirmation and stop in production env.
'migrate-fresh' command is more danger than above commands.
So 'migrate-fresh' command should ask confirmation in prod env.

### Steps to reproduce

```
//.env
APP_ENV=production
```
```
php artisan tenants:migrate
// ask confirmation and stop proceed.

php artisan tenants:migrate-fresh
// NOT ask confirmation, just run.
```

### Expected behavior

```
php artisan tenants:migrate-fresh
 //show confirm message like migrate and seed command.
```

### Laravel version

9.19.0

### stancl/tenancy version

^3.4

**Comment by stancl** [comment]
You can change the behavior here https://github.com/archtechx/tenancy/blob/3.x/assets/config.php#L186
