### ISSUE TITLE
route() helper takes last domain in central domains list (config/tenancy.php)

### ISSUE THREAD

**Issue by giagara** [stancl/tenancy#890]
### Bug description

The problem seems present if you have more than one central domain in domains list (config/tenenacy.php key central_domains), and try to use `route()` helper. The helper return the LAST domain in domains list with the provided URI.

### Steps to reproduce

In config/tenancy.php add more than one domain:
```
'central_domains' => [
        'first.domain.local',
        'second.domain.local',
],
```

In routes/web.php add some routes with name:
```
Route::get('/', function () {
    return view('central.homepage');
});
    
Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::view('about', 'about')->name('about');
```

In HomeController@index call `dd(route('home'))`.

Connect to the application using http://first.domain.local/home and the result will be http://second.domain.local/home

### Expected behavior

The expected behavior should be the same domain calling the application, so based on the example: http://first.domain.local/home

### Laravel version

8.83.15

### stancl/tenancy version

3.5.7

**Comment by giagara** [comment]
Right now I've solved using `route('home', [], false)` and this will generate a `/home` link that work in my blade file.
But this remain an issue.

**Comment by stancl** [comment]
How exactly are you registering the routes? It feels like you're looping through the central domains and registering them on all domains so it picks the last one for the `domain()` scope.

**Comment by giagara** [comment]
i'd say i'm not registering it. The package handle the registration for me i suppose (?!) like mentioned in https://tenancyforlaravel.com/docs/v3/quickstart section Central routes.

**Comment by stancl** [comment]
See the note here https://tenancyforlaravel.com/docs/v3/routes/#central-routes
