### ISSUE TITLE
Bus batch route helper

### ISSUE THREAD

**Issue by num3r06** [stancl/tenancy#891]
### Bug description

Hi,
In my existent laravel app i use Bus::batch for job batching.
First of all the batch, not like single job, run on a tenant table. But the bug it's on route helper.
One of batch's job return a link with route('my_route',parameter) but this route it's on central app and not on subdomain tenant

### Steps to reproduce

Create a batch
run a worker 
final link it's wrong

### Expected behavior

link in tenant route instead of central app

### Laravel version

8.19

### stancl/tenancy version

3.1

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks
