### ISSUE TITLE
Impossible to access to tenancy assets

### ISSUE THREAD

**Issue by AndreBlade97** [stancl/tenancy#901]
### Bug description

I can't access to image saved in public folder of single tenant.
The image is saving by` Image::make(__('Logo'), 'company_logo')->disk('public')` and I retrieve the file on my app on this path: storage/tenant24087ec6-e592-40a3-a33b-0c436f231ac0/app/public/bSTuLvTlJViNKarET0OAtfgV68eqwPWDHcupjy2F.png

I use `storage_path('bSTuLvTlJViNKarET0OAtfgV68eqwPWDHcupjy2F.png')` and it return [tenant_domain]/tenancy/assets/bSTuLvTlJViNKarET0OAtfgV68eqwPWDHcupjy2F.png

### Steps to reproduce

```
Image::make(__('Logo'), 'company_logo')->disk('public')
storage_path('filename')
```

### Expected behavior

If I visit [tenant_domain]/tenancy/assets/bSTuLvTlJViNKarET0OAtfgV68eqwPWDHcupjy2F.png the app redirect my on primary domain.

### Laravel version

9.5

### stancl/tenancy version

3.5

**Comment by stancl** [comment]
If this is related to Nova, I recommend asking on our Discord, it's not really a bug with the package.
