### ISSUE TITLE
Cached  Tenancy Resolver not updating or getting invalidated when Tenant data is updated

### ISSUE THREAD

**Issue by alexfarrugia** [stancl/tenancy#903]
### Bug description

I have a custom tenant model which has a jsonb column called settings. Whenever I save some new settings using the below method:
 
        $result = $tenant->forceFill($newSettings)->save();

The value is updated correctly in the database however, if i try to retrieve this value using my laravel API i get the previous value being returned. When I try to invalidate the Cache programmatically (i am using Redis), this still remains the same. I have tried the following options:

Cache:flush();
Redis:flushDb();
Cache::forget(config('tenancy.cache.tag_base') . tenancy()->tenant->id);

but none of them work. The only methods which work are:

1) php artisan cache:clear
2) logging in to redis-cli and trying FLUSH-ALL

It seems like the offending key is the Tenancy Resolver key which usually is in this format:

_tenancy_resolver:App\Resolvers\TenantResolver:["42c70ecb-10e8-44eb-b07d-4ec262d5f2ae"]

and which stubbornly fails to get invalidated in my case. 

### Steps to reproduce

Tenant Model:

```
class Tenant extends BaseTenant implements TenantWithDatabase
{
    use HasDatabase;
    use HasDomains;

    protected $connection = 'central';
    protected $casts = [
        'id' => 'string',
        'settings' => 'array',
    ];
    protected $fillable = [
        'name', 'data', 'friendly_name', 'user_limit', 'settings'
    ];

    public static function getCustomColumns(): array
    {
        return [
            'id',
            'name',
            'data',
            'friendly_name',
            'user_limit',
            'settings',
            'created_at',
            'updated_at',
            'deleted_at'
        ];
    }

    public function users()
    {
        return $this->belongsToMany(User::class, 'tenant_user', 'tenant_id', 'user_id', 'id', 'id')
            ->using(TenantPivot::class);
    }

    public function settings()
    {
        return new TenantSettings($this->settings ? $this->settings : [], $this);
    }

}
````

From my controller I then call

```
        $newSettings = ['test' => 'abc', 'testArray' => ['a','b','c']];
        $result = $tenant->forceFill($newSettings)->save();
        return 1;
````

### Expected behavior

Database value in column settings is updated.
Cached value is also updated

### Laravel version

8.0

### stancl/tenancy version

3.5

**Comment by stancl** [comment]
Please provide proper steps to reproduce this.

Also, I don't know if `$result = ...->save()` does what you're expecting it to do. `save()` generally returns whether something was saved or not.

**Comment by alexfarrugia** [comment]
Hi @stancl , thanks I have added steps to reproduce. The ```save()``` method works since when I check the value within my database, the newest value provided is read, it also returns a value of true. Therefore from an eloquent point of view, this is working. The issue is that the cached Tenancy Resolver is not getting invalidated or updated.

**Comment by stancl** [comment]
This seems like a usage thing, I'd recommend asking on Discord.

For reproduction steps, don't just include your code, but include a minimal example that reproduces the issue. You should be able to have code that doesn't reproduce the issue, and code that reproduces the issue, to show the difference **when** this happens.

If the feature simply "doesn't work" for you at all, but works for everyone else, it's a usage issue.

**Comment by alexfarrugia** [comment]
hi @stancl , I've asked on discord yesterday and while i got a reply, it didn't address the issue. Is there a correct way to manually invalidate the tenancy resolver key specifically? Because I even tried to do this using the following techniques but to no avail:

```
Cache::forget(config('tenancy.cache.tag_base') . tenancy()->tenant->id);
Cache::tags(config('tenancy.cache.tag_base') . tenancy()->tenant->id)->flush();
```

**Comment by ManissDev** [comment]
I have the same problem, cache is not invalidating when you delete a tenant...

**Comment by alexfarrugia** [comment]
in the end i resolved this using: 
```Artisan:call('cache:clear');```
