### ISSUE TITLE
Http fake not respected after tenant change in userland code

### ISSUE THREAD

**Issue by megawubs** [stancl/tenancy#908]
### Bug description

Our central application receives multiple webhooks from different vendors. Inside this webhook controller, depending on the data that is received we'll switch tenant context.

In our test, we fake certain http endpoints that are executed after a webhook comes in. But, when the tenant is switched, the http calls are done for real. When digging deeper we've found out that before the switch `Http::getFacadeRoot()` returns a `Illuminate\Http\Client\Factory` with `recording` set to `true` and with a filled `stubCallbacks`. But  After the tenant is switched and inside the closure, `Http::getFacadeRoot()` returns a new instance with `recording` set to false, and `stubCallbacks` being an empty collection.

### Steps to reproduce

```php
class HttpFakeInTenantScopeTest extends TestCase
{
    public function test_tenant_switching_with_http_fake(): void
    {
        $this->createTenant();

        Http::fake([
            'https://google.com' => Http::response(),
        ]);

        $response = Http::get('https://google.com');
        $this->assertEmpty($response->body());
        Tenant::first()->run(function (): void {
            $response = Http::get('https://google.com');
            $this->assertEmpty($response->body()); //this fails
        });
    }
}
```

### Expected behavior

I expect to be able to setup my http fake responses inside a test, and it not forgetting them when the code underneath my test switches the tenant.

### Laravel version

8.83.19

### stancl/tenancy version

3.5.8

**Comment by megawubs** [comment]
After some more digging, we've found that `Stancl\Tenancy\Bootstrappers\CacheTenancyBootstrapper` resets the facade cache on line 55

**Comment by stancl** [comment]
I think it only clears the cached instance for the `Cache` facade, not any other facade.

**Comment by megawubs** [comment]
When I look into `clearResolvedInstances` it sets `static::$resolvedInstance = [];` which does this on the `Facade` class. In my knowledge this wipes all resovled instances from the `Facade` class, resulting in every facade being "lost" and needing to recreate their accessor. In fact, we just ran into the same problem with `Event::fake()` and `Bus::fake()`.

Should this line not be:

```php
Facade::clearResolvedInstance('cache');
```

**Comment by stancl** [comment]
We seem to be unable to reproduce this. If it's still happening to you, feel free to provide more details.

**Comment by megawubs** [comment]
Did you try the provided testcase? And did it succeed? If so, that's interesting 🤔

**Comment by abrardev99** [comment]
> Did you try the provided testcase

Yes, we did. The test is passing, and Http::fake is working fine. We have tested other facades you mentioned like `Bus, Event`. All are working fine.
