### ISSUE TITLE
Problem with multiple central domains and named routes

### ISSUE THREAD

**Issue by victorelec14** [stancl/tenancy#911]
### Bug description

If you have several central domains and you generate the cache of the routes, it will give the next error.

Error:
```
php artisan route:cache
Route cache cleared successfully.

   LogicException 

  Unable to prepare route [test] for serialization. Another route has already been assigned name [test].
```

If I leave only 1 central domain it will work fine.

If I remove the names of the routes it will work fine.

Route List
```
php artisan route:list

GET|HEAD        127.0.0.1/test ............................................................................................................................................................. test › TenantsController  
  GET|HEAD        localhost/test ............................................................................................................................................................. test › TenantsController  
  GET|HEAD        custom.dev/test ............................................................................................................................................................ test › TenantsController 
```

thanks

### Steps to reproduce

1. Add Central domains 

```php
// /config/tenancy.php
/**
     * The list of domains hosting your central app.
     *
     * Only relevant if you're using the domain or subdomain identification middleware.
     */
    'central_domains' => [
        '127.0.0.1',
        'localhost',
        'custom.dev',
    ],
```

2. Add the route
```php
/routes/web.php

Route::middleware(['universal', InitializeTenancyByDomain::class])->controller(TenantsController::class)->group(
    function () {
        Route::name('test')->get('/test', function () {
            return 'okkkk';
        });
    }
);
```

3. refresh routes cache
> php artisan route:cache

### Expected behavior

correctly generate the routes cache

### Laravel version

9.20.0

### stancl/tenancy version

3.5.7

**Comment by stancl** [comment]
This isn't a bug, it's mentioned in the documentation. You cannot use named routes if you define them multiple times. That's unfortunately how Laravel works and out of our control.

**Comment by chrillep** [comment]
https://tenancyforlaravel.com/docs/v3/quickstart/#central-routes
use
`->name("{$domain}.")`
?

```php
protected function mapWebRoutes()
{
    foreach ($this->centralDomains() as $domain) {
        Route::middleware('web')
            ->domain($domain)
            ->name("{$domain}.")
            ->namespace($this->namespace)
            ->group(base_path('routes/web.php'));
    }
}
```

ofc this intruduces other problems ... :)

**Comment by MCKLtech** [comment]
I came across this today and wanted to check in Laravel 11 if the 'fix' is basically that route:cache cannot be used?

**Comment by stancl** [comment]
https://github.com/archtechx/tenancy/issues/911#issuecomment-1204484763

Cached routes are unrelated. Not using them makes this at best flaky, but incorrect regardless. Just don't use conflicting route names, use separate prefixes.
