### ISSUE TITLE
Getting raw validation messages instead of pretty formatted messages

### ISSUE THREAD

**Issue by amitshrestha221** [stancl/tenancy#913]
### Bug description

I am facing issue with the validation library while using tenancyforlaravel package.

I am getting raw validation messages like :

```

[
    "mobile" : [
          "validation.required"
    ]

]


```

instead of The field mobile is required.

Is this a known issue or did I missing something in the package?

Any idea would be appreciated.

### Steps to reproduce

Just facing in every validation.

### Expected behavior

Expected pretty formatted validation messages.

### Laravel version

9.5

### stancl/tenancy version

3.5

**Comment by stancl** [comment]
This seems completely unrelated to Tenancy. Please only use this issue tracker for bugs in Tenancy.
