### ISSUE TITLE
Getting Error Stancl \ Tenancy \ Exceptions \ TenantCouldNotBeIdentifiedOnDomainException

### ISSUE THREAD

**Issue by aniket-singh** [stancl/tenancy#914]
### Bug description

I'm using laravel Livewire in my project and I've enabled Universal route as per documentation. everything was working fine before implementing the universal route. 

Now whenever user try to access a subdomain that does not exist it results in an error stating - "Stancl \ Tenancy \ Exceptions \ TenantCouldNotBeIdentifiedOnDomainException"

If i disable the universal feature from tenancy config then everything seems to work fine and 
```
\Stancl\Tenancy\Middleware\InitializeTenancyByDomain::$onFail = function () {
            return redirect('https://example.com/');
        };
```
redirects the user to main website homepage

is there a way to handle the below exception and redirect the user to homepage or return 404 error

`Stancl \ Tenancy \ Exceptions \ TenantCouldNotBeIdentifiedOnDomainException`

### Steps to reproduce

Enable Universal route in tenant config file and then visit any subdomain that is not assigned to any tenant.

### Expected behavior

User should be redirected to some page or return a 404 error

### Laravel version

9.11

### stancl/tenancy version

3

**Comment by stancl** [comment]
I think this was fixed in https://github.com/archtechx/tenancy/pull/679 for `master`. We won't be changing the logic in `3.x`.

This was recently discussed on Discord, you can search for the convo there — archte.ch/discord
