### ISSUE TITLE
how to use tenant('id') in  "static::creating"

### ISSUE THREAD

**Issue by hai-shift** [stancl/tenancy#921]
i try t use tenant('id')
on model file like this when i use a Morph relationship 
```

  protected static function booted(){
        static::creating(function ($model) { 
            $model->tenant()->associate(tenant('id'));
        });
    }
```

but i cant so i do somthing like this:
```
  protected static function booted(){
        static::creating(function ($model) { 
            $model->tenant()->associate($model?->model()?->first()->tenant_id);
        });
    }

```

how i can do that with tenant('id') ?

**Comment by stancl** [comment]
Use [Discord](https://archte.ch/discord) for support questions.

As I mentioned there already, you can't use `tenant()` when tenancy is not initialized, and `booted()` runs at a very specific point in the request lifecycle.
