### ISSUE TITLE
sanctum/csrf-cookie route

### ISSUE THREAD

**Issue by Allgoodnamesargone** [stancl/tenancy#929]
### Bug description

The issue is that `session.domain` config is not getting set while making a request to this route of sanctum.
However, it does work in other routes (the application routes).

### Steps to reproduce

add
```
\Stancl\Tenancy\Features\TenantConfig::$storageToConfigMap = [
    'SESSION_DOMAIN' => 'session.domain',
    'SANCTUM_STATEFUL_DOMAINS' => 'sanctum.stateful',
];
```
in `boot` method of `AppServiceProvider` or `TenancyServiceProvider`
create a tenant like below:
```
$tenant = Tenant::create([...]);
$tenant->SESSION_DOMAIN = '';
$tenant->SANCTUM_STATEFUL_DOMAINS= ...;
```
Make a request to `/sanctum/csrf-cookie` route of the tenant domain and check what's the domain of the `set-cookie` response headers

### Expected behavior

`/sanctum/csrf-cookie` must return cookies with domain that is set to `session.domain` via:
```
\Stancl\Tenancy\Features\TenantConfig::$storageToConfigMap = [
    'SESSION_DOMAIN' => 'session.domain',
    'SANCTUM_STATEFUL_DOMAINS' => 'sanctum.stateful',
];
```

### Laravel version

9.26.0

### stancl/tenancy version

3.5.9

**Comment by Allgoodnamesargone** [comment]
```
Route::group(['prefix' => config('sanctum.prefix', 'sanctum')], static function () {
    Route::get(
        '/csrf-cookie',
        CsrfCookieController::class . '@show'
    )->middleware([InitializeTenancyByDomain::class, PreventAccessFromCentralDomains::class, 'web'])->name(
        'sanctum.csrf-cookie'
    );
});
```
By adding the code in the above to the `routes/tenant.php` will fix it but well, I'm not sure if this the correct way in terms of security. Also, things will go wrong if Sanctum package change the Controller name or method!

----------
EDIT:
The workaround above prevent access to the route from central domain, tried using Universal routes feature but again and still, the cookie's domain is not set to the tenant domain.

**Comment by Allgoodnamesargone** [comment]
@stancl Do we need to wait for v4 for a solution/fix to this?

**Comment by stancl** [comment]
I haven't had time to go through all this yet, but it's related to an integration so it's not a bug in the package.

I don't remember how Sanctum works internally, but it might be the same issue Fortify has with constructor DI. But that's just a guess, since I haven't had an in-depth look at this.

It's possible that Sanctum is perfectly compatible with Tenancy, and the issue here is just the config mapping (many packages don't support the Tenant Config feature because they read from the config *before* Tenancy has an opportunity to change it, and the value gets "cached" in some property in a singleton registered by the package).

**Comment by Allgoodnamesargone** [comment]
> many packages don't support the Tenant Config feature because they read from the config _before_ Tenancy has an opportunity to change it, and the value gets "cached" in some property in a singleton registered by the package

That's it as far as i checked, Tenant config has not yet changed the configs and Sanctum route returns the response before them all.
there will be no solution then?

**Comment by stancl** [comment]
The general approach to solving this type of issues is to use `Event::listen(TenancyInitialized::class, ...)` (and the same for `TenancyEnded`) to change the property directly on the singleton object, rather than just changing the config values.

**Comment by Allgoodnamesargone** [comment]
> The general approach to solving this type of issues is to use `Event::listen(TenancyInitialized::class, ...)` (and the same for `TenancyEnded`) to change the property directly on the singleton object, rather than just changing the config values.

I may have not understood you correctly, but if you meant i have to listen for `TenancyInitialized::class` event and change things in that event then i have to say that event i not even fired, never if you make a request to `sanctum/csrf-token`
![image](https://user-images.githubusercontent.com/110684470/188405316-9aff8f2d-64ed-4d62-99fe-d3612ace7bbc.png)

Only the `boot()` method of `TenancyServiceProvider` invokes and just that...

used `Event::listen(TenancyInitialized::class, TenancyInitializedListener::class);` in `boot` method but no luck yet.

**Comment by Allgoodnamesargone** [comment]
Hey,
I had to get it fixed so i did.
1. Add `'routes' => false,` to the `sanctum.php` config file.
2. Setup [Universal Routes](https://tenancyforlaravel.com/docs/v3/features/universal-routes)
3. Add the code below in `routes/tenant.php`
```
Route::group(['prefix' => config('sanctum.prefix', 'sanctum')], static function () {
    Route::get(
        '/csrf-cookie',
        \Laravel\Sanctum\Http\Controllers\CsrfCookieController::class . '@show'
    )->middleware(['universal', 'web', \Stancl\Tenancy\Middleware\InitializeTenancyByDomain::class])->name(
        'sanctum.csrf-cookie'
    );
});
```

**Comment by stancl** [comment]
@lukinovec Could you take a look at this?

**Comment by lukinovec** [comment]
I've looked into this, and I couldn't find anything else than [this solution](https://github.com/archtechx/tenancy/issues/929#issuecomment-1246946861). In the `SanctumServiceProvider`, the route is hardcoded along with the middleware, so we either have to override the route, or add the middlewares at some point when the route already exists (the latter would be the best, not sure how to achieve that though).

Maybe @LabSilo's solution should be added to the docs?

**Comment by stancl** [comment]
Yeah, if you can reproduce the issue, and this is a needed solution, then we should add it to the docs.
