### ISSUE TITLE
Need Auth user to be Tenant user data , because every tenancy user have its own Roles and permissions 

### ISSUE THREAD

**Issue by muhammad-salman-khalid** [stancl/tenancy#937]
### Bug description

I have created 2 laravel applications and they are hosted on different servers. I laravel application is called Auth(central database) Application and other 1 is called Tenant Application( tenant databases ).My website have single login system and it will be on Auth App .Auth app is responsible for login register , create tenancy database and seeding .After login user can switch to any tenancy which he belongs, but with login . I need on my tenant application is that when authenticated request comes in with X-tenant approach it should give data from auth()->user from tenancy users table .So that my both apps should be independent .How can I achieve this from this package . I have manage authentication on both applications running on separate VMS  .I need get auth()->user data from tenant app.kindly help me out on this 
thanks 

### Steps to reproduce

I have created 2 laravel applications and they are hosted on different servers. I laravel application is called Auth(central database) Application and other 1 is called Tenant Application( tenant databases )

### Expected behavior

I have created 2 laravel applications and they are hosted on different servers. I laravel application is called Auth(central database) Application and other 1 is called Tenant Application( tenant databases )

### Laravel version

8

### stancl/tenancy version

3

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks
