### ISSUE TITLE
In manual mode, when migrate, need DatabaseTenancyBootstrapper

### ISSUE THREAD

**Issue by santutu** [stancl/tenancy#942]
#### Description

TenancyServiceProvider.php

```
            MigratingDatabase::class => [
                BootDatabaseTenancyListener::class,
            ],
            Events\DatabaseMigrated::class => [
                RevertDatabaseTenancyListener::class,
            ],
```

BootDatabaseTenancyListener.php

```
<?php

namespace App\Listeners;

use Stancl\Tenancy\Bootstrappers\DatabaseTenancyBootstrapper;
use Stancl\Tenancy\Events\Contracts\TenantEvent;

class BootDatabaseTenancyListener {
    public function __construct() {
    }

    public function handle(TenantEvent $event) {
        app(DatabaseTenancyBootstrapper::class)->bootstrap($event->tenant);
    }
}

```

RevertDatabaseTenancyListener.php

```
<?php

namespace App\Listeners;

use Stancl\Tenancy\Bootstrappers\DatabaseTenancyBootstrapper;
use Stancl\Tenancy\Events\Contracts\TenantEvent;

class RevertDatabaseTenancyListener {
    public function __construct() {
    }

    public function handle(TenantEvent $event) {
        app(DatabaseTenancyBootstrapper::class)->revert();
    }
}


```

#### Why this should be added

In manual mode, migration does not work because default db connection is central db.
In document, it is not referred. newbie can be confused.

**Comment by stancl** [comment]
Please add more context, I'm not sure what your point with this issue is exactly.

**Comment by santutu** [comment]
manual mode does not use default db connection by tenant because this mode does not use DatabaseTenancyBootstrapper. but MigrateDatabase use default db connenct. therefore need BootDatabaseTenancy for to set default db connection to tenant in MigrateDatabase. my temporary solution is to add BootDatabaseTenancy listener to MigratingDatabase event

**Comment by stancl** [comment]
Sorry, still don't see your point. If you can write a clear and understandable description, I may reopen.
