### ISSUE TITLE
Tenant could not be identified with tenant_id

### ISSUE THREAD

**Issue by miketimeturner** [stancl/tenancy#948]
### Bug description

Every so often at the MigrateDatabase stage of the TenantCreated pipeline, the pipeline fails with a message of "Tenant could not be identified with tenant_id: ". It appears that the $tenantId is empty when initialising so it cant find the tenant. When the pipeline fails, it will retry but wont go past the CreateDatabase job as TenantDatabaseAlreadyExists.

After more digging, it looks like the Database doesn't even exist but no exception was thrown, the tenant exists and any migration attempt going forward will fail.

### Steps to reproduce

This issue is inconsistent and happens only 10% of the time. Using default jobs for db creation and migrations. Using Redis for Queues and cache.

### Expected behavior

I would expect the migration job to find the tenant and be able to proceed.

### Laravel version

9.30

### stancl/tenancy version

3.5.9

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks
