### ISSUE TITLE
Cannot use Laravel 9 assets compiled with Vite

### ISSUE THREAD

**Issue by rico-ocepek** [stancl/tenancy#951]
# Problem
When using the new `@vite` Blade directive the resulting `<script>` and `<link>` tags all have tenant specific URLs.

For older Laravel versions using Laravel Mix the documentation currently suggests using the `mix()` helper function

> And for JS/CSS assets, you should use mix() or again global_asset()
(https://tenancyforlaravel.com/docs/v3/tenancy-bootstrappers/#filesystem-tenancy-boostrapper)

However, there is no `vite()` helper function equivalent, just this `@vite` Blade directive.

# Cause
I did a bit of investigation on how these asset paths are resolved and the reason why they are being resolved in a tenant context. Apparently it is caused by the `assetPath()` method of the `Illuminate\Foundation\Vite` class which internally uses the `asset()` helper function. 

# My fix
I extended the `Illuminate\Foundation\Vite` class and overrode the `assetPath()` to use the `global_asset()` helper instead of `asset()`.

```
<?php

namespace App\Foundation;

class Vite extends \Illuminate\Foundation\Vite
{
    /**
     * Generate an asset path for the application.
     *
     * @param  string  $path
     * @param  bool|null  $secure
     * @return string
     */
    protected function assetPath($path, $secure = null)
    {
        return global_asset($path);
    }
}
```

Then i added a simple `vite()` helper function mimicking the old `mix()` helper

```
if (! function_exists('vite')) {
    /**
     * Get the path to a versioned Vite file.
     *
     * @param  string  $path
     * @param  string  $manifestDirectory
     * @return \Illuminate\Support\HtmlString|string
     *
     * @throws \Exception
     */
    function vite($path, $manifestDirectory = '')
    {
        return app(Vite::class)(...func_get_args());
    }
}
```

# Feedback / second opinions / solutions

I'm not a Laravel expert by any means so I'm not sure whether my approach is a good one. Though I feel like it's somewhat solid because it reuses the path resolution of the existing Vite foundation class, which feels about right.

Still please let me know if anybody has anything to add here :)

**Comment by rico-ocepek** [comment]
I submitted this as a feature request but really it could be quite a deal breaker for people coming along with their shiny and new Laravel 9 projects.

**Comment by stancl** [comment]
You can just disable `asset_helper_tenancy` in the config

**Comment by rico-ocepek** [comment]
Fair enough 😄 

Thanks!
