### ISSUE TITLE
bug in Request data identification 

### ISSUE THREAD

**Issue by KaremMohamed0010** [stancl/tenancy#955]
### Bug description

hi everyone 
i have backend tenant based app on this package 
so i am using Request data identification all things good 
the problem is when tenant try to add file to local storage it i use this code below
i get the url 
but when i try to open it i get 

"Tenant could not be identified by request data with payload"

### Steps to reproduce

```
if ($request->file('file')) {
    $filePath = $request->file('file')->store('example-folder-name');

    $file = new File;
    $file->url = $filePath;
    $file->save();
}
```
and retrieve file with 
` `tenant_asset($file->url)
`

### Expected behavior

to see the file 

### Laravel version

8.2.1

### stancl/tenancy version

3.5

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks
