### ISSUE TITLE
any_name.host_name shows my tenant landing page

### ISSUE THREAD

**Issue by valpuia** [stancl/tenancy#959]
### Bug description

I have set up `demo.localhost` for my tenant with database.. it's working as expected. But if I type `foo.localhost` or `bar.localhost` the tenant landing page is still showing, but I don't have any tenant for `foo` or `bar` nor setup any database for them. Maybe it's because of the apache server. but i'm not sure.

### Steps to reproduce

- install laravel
- composer require stancl/tenancy
- php artisan tenancy:install
- setup database and create first tenant. eg: `foo.localhost`
- try to go to `bar.localhost` which is not present in the tenant

### Expected behavior

`This site can’t be reached` localhost refused to connect.

### Laravel version

v 9.19

### stancl/tenancy version

v 3.5

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks
