### ISSUE TITLE
Tenant cannot be created

### ISSUE THREAD

**Issue by asagtc** [stancl/tenancy#972]
### Bug description

Stancl\Tenancy\Exceptions\TenantDatabaseAlreadyExistsException: Tenant cannot be created

this exception appear on ploi when queue start on registeration

### Expected behavior

queue creat the database twice but only one appear?

### Laravel version

9

### stancl/tenancy version

3

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks
