### ISSUE TITLE
i can't getting any data from users table 

### ISSUE THREAD

**Issue by arabnewscms** [stancl/tenancy#976]
I'm not sure I have the problem but I think it comes from the package 
I have connections to other tables in the same tenant but when I try to get user data from the same tenant it tells me that the table does not exist in the central  tenants database
Is it an bug or is there a mistake I did not do, knowing that I followed the installation steps well

The strange thing is that it works with other tables and actually connects to the tenant database, but when I try to find a user through the App\Model\User, it tells me that the connection is on the central database and not on the same tenant database

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tenant.users' doesn't exist (SQL: select count(*) as aggregate from `users` where `account_type` = user)
```
Laravel Version: 9.*
package Version: 3.*
tenant database : tenant_foo 
central database : tenants
Can someone tell me what to do?

**Comment by arabnewscms** [comment]
anyone can help 
i get data from another table like Role or Group 
but He only wants to view the data through the  central database not by tenant  db

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks
