### ISSUE TITLE
Weird dates in sqlite tenant database

### ISSUE THREAD

**Issue by Dennise89** [stancl/tenancy#987]
### Bug description

I'm locally developing with sqlite and Laravel 9. When I add a database migration to the tenants folder and run it, all works fine.
But when I add data to the database it formats the dates in a weird format and also it does not retrieve these dates correctly.

For example; it saves the date to the database like this: `1666796400000` and it will retrieve it like `54788-09-04 00:00:00`

### Steps to reproduce

Install fresh laravel version and use sqlite as a database.
Install the package.
Create a migration in the tenants folder
Run the migration
Review the outcome

### Expected behavior

I just want it to add the date like 2022-10-26 15:00:00.000 and also to be retrieved properly.

### Laravel version

9.26.1

### stancl/tenancy version

3.6.0

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

Thanks

**Comment by Dennise89** [comment]
@stancl I don't think it's in my setup because the tables in the normal database are created with normal date times. And because your package makes the tenant databases I think the issue is in your package.

**Comment by stancl** [comment]
The package just creates an empty `.sqlite` file and then Laravel runs the migrations and does everything else.
