### ISSUE TITLE
Caching the existance of a tenants database

### ISSUE THREAD

**Issue by dorep** [stancl/tenancy#988]
Hello,

#### Description
We have noticed, that on every new request, this query is executed:
`SELECT datname FROM pg_database WHERE datname = '$name'"`
Is it possible to cache this? It is executed in `PostgreSQLDatabaseManager->databaseExists(string $name)`. I am not sure, maybe it must be queried every time.

#### Why this should be added
It would reduce the number of queries, that return the same result every time.

We are already using DomainTenantResolver::$shouldCache.
Thank you very much!

Best regards, Dore

**Comment by stancl** [comment]
1. I told you to use the right support channel https://github.com/stancl/tenancy-docs/issues/221#issuecomment-1294818942
2. When you're creating a new issue, you have to select the type. This includes a very clear option for support questions ![CleanShot 2022-10-28 at 12 36 39@2x](https://user-images.githubusercontent.com/33033094/198568101-cd2683e9-1c57-46d0-9058-de1834df3306.png)
3. You open a feature request

Why?

**Comment by dorep** [comment]
Sorry about that, I guess I thought wrong. I'll post this to the discord server.
