### ISSUE TITLE
Help: Tenant schedule 

### ISSUE THREAD

**Issue by xDemon200** [stancl/tenancy#991]
I need to be able to schedule a job on time according to a column stored in a database in a configuration table.

I have the following code inside the file app/Console/Kernel.php:

![image](https://user-images.githubusercontent.com/24462068/199845723-88c06db8-512b-4a76-96ec-dcac1b665906.png)

i have a table called configurations which has an attribute called time_of_notifications within each tenant:

` $time = Configuration::where('description', 'time_of_notifications')->first()->value;`

I need to be able to assign the tenant settings to the scheduled job.

try this but it does not work

![image](https://user-images.githubusercontent.com/24462068/199846258-3b4e08e3-576a-4c18-8680-f7e3a499de1c.png)

it is worth mentioning that I previously had only the following in both Kernel.php and my SendWhatsappPaymentNotification.php file.

![image](https://user-images.githubusercontent.com/24462068/199846481-a3f77eb6-f7ac-43b9-8fa2-2b8c79a3505d.png)

![image](https://user-images.githubusercontent.com/24462068/199846577-591c90dc-cdbd-4c1e-8f1c-6e8552d4fd16.png)

**Comment by stancl** [comment]
This isn't a feature request. Use the proper support channels.
